using Akbura.Language;
using Akbura.Language.CodeGeneration;
using Akbura.Language.Syntax;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.IO;

namespace Akbura.UnitTests;

public sealed class AkburaGenerationCatalogTests
{
    [Fact]
    public void Create_CollectsComponentExternalAndInlineAkcssInputs()
    {
        var fixture = CreateFixture();
        var catalog = fixture.Catalog;

        var component = Assert.Single(catalog.Components);
        var external = Assert.Single(catalog.ExternalAkcssModules);
        var inline = Assert.Single(catalog.InlineAkcssModules);

        Assert.Equal("Views/PlannerView.akbura", component.SourcePath);
        Assert.Equal("Styles/Shared.akcss", external.SourcePath);
        Assert.Equal("Styles/Shared.akcss", external.ModuleIdentity);
        Assert.Equal("Views/PlannerView.akbura", inline.SourcePath);
        Assert.Equal("Views/PlannerView.akbura.inline.0.akcss", inline.ModuleIdentity);

        var externalSyntax = Assert.IsType<AkburaSyntax>(external.Module.DeclaringSyntax, exactMatch: false);
        var inlineSyntax = Assert.IsType<AkburaSyntax>(inline.Module.DeclaringSyntax, exactMatch: false);

        Assert.Equal(
            AkcssGeneratedModuleNames.GetFullyQualifiedTypeName("Demo", external.ModuleIdentity),
            catalog.AkcssModuleTypeNames[externalSyntax]);

        Assert.Equal(
            AkcssGeneratedModuleNames.GetFullyQualifiedTypeName("Demo", inline.ModuleIdentity),
            catalog.AkcssModuleTypeNames[inlineSyntax]);

        Assert.True(catalog.AkcssSourceMap.TryGetLineDirective(externalSyntax, out _, out var externalPath));
        Assert.Equal(fixture.ExternalAkcssPath, externalPath);

        Assert.True(catalog.AkcssSourceMap.TryGetLineDirective(inlineSyntax, out _, out var inlinePath));
        Assert.Equal(fixture.ComponentPath, inlinePath);
    }

    [Fact]
    public void ModulePlanner_AssignsStableSymbolAndRuntimeIndices()
    {
        var fixture = CreateFixture();
        ref readonly var input = ref fixture.Catalog.ExternalAkcssModules.ItemRef(0);

        var plan = AkcssModulePlanner.Create(input, fixture.Catalog.RootNamespace);

        try
        {
            Assert.Equal("Styles/Shared.akcss", plan.SourcePath);
            Assert.Equal("Styles/Shared.akcss", plan.ModuleIdentity);
            Assert.Equal("Demo.Generated", plan.GeneratedNamespace);

            Assert.Equal(
                AkcssGeneratedModuleNames.GetTypeName("Styles/Shared.akcss"),
                plan.GeneratedTypeName);

            Assert.Equal(input.Module.MetadataName, plan.MetadataName);

            Assert.False(plan.IsInlined);
            Assert.Equal(2, plan.Symbols.Length);
            Assert.Equal(2, plan.RuntimeStyles.Length);

            Assert.Equal(AkcssSymbolGenerationKind.Style, plan.Symbols[0].Kind);
            Assert.Equal(AkcssSymbolGenerationKind.Utility, plan.Symbols[1].Kind);

            Assert.Equal(0, plan.Symbols[0].SymbolIndex);
            Assert.Equal(1, plan.Symbols[1].SymbolIndex);
            Assert.Equal(0, plan.Symbols[0].RuntimeStyleIndex);
            Assert.Equal(1, plan.Symbols[1].RuntimeStyleIndex);
            Assert.False(plan.Symbols[0].HasErrors);
            Assert.False(plan.Symbols[1].HasErrors);

            Assert.Equal(AkcssRuntimeStyleKind.Generated, plan.RuntimeStyles[0].Kind);
            Assert.Equal(AkcssRuntimeStyleKind.Generated, plan.RuntimeStyles[1].Kind);
        }
        finally
        {
            plan.ReturnToPool();
        }
    }

    [Fact]
    public void ModuleWriter_WritesCompilableModuleMetadata()
    {
        var fixture = CreateFixture();
        var input = fixture.Catalog.ExternalAkcssModules[0];
        var plan = AkcssModulePlanner.Create(input, fixture.Catalog.RootNamespace);

        try
        {
            using var codeWriter = new CodeWriter("\r\n");

            var writer = new AkcssModuleWriter(
                codeWriter,
                fixture.Catalog.AkcssSourceMap);

            codeWriter.WriteLine("// <auto-generated />");
            codeWriter.WriteLine("#nullable enable");

            writer.WriteAssemblyReference(plan);

            codeWriter.WriteLine();
            codeWriter.Write("namespace ");
            codeWriter.Write(plan.GeneratedNamespace);
            codeWriter.WriteLine();
            codeWriter.WriteLine("{");
            codeWriter.CurrentIndent += codeWriter.TabSize;

            writer.WriteDeclarationAttributes(plan);

            codeWriter.Write("public static class ");
            codeWriter.Write(plan.GeneratedTypeName);
            codeWriter.WriteLine();
            codeWriter.WriteLine("{");
            codeWriter.CurrentIndent += codeWriter.TabSize;

            writer.WriteConstants(plan);
            codeWriter.WriteLine();

            writer.WriteStyleCollection(plan);
            codeWriter.WriteLine();

            writer.WriteMetadataCarriers(plan);
            codeWriter.WriteLine();

            codeWriter.WriteLine(
                "private sealed class Style_0 : global::Akbura.Akcss.AkcssStyle");
            codeWriter.WriteLine("{");
            codeWriter.WriteLine("}");
            codeWriter.WriteLine();

            codeWriter.WriteLine(
                "private sealed class Style_1 : global::Akbura.Akcss.AkcssStyle");
            codeWriter.WriteLine("{");
            codeWriter.WriteLine("}");

            codeWriter.CurrentIndent -= codeWriter.TabSize;
            codeWriter.WriteLine("}");

            codeWriter.CurrentIndent -= codeWriter.TabSize;
            codeWriter.WriteLine("}");

            var output = codeWriter.GetText().ToString();

            Assert.Contains(
                "[assembly: global::Akbura.CompilerAnotations.AkcssModuleReferenceAttribute(" +
                "typeof(global::" +
                plan.GeneratedNamespace +
                "." +
                plan.GeneratedTypeName +
                "))]",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "[global::Akbura.CompilerAnotations.AkcssModuleAttribute(",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "public const string MetadataName = ",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "public const string SourcePath = \"Styles/Shared.akcss\";",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "public static readonly global::System.Collections.Immutable.ImmutableArray<" +
                "global::Akbura.Akcss.AkcssStyle> Styles =",
                output,
                StringComparison.Ordinal);

            Assert.Contains("new Style_0()", output, StringComparison.Ordinal);
            Assert.Contains("new Style_1()", output, StringComparison.Ordinal);

            Assert.Contains(
                "public static class __AkcssMetadata_0",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "public static class __AkcssMetadata_1",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "Kind = global::Akbura.CompilerAnotations.AkcssSymbolKind.Style",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "Kind = global::Akbura.CompilerAnotations.AkcssSymbolKind.Utility",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "RuntimeStyleIndex = 0",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "RuntimeStyleIndex = 1",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "[global::Akbura.CompilerAnotations.AkcssUtilityParameterAttribute(",
                output,
                StringComparison.Ordinal);

            Assert.Contains("Ordinal = 0", output, StringComparison.Ordinal);
            Assert.Contains("CSharpName = \"value\"", output, StringComparison.Ordinal);
            Assert.Contains("IsOptional = false", output, StringComparison.Ordinal);

            Assert.Contains(
                "[global::Akbura.CompilerAnotations.AkcssOperationAttribute(",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "Kind = global::Akbura.CompilerAnotations.AkcssOperationKind.Set",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "Origin = global::Akbura.CompilerAnotations.AkcssOperationOriginKind.Direct",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "PropertyAccessKind = " +
                "global::Akbura.CompilerAnotations.AkcssPropertyAccessKind.AvaloniaProperty",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "ValueKind = " +
                "global::Akbura.CompilerAnotations.AkcssPropertyValueKind.CSharpExpression",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "Priority = global::Akbura.CompilerAnotations.AkcssOperationPriority.Style",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "Property = \"Height\"",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "Property = \"Width\"",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "Expression = \"20\"",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "SourceStart = ",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "SourceLength = ",
                output,
                StringComparison.Ordinal);

            var generatedTree = CSharpSyntaxTree.ParseText(
                output,
                CSharpParseOptions.Default.WithLanguageVersion(
                    LanguageVersion.Preview),
                path: "AkcssModuleWriter.g.cs");

            var diagnostics = fixture.Catalog.Compilation.CSharpCompilation
                .AddSyntaxTrees(generatedTree)
                .GetDiagnostics()
                .Where(static diagnostic =>
                    diagnostic.Severity is
                        DiagnosticSeverity.Warning or
                        DiagnosticSeverity.Error)
                .ToArray();

            Assert.True(
                diagnostics.Length == 0,
                string.Join(
                    Environment.NewLine,
                    diagnostics.Select(
                        static diagnostic =>
                            diagnostic.ToString())) +
                Environment.NewLine +
                output);
        }
        finally
        {
            plan.ReturnToPool();
        }
    }

    [Fact]
    public void ModuleWriter_WritesCompilableClassRuntimeStyle()
    {
        var fixture = CreateFixture();
        var input = fixture.Catalog.ExternalAkcssModules[0];
        var plan = AkcssModulePlanner.Create(
            input,
            fixture.Catalog.RootNamespace);

        try
        {
            using var codeWriter = new CodeWriter("\r\n");

            var writer = new AkcssModuleWriter(
                codeWriter,
                fixture.Catalog.AkcssSourceMap);

            codeWriter.WriteLine(
                "// <auto-generated />");

            codeWriter.WriteLine(
                "#nullable enable");

            codeWriter.Write("namespace ");
            codeWriter.Write(plan.GeneratedNamespace);
            codeWriter.WriteLine();

            codeWriter.WriteLine("{");
            codeWriter.CurrentIndent += codeWriter.TabSize;

            codeWriter.WriteLine(
                "internal static class RuntimeStyles");

            codeWriter.WriteLine("{");
            codeWriter.CurrentIndent += codeWriter.TabSize;

            Assert.True(
                writer.WriteClassStyles(plan));

            codeWriter.CurrentIndent -= codeWriter.TabSize;
            codeWriter.WriteLine("}");

            codeWriter.CurrentIndent -= codeWriter.TabSize;
            codeWriter.WriteLine("}");

            var output = codeWriter.GetText().ToString();

            Assert.Contains(
                "[global::Akbura.CompilerAnotations.StyleNameAttribute(\"shared\")]",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "private sealed class Style_0 : global::Akbura.Akcss.AkcssClass",
                output,
                StringComparison.Ordinal);

            Assert.DoesNotContain(
                "class Style_1",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "public override void Update(object __target)",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "global::System.ArgumentNullException.ThrowIfNull(__target);",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                ".SetValue(",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "HeightProperty",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "20);",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "public override void Reset(object __target)",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "base.Reset(__target);",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                ".ClearValue(",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "#line (",
                output,
                StringComparison.Ordinal);

            var generatedTree = CSharpSyntaxTree.ParseText(
                output,
                CSharpParseOptions.Default.WithLanguageVersion(
                    LanguageVersion.Preview),
                path: "AkcssStyleWriter.g.cs");

            var diagnostics = fixture.Catalog.Compilation.CSharpCompilation
                .AddSyntaxTrees(generatedTree)
                .GetDiagnostics()
                .Where(static diagnostic =>
                    diagnostic.Severity is
                        DiagnosticSeverity.Warning or
                        DiagnosticSeverity.Error)
                .ToArray();

            Assert.True(
                diagnostics.Length == 0,
                string.Join(
                    Environment.NewLine,
                    diagnostics.Select(
                        static diagnostic =>
                            diagnostic.ToString())) +
                Environment.NewLine +
                output);
        }
        finally
        {
            plan.ReturnToPool();
        }
    }

    [Fact]
    public void ModuleWriter_WritesCompilableUtilityRuntimeStyle()
    {
        var fixture = CreateFixture();
        var input = fixture.Catalog.ExternalAkcssModules[0];
        var plan = AkcssModulePlanner.Create(input, fixture.Catalog.RootNamespace);

        try
        {
            using var codeWriter = new CodeWriter("\r\n");

            var writer = new AkcssModuleWriter(
                codeWriter,
                fixture.Catalog.AkcssSourceMap);

            codeWriter.WriteLine("// <auto-generated />");
            codeWriter.WriteLine("#nullable enable");

            codeWriter.Write("namespace ");
            codeWriter.Write(plan.GeneratedNamespace);
            codeWriter.WriteLine();

            codeWriter.WriteLine("{");
            codeWriter.CurrentIndent += codeWriter.TabSize;

            codeWriter.WriteLine("internal static class RuntimeUtilities");
            codeWriter.WriteLine("{");
            codeWriter.CurrentIndent += codeWriter.TabSize;

            Assert.True(writer.WriteUtilities(plan));

            codeWriter.CurrentIndent -= codeWriter.TabSize;
            codeWriter.WriteLine("}");

            codeWriter.CurrentIndent -= codeWriter.TabSize;
            codeWriter.WriteLine("}");

            var output = codeWriter.GetText().ToString();
            var utilityName = plan.Symbols[1].Symbol.Name;

            Assert.Contains(
                "[global::Akbura.CompilerAnotations.StyleNameAttribute(\"" +
                utilityName +
                "\")]",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "private sealed class Style_1 : global::Akbura.Akcss.AkcssUtility<",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "private readonly global::System.Collections.Immutable.ImmutableArray<" +
                "global::Akbura.Akcss.AkcssUtilityOperation> __operations;",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "new Operation_0(this)",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "public override global::System.Collections.Immutable.ImmutableArray<" +
                "global::Akbura.Akcss.AkcssUtilityOperation> Operations => __operations;",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "public override void Update(object __target,",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "private sealed class Operation_0 : global::Akbura.Akcss.AkcssUtilityOperation",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "\"property:Width\"",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "global::Akbura.CompilerAnotations.AkcssOperationPriority.Style",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "public override bool IsActive(",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "public override global::System.IDisposable Apply(",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "__bindingPriority",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                ".WidthProperty",
                output,
                StringComparison.Ordinal);

            Assert.Contains(
                "public override void Reset(object __target)",
                output,
                StringComparison.Ordinal);

            var generatedTree = CSharpSyntaxTree.ParseText(
                output,
                CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview),
                path: "AkcssUtilityWriter.g.cs");

            var diagnostics = fixture.Catalog.Compilation.CSharpCompilation
                .AddSyntaxTrees(generatedTree)
                .GetDiagnostics()
                .Where(static diagnostic =>
                    diagnostic.Severity is DiagnosticSeverity.Warning or DiagnosticSeverity.Error)
                .ToArray();

            Assert.True(
                diagnostics.Length == 0,
                string.Join(
                    Environment.NewLine,
                    diagnostics.Select(static diagnostic => diagnostic.ToString())) +
                Environment.NewLine +
                output);
        }
        finally
        {
            plan.ReturnToPool();
        }
    }

    private static CatalogFixture CreateFixture()
    {
        const string rootNamespace = "Demo";

        const string componentSource =
            """
            using Avalonia.Controls;
            using Demo.Styles.Shared.akcss;

            @akcss {
                @using Avalonia.Controls;

                .local {
                    Width: 10;
                }
            }

            <Border class="local shared" />
            """;

        const string externalAkcssSource =
            """
            @using Avalonia.Controls;

            .shared {
                Height: 20;
            }

            @utilities {
                .spacing-(double value) {
                    Width: value;
                }
            }
            """;

        const string csharpSource =
            """
            namespace Demo;

            public partial class PlannerView
            {
            }
            """;

        var projectDirectory = Path.Combine(Path.GetTempPath(), "AkburaGenerationCatalogTests");
        var componentPath = Path.Combine(projectDirectory, "Views", "PlannerView.akbura");
        var externalAkcssPath = Path.Combine(projectDirectory, "Styles", "Shared.akcss");
        var externalSourcePath = "Styles/Shared.akcss";

        var externalLogicalName = AkcssGeneratedModuleNames.GetMetadataName(
            rootNamespace,
            externalSourcePath);

        var componentTree = ComponentSyntaxTree.ParseText(
            SourceText.From(componentSource),
            componentPath);

        var externalAkcssTree = AkcssSyntaxTree.ParseText(
            SourceText.From(externalAkcssSource),
            externalAkcssPath,
            externalLogicalName);

        var parseOptions = CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview);

        var csharpCompilation = CSharpCompilation.Create(
            "AkburaGenerationCatalogTests",
            syntaxTrees: [CSharpSyntaxTree.ParseText(csharpSource, parseOptions)],
            references: SymbolTests.CreateAvaloniaReferences(),
            options: new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable));

        var catalog = AkburaGenerationCatalogBuilder.Create(
            csharpCompilation,
            [componentTree, externalAkcssTree],
            rootNamespace,
            projectDirectory);

        return new CatalogFixture(catalog, componentPath, externalAkcssPath);
    }

    private sealed class CatalogFixture
    {
        public CatalogFixture(
            AkburaGenerationCatalog catalog,
            string componentPath,
            string externalAkcssPath)
        {
            Catalog = catalog;
            ComponentPath = componentPath;
            ExternalAkcssPath = externalAkcssPath;
        }

        public AkburaGenerationCatalog Catalog { get; }

        public string ComponentPath { get; }

        public string ExternalAkcssPath { get; }
    }
}
