using System.Reflection;
using Akbura.BlackSilence;
using Akbura.Language;
using Akbura.Language.Syntax;
using CommunityToolkit.Mvvm.ComponentModel;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Akbura.UnitTests;

public sealed class CommunityToolkitMetadataBoundaryTests
{
    private const string ProducerSource =
        """
        using System.Globalization;
        using CommunityToolkit.Mvvm.ComponentModel;
        using CommunityToolkit.Mvvm.Input;

        namespace Producer;

        public interface IGreetingService
        {
            string CreateGreeting(string? userName);
        }

        public abstract class ViewModelBase : ObservableObject
        {
        }

        public sealed partial class MainViewModel : ViewModelBase
        {
            private readonly IGreetingService _greetingService;

            public MainViewModel(IGreetingService greetingService)
            {
                _greetingService = greetingService;
            }

            [ObservableProperty]
            [NotifyPropertyChangedFor(nameof(CountText))]
            [NotifyCanExecuteChangedFor(nameof(ResetCounterCommand))]
            private int _count;

            public string CountText => Count.ToString(CultureInfo.InvariantCulture);

            [ObservableProperty]
            [NotifyPropertyChangedFor(nameof(Greeting))]
            private string? _userName = "Akbura";

            public string Greeting => _greetingService.CreateGreeting(UserName);

            [ObservableProperty]
            private string _generatedStatus = "Generated by CommunityToolkit.Mvvm";

            [RelayCommand]
            private void Increment() => Count++;

            [RelayCommand(CanExecute = nameof(CanResetCounter))]
            private void ResetCounter() => Count = 0;

            private bool CanResetCounter() => Count != 0;

            [RelayCommand]
            private void UseExampleName() => UserName = "Developer";
        }
        """;

    private const string ConsumerMarkup =
        """
        using Avalonia.Controls;
        using Producer;

        namespace Consumer;

        <StackPanel x.DataType="MainViewModel">
            <TextBlock Text=${Binding GeneratedStatus} />
            <Button Command=${Binding IncrementCommand} />
        </StackPanel>
        """;

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void CompletedProducerMetadataExposesGeneratedMembersToFreshAkburaConsumer(bool referenceAssembly)
    {
        var parseOptions = CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview);
        var toolkitReference = MetadataReference.CreateFromFile(typeof(ObservableObject).Assembly.Location);
        var references = SymbolTests.CreateAvaloniaReferences()
            .Where(reference => !string.Equals(reference.Display, toolkitReference.Display, StringComparison.OrdinalIgnoreCase))
            .Append(toolkitReference)
            .ToArray();
        var producer = CSharpCompilation.Create(
            "Producer.ViewModels",
            [CSharpSyntaxTree.ParseText(ProducerSource, parseOptions, "MainViewModel.cs")],
            references,
            new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable));
        GeneratorDriver toolkitDriver = CSharpGeneratorDriver.Create(
            LoadCommunityToolkitGenerators(),
            parseOptions: parseOptions);

        toolkitDriver = toolkitDriver.RunGeneratorsAndUpdateCompilation(
            producer,
            out var completedProducer,
            out var toolkitDiagnostics);

        AssertNoErrors(toolkitDiagnostics);
        AssertNoErrors(completedProducer.GetDiagnostics());
        var producerType = Assert.IsAssignableFrom<INamedTypeSymbol>(
            completedProducer.GetTypeByMetadataName("Producer.MainViewModel"));
        Assert.Single(producerType.GetMembers("IncrementCommand").OfType<IPropertySymbol>());
        Assert.Single(producerType.GetMembers("ResetCounterCommand").OfType<IPropertySymbol>());
        Assert.Single(producerType.GetMembers("UseExampleNameCommand").OfType<IPropertySymbol>());
        Assert.Single(producerType.GetMembers("GeneratedStatus").OfType<IPropertySymbol>());
        Assert.Single(producerType.GetMembers("Count").OfType<IPropertySymbol>());

        using var producerImage = new MemoryStream();
        var emitResult = completedProducer.Emit(
            producerImage,
            options: referenceAssembly
                ? new Microsoft.CodeAnalysis.Emit.EmitOptions(
                    metadataOnly: true,
                    includePrivateMembers: false)
                : null);
        Assert.True(emitResult.Success, string.Join(Environment.NewLine, emitResult.Diagnostics));
        var producerReference = MetadataReference.CreateFromImage(producerImage.ToArray());
        var consumer = CSharpCompilation.Create(
            "Consumer.Ui",
            [CSharpSyntaxTree.ParseText(string.Empty, parseOptions, "Consumer.cs")],
            references.Append(producerReference),
            new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable)
                .WithMetadataImportOptions(MetadataImportOptions.Public));

        Assert.DoesNotContain(consumer.SyntaxTrees, static tree =>
            tree.FilePath.Contains("MainViewModel", StringComparison.Ordinal));
        var referencedProducer = Assert.IsAssignableFrom<IAssemblySymbol>(
            consumer.GetAssemblyOrModuleSymbol(producerReference));
        var referencedType = Assert.IsAssignableFrom<INamedTypeSymbol>(
            referencedProducer.GetTypeByMetadataName("Producer.MainViewModel"));
        Assert.Single(referencedType.GetMembers("IncrementCommand").OfType<IPropertySymbol>());
        Assert.Single(referencedType.GetMembers("GeneratedStatus").OfType<IPropertySymbol>());

        var projectDirectory = Path.Combine(Path.GetTempPath(), nameof(CommunityToolkitMetadataBoundaryTests));
        GeneratorDriver consumerDriver = CSharpGeneratorDriver.Create(
            [new AkburaBlackSilenceGenerator().AsSourceGenerator()],
            [new TestAdditionalText(
                Path.Combine(projectDirectory, "MainView.akbura"),
                SourceText.From(ConsumerMarkup))],
            parseOptions,
            new TestAnalyzerConfigOptionsProvider("Consumer", projectDirectory));
        consumerDriver = consumerDriver.RunGeneratorsAndUpdateCompilation(
            consumer,
            out var completedConsumer,
            out var consumerDiagnostics);

        AssertNoErrors(consumerDiagnostics);
        AssertNoErrors(completedConsumer.GetDiagnostics());
        var generated = string.Join(
            Environment.NewLine,
            consumerDriver.GetRunResult().Results.SelectMany(static result => result.GeneratedSources)
                .Select(static source => source.SourceText.ToString()));
        Assert.Contains("GeneratedStatus", generated, StringComparison.Ordinal);
        Assert.Contains("IncrementCommand", generated, StringComparison.Ordinal);
    }

    [Fact]
    public void MissingMemberStillProducesTypedBindingDiagnosticAcrossMetadataBoundary()
    {
        var parseOptions = CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview);
        var toolkitReference = MetadataReference.CreateFromFile(typeof(ObservableObject).Assembly.Location);
        var references = SymbolTests.CreateAvaloniaReferences()
            .Where(reference => !string.Equals(reference.Display, toolkitReference.Display, StringComparison.OrdinalIgnoreCase))
            .Append(toolkitReference)
            .ToArray();
        var producer = CSharpCompilation.Create(
            "Producer.ViewModels.Negative",
            [CSharpSyntaxTree.ParseText(ProducerSource, parseOptions)],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        GeneratorDriver toolkitDriver = CSharpGeneratorDriver.Create(
            LoadCommunityToolkitGenerators(),
            parseOptions: parseOptions);
        toolkitDriver.RunGeneratorsAndUpdateCompilation(
            producer,
            out var completedProducer,
            out _);
        using var producerImage = new MemoryStream();
        Assert.True(completedProducer.Emit(producerImage).Success);
        var producerReference = MetadataReference.CreateFromImage(producerImage.ToArray());
        var consumer = CSharpCompilation.Create(
            "Consumer.Ui.Negative",
            [CSharpSyntaxTree.ParseText(string.Empty, parseOptions)],
            references.Append(producerReference),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        var invalidMarkup = ConsumerMarkup.Replace(
            "IncrementCommand",
            "MissingCommand",
            StringComparison.Ordinal);
        var componentTree = ComponentSyntaxTree.ParseText(
            invalidMarkup,
            "InvalidMainView.akbura");
        var akburaCompilation = new AkburaCompilation(consumer, [componentTree]);
        var semanticModel = akburaCompilation.GetSemanticModel(componentTree);
        var root = Assert.IsType<MarkupRootSyntax>(
            Assert.Single(componentTree.GetRoot().Members,
                static member => member is MarkupRootSyntax));

        Assert.Contains(semanticModel.GetSemanticDiagnostics(root.Element), static diagnostic =>
            diagnostic.Code == ErrorCodes.AKBURA_SEMANTIC_MarkupExpressionError);
    }

    private static ISourceGenerator[] LoadCommunityToolkitGenerators()
    {
        var packagePath = typeof(CommunityToolkitMetadataBoundaryTests).Assembly
            .GetCustomAttributes<AssemblyMetadataAttribute>()
            .Single(static attribute => attribute.Key == "CommunityToolkitMvvmPackagePath")
            .Value!;
        var generatorPath = Directory.GetFiles(
            packagePath,
            "CommunityToolkit.Mvvm.SourceGenerators.dll",
            SearchOption.AllDirectories).Single(static path =>
                path.Contains("roslyn4.3", StringComparison.OrdinalIgnoreCase));
        var reference = new AnalyzerFileReference(generatorPath, new TestAnalyzerAssemblyLoader());
        return reference.GetGenerators(LanguageNames.CSharp).ToArray();
    }

    private static void AssertNoErrors(IEnumerable<Diagnostic> diagnostics)
    {
        Assert.DoesNotContain(diagnostics, static diagnostic =>
            diagnostic.Severity == DiagnosticSeverity.Error);
    }

    private sealed class TestAnalyzerAssemblyLoader : IAnalyzerAssemblyLoader
    {
        public void AddDependencyLocation(string fullPath)
        {
        }

        public Assembly LoadFromPath(string fullPath)
        {
            return Assembly.LoadFrom(fullPath);
        }
    }

    private sealed class TestAdditionalText(string path, SourceText sourceText) : AdditionalText
    {
        public override string Path { get; } = path;

        public override SourceText GetText(CancellationToken cancellationToken = default)
        {
            return sourceText;
        }
    }

    private sealed class TestAnalyzerConfigOptionsProvider(string rootNamespace, string projectDirectory) : AnalyzerConfigOptionsProvider
    {
        private static readonly AnalyzerConfigOptions s_empty =
            new TestAnalyzerConfigOptions(new Dictionary<string, string>());

        private readonly AnalyzerConfigOptions _global =
            new TestAnalyzerConfigOptions(
                new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["build_property.RootNamespace"] = rootNamespace,
                    ["build_property.ProjectDir"] = projectDirectory,
                });

        public override AnalyzerConfigOptions GlobalOptions => _global;

        public override AnalyzerConfigOptions GetOptions(SyntaxTree tree)
        {
            return s_empty;
        }

        public override AnalyzerConfigOptions GetOptions(AdditionalText textFile)
        {
            return s_empty;
        }
    }

    private sealed class TestAnalyzerConfigOptions(IReadOnlyDictionary<string, string> values) : AnalyzerConfigOptions
    {
        public override bool TryGetValue(string key, out string value)
        {
            if (values.TryGetValue(key, out var result))
            {
                value = result;
                return true;
            }

            value = null!;
            return false;
        }
    }
}
