using Akbura.Language.CodeGeneration;
using Akbura.Language.Symbols;
using Akbura.Language.Syntax;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace Akbura.UnitTests;

public sealed class ComponentDocumentWriterTests
{
    [Fact]
    public void Generate_WritesCompleteCompilableDocument()
    {
        const string componentSource =
            """
            using Avalonia.Controls;

            param string Title = "Hello";

            <Border Width="42" />
            """;

        const string csharpSource =
            """
            using Akbura;
            using Akbura.Engine;

            namespace Demo;

            public partial class PlannerView : AkburaControl
            {
                public PlannerView()
                    : base(AkburaEngine.Empty)
                {
                }
            }
            """;

        var fixture = AkcssActivatorPlannerTests.CreateFixture(
            componentSource,
            csharpSource);

        var component = Assert.IsType<IAkburaComponentSymbol>(
            fixture.SemanticModel.GetSymbolInfo(
                fixture.ComponentTree.GetRoot()).Symbol, exactMatch: false);

        var generatedText = ComponentDocumentWriter.Generate(
            component,
            fixture.SemanticModel,
            "Views/PlannerView.akbura",
            new Dictionary<AkburaSyntax, string>(),
            CancellationToken.None);

        var generatedSource = generatedText.ToString();

        Assert.Contains(
            "// <auto-generated />",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "#nullable enable",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "using Avalonia.Controls;",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "namespace Demo",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "public partial class PlannerView : global::Akbura.AkburaControl",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "TitleProperty",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "private global::Avalonia.Controls.Border __element0 = null!;",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "protected override global::Avalonia.Controls.Control FirstUpdate()",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "protected override global::Avalonia.Controls.Control Update()",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "GetParameters()",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "GetCommands()",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "GetServices()",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "GetStates()",
            generatedSource,
            StringComparison.Ordinal);

        var syntaxTree = CSharpSyntaxTree.ParseText(
            generatedText,
            CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview),
            path: ComponentDocumentWriter.GetHintName(
                component,
                "Views/PlannerView.akbura"));

        var diagnostics = fixture.CSharpCompilation
            .AddSyntaxTrees(syntaxTree)
            .GetDiagnostics()
            .Where(static diagnostic =>
                diagnostic.Severity is
                    DiagnosticSeverity.Warning or
                    DiagnosticSeverity.Error)
            .ToArray();

        Assert.True(
            diagnostics.Length == 0,
            string.Join(
                Environment.NewLine,
                diagnostics.Select(static diagnostic => diagnostic.ToString())) +
            Environment.NewLine +
            generatedSource);
    }

    [Fact]
    public void GetHintName_IsStableAndDistinguishesSourcePaths()
    {
        const string componentSource =
            """
            using Avalonia.Controls;

            <Border />
            """;

        var fixture = AkcssActivatorPlannerTests.CreateFixture(componentSource);

        var component = Assert.IsType<IAkburaComponentSymbol>(
            fixture.SemanticModel.GetSymbolInfo(
                fixture.ComponentTree.GetRoot()).Symbol, exactMatch: false);

        var first = ComponentDocumentWriter.GetHintName(
            component,
            "Views/PlannerView.akbura");

        var second = ComponentDocumentWriter.GetHintName(
            component,
            "Views/PlannerView.akbura");

        var other = ComponentDocumentWriter.GetHintName(
            component,
            "Controls/PlannerView.akbura");

        Assert.Equal(first, second);
        Assert.NotEqual(first, other);
        Assert.EndsWith(".g.cs", first, StringComparison.Ordinal);
        Assert.DoesNotContain("/", first, StringComparison.Ordinal);
        Assert.DoesNotContain("\\", first, StringComparison.Ordinal);
    }
}
