using Akbura.Language.CodeGeneration;
using Akbura.Language.Symbols;
using Akbura.Language.Syntax;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace Akbura.UnitTests;

public sealed class ComponentDocumentWriterTests
{
    [Fact]
    public void Generate_WritesCompleteCompilableDocument()
    {
        const string componentSource =
            """
            using Avalonia.Controls;

            param string Title = "Hello";

            <Border Width="42" />
            """;

        const string csharpSource =
            """
            using Akbura;
            using Akbura.Engine;

            namespace Demo;

            public partial class PlannerView : AkburaControl
            {
                public PlannerView()
                    : base(AkburaEngine.Empty)
                {
                }
            }
            """;

        var fixture = AkcssActivatorPlannerTests.CreateFixture(
            componentSource,
            csharpSource);

        var component = Assert.IsType<IAkburaComponentSymbol>(
            fixture.SemanticModel.GetSymbolInfo(
                fixture.ComponentTree.GetRoot()).Symbol, exactMatch: false);

        var generatedText = ComponentDocumentWriter.Generate(
            component,
            fixture.SemanticModel,
            "Views/PlannerView.akbura",
            new Dictionary<AkburaSyntax, string>(),
            CancellationToken.None);

        var generatedSource = generatedText.ToString();

        Assert.Contains(
            "// <auto-generated />",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "#nullable enable",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "using Avalonia.Controls;",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "namespace Demo",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "public partial class PlannerView : global::Akbura.AkburaControl",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "TitleProperty",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "private global::Avalonia.Controls.Border __element0 = null!;",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "protected override global::Avalonia.Controls.Control FirstUpdate()",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "protected override global::Avalonia.Controls.Control Update()",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "GetParameters()",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "GetCommands()",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "GetServices()",
            generatedSource,
            StringComparison.Ordinal);

        Assert.Contains(
            "GetStates()",
            generatedSource,
            StringComparison.Ordinal);

        var syntaxTree = CSharpSyntaxTree.ParseText(
            generatedText,
            CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview),
            path: ComponentDocumentWriter.GetHintName(
                component,
                "Views/PlannerView.akbura"));

        var diagnostics = fixture.CSharpCompilation
            .AddSyntaxTrees(syntaxTree)
            .GetDiagnostics()
            .Where(static diagnostic =>
                diagnostic.Severity is
                    DiagnosticSeverity.Warning or
                    DiagnosticSeverity.Error)
            .ToArray();

        Assert.True(
            diagnostics.Length == 0,
            string.Join(
                Environment.NewLine,
                diagnostics.Select(static diagnostic => diagnostic.ToString())) +
            Environment.NewLine +
            generatedSource);
    }

    [Fact]
    public void Generate_DebugWritesCompleteStructuralHotReloadContract()
    {
        const string componentSource =
            """
            using Avalonia.Controls;
            using System.Collections.Generic;

            param string Title = "Hello";
            param IList<Control> Content;
            inject IClock clock;
            command void Save(string value);
            state int count = 1;

            <Border>
                <TextBlock Text="Before" />
            </Border>
            """;
        const string csharpSource =
            """
            namespace Demo;

            public interface IClock
            {
            }
            """;
        var fixture = AkcssActivatorPlannerTests.CreateFixture(
            componentSource,
            csharpSource);
        var component = Assert.IsAssignableFrom<IAkburaComponentSymbol>(
            fixture.SemanticModel.GetSymbolInfo(
                fixture.ComponentTree.GetRoot()).Symbol);
        var generatedText = ComponentDocumentWriter.Generate(
            component,
            fixture.SemanticModel,
            "Views/PlannerView.akbura",
            new Dictionary<AkburaSyntax, string>(),
            CancellationToken.None);
        var generatedSource = generatedText.ToString();

        Assert.Contains(
            "private static string s_akburaAppliedDescriptorShape =",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "private static string s_akburaAppliedStateShape =",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "s_akburaHotReloadProperties",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "\"param:Title:System.String:styled:normal\"",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "\"service:clock:Demo.IClock:direct\"",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "\"command:Save:System.String:System.Void\"",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "global::Akbura.ComponentTree.Parameter.RecreateForHotReload",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "global::Akbura.ComponentTree.Parameter." +
            "RecreateReadOnlyForHotReload",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "global::Akbura.ComponentTree.InjectService.RecreateForHotReload",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "global::Akbura.HotReload.AkburaHotReloadRuntime.FindProperty<",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "global::Akbura.HotReload.AkburaHotReloadRuntime." +
            "BeginPropertyUpdate(",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "__component.__states = default;",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "private void __AkburaHotReloadUpdateInitialValues()",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "private static void __AkburaHotReloadPrepare(",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "__component.__AkburaHotReloadUpdateInitialValues();",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "global::Akbura.HotReload.AkburaHotReloadRuntime.Refresh<",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "__AkburaHotReloadPrepare);",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "internal static void __AkburaHotReloadApply()",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "public static global::Akbura.ComponentTree.Parameter<",
            generatedSource,
            StringComparison.Ordinal);
        Assert.Contains(
            "public static readonly global::Akbura.ComponentTree.Parameter<",
            generatedSource,
            StringComparison.Ordinal);
        Assert.DoesNotContain(
            "__state0",
            generatedSource,
            StringComparison.Ordinal);
        Assert.DoesNotContain(
            "__service0",
            generatedSource,
            StringComparison.Ordinal);

        var syntaxTree = CSharpSyntaxTree.ParseText(
            generatedText,
            CSharpParseOptions.Default
                .WithLanguageVersion(LanguageVersion.Preview)
                .WithPreprocessorSymbols("DEBUG"),
            path: ComponentDocumentWriter.GetHintName(
                component,
                "Views/PlannerView.akbura"));
        GeneratedCodeAssertions.AssertDoubleUnderscoreMethodsAreHidden(
            generatedSource);
        var diagnostics = fixture.CSharpCompilation
            .AddSyntaxTrees(syntaxTree)
            .GetDiagnostics()
            .Where(static diagnostic =>
                diagnostic.Severity is
                    DiagnosticSeverity.Warning or
                    DiagnosticSeverity.Error)
            .ToArray();

        Assert.True(
            diagnostics.Length == 0,
            string.Join(
                Environment.NewLine,
                diagnostics.Select(static diagnostic => diagnostic.ToString())) +
            Environment.NewLine +
            generatedSource);
    }

    [Fact]
    public void GetHintName_IsStableAndDistinguishesSourcePaths()
    {
        const string componentSource =
            """
            using Avalonia.Controls;

            <Border />
            """;

        var fixture = AkcssActivatorPlannerTests.CreateFixture(componentSource);

        var component = Assert.IsType<IAkburaComponentSymbol>(
            fixture.SemanticModel.GetSymbolInfo(
                fixture.ComponentTree.GetRoot()).Symbol, exactMatch: false);

        var first = ComponentDocumentWriter.GetHintName(
            component,
            "Views/PlannerView.akbura");

        var second = ComponentDocumentWriter.GetHintName(
            component,
            "Views/PlannerView.akbura");

        var other = ComponentDocumentWriter.GetHintName(
            component,
            "Controls/PlannerView.akbura");

        Assert.Equal(first, second);
        Assert.NotEqual(first, other);
        Assert.EndsWith(".g.cs", first, StringComparison.Ordinal);
        Assert.DoesNotContain("/", first, StringComparison.Ordinal);
        Assert.DoesNotContain("\\", first, StringComparison.Ordinal);
    }
}
