using Akbura.BlackSilence;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Reflection;

namespace Akbura.UnitTests;

public sealed class HotReloadServiceWriterTests
{
    [Fact]
    public void Generate_WritesMetadataHandlerDispatchAndSortedUniqueDirectCalls()
    {
        const string assemblyName = "HotReloadServiceWriterTests";
        var handlerTypeName =
            HotReloadServiceWriter.GetHandlerTypeName(assemblyName);
        var source = HotReloadServiceWriter.Generate(
            assemblyName,
            [
                "Demo.Zeta",
                "Demo.Alpha",
                "Demo.Zeta",
                string.Empty,
            ]);

        Assert.Equal(HotReloadServiceWriter.HintName, source.HintName);

        var output = source.SourceText.ToString();

        Assert.StartsWith(
            "// <auto-generated />\r\n" +
            "#if DEBUG\r\n" +
            "#nullable enable\r\n",
            output,
            StringComparison.Ordinal);
        Assert.Contains(
            "[assembly: global::System.Reflection.Metadata.MetadataUpdateHandlerAttribute(\r\n" +
            "    typeof(global::Akbura.Generated." +
            handlerTypeName +
            "))]",
            output,
            StringComparison.Ordinal);
        Assert.Contains(
            "internal static void ClearCache(global::System.Type[]? updatedTypes)\r\n" +
            "        {\r\n" +
            "        }",
            output,
            StringComparison.Ordinal);
        Assert.Contains(
            "internal static void UpdateApplication(global::System.Type[]? updatedTypes)",
            output,
            StringComparison.Ordinal);
        Assert.Contains(
            "if (global::Avalonia.Threading.Dispatcher.UIThread.CheckAccess())",
            output,
            StringComparison.Ordinal);
        Assert.Contains(
            "global::Avalonia.Threading.Dispatcher.UIThread.Post(\r\n" +
            "                () => UpdateApplicationCore(updatedTypes));",
            output,
            StringComparison.Ordinal);
        Assert.Contains(
            "ContainsType(updatedTypes, typeof(" +
            handlerTypeName +
            "))",
            output,
            StringComparison.Ordinal);
        Assert.Contains(
            "type = type.DeclaringType",
            output,
            StringComparison.Ordinal);
        Assert.Contains(
            "type.IsAssignableFrom(componentType)",
            output,
            StringComparison.Ordinal);
        Assert.Equal(
            1,
            CountOccurrences(
                output,
                "global::Demo.Alpha.__AkburaHotReloadApply();"));
        Assert.Equal(
            1,
            CountOccurrences(
                output,
                "global::Demo.Zeta.__AkburaHotReloadApply();"));
        Assert.Contains(
            "private static void ReloadAll()",
            output,
            StringComparison.Ordinal);
        Assert.Contains(
            "global::System.Collections.Generic.List<global::System.Exception>? " +
            "__exceptions = null;",
            output,
            StringComparison.Ordinal);
        Assert.Contains(
            "ThrowRefreshFailures(__exceptions);",
            output,
            StringComparison.Ordinal);
        Assert.True(
            output.IndexOf(
                "typeof(global::Demo.Alpha)",
                StringComparison.Ordinal) <
            output.IndexOf(
                "typeof(global::Demo.Zeta)",
                StringComparison.Ordinal),
            output);
        Assert.DoesNotContain(
            "static readonly global::System.Type[]",
            output,
            StringComparison.Ordinal);
        Assert.DoesNotContain("s_components", output, StringComparison.Ordinal);
        Assert.Contains(
            "OrderBaseTypesFirst(componentTypes, componentCount);",
            output,
            StringComparison.Ordinal);
        Assert.DoesNotContain(
            "\n",
            output.Replace("\r\n", string.Empty, StringComparison.Ordinal),
            StringComparison.Ordinal);
        Assert.EndsWith("#endif\r\n", output, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_AkcssNestedTypeUpdateReloadsOnlyDependentComponent()
    {
        const string hostSource =
            """
            namespace Demo
            {
                internal static class Dependent
                {
                    internal static int CallCount;

                    internal static void __AkburaHotReloadApply()
                    {
                        CallCount++;
                    }
                }

                internal static class Unrelated
                {
                    internal static int CallCount;

                    internal static void __AkburaHotReloadApply()
                    {
                        CallCount++;
                    }
                }

                internal static class ThemeModule
                {
                    internal sealed class Style
                    {
                    }
                }
            }
            """;
        var assemblyName =
            "AkburaAkcssDispatch_" +
            Guid.NewGuid().ToString("N");
        var generated = HotReloadServiceWriter.Generate(
            assemblyName,
            ["Demo.Dependent", "Demo.Unrelated"],
            new Dictionary<string, ImmutableArray<string>>(
                StringComparer.Ordinal)
            {
                ["Demo.Dependent"] =
                    ["global::Demo.ThemeModule"],
            });
        var output = generated.SourceText.ToString();

        Assert.Contains(
            "Affects(updatedTypes, typeof(global::Demo.ThemeModule))",
            output,
            StringComparison.Ordinal);
        Assert.DoesNotContain(
            "static readonly global::System.Type",
            output,
            StringComparison.Ordinal);

        var assembly = CompileAndLoad(
            assemblyName,
            hostSource,
            generated);
        var handler = GetRequiredType(
            assembly,
            "Akbura.Generated." +
            HotReloadServiceWriter.GetHandlerTypeName(
                assemblyName));
        var style = GetRequiredType(
            assembly,
            "Demo.ThemeModule+Style");
        var dependent = GetRequiredType(
            assembly,
            "Demo.Dependent");
        var unrelated = GetRequiredType(
            assembly,
            "Demo.Unrelated");
        var updateApplicationCore = GetRequiredStaticMethod(
            handler,
            "UpdateApplicationCore");

        updateApplicationCore.Invoke(
            null,
            [new[] { style }]);

        Assert.Equal(1, GetStaticCallCount(dependent));
        Assert.Equal(0, GetStaticCallCount(unrelated));
    }

    [Fact]
    public void Generate_ReloadsBaseBeforeLexicallyEarlierDerivedComponent()
    {
        const string hostSource =
            """
            namespace Demo
            {
                internal static class CallLog
                {
                    internal static readonly System.Collections.Generic.List<string> Entries = [];
                }

                internal class ZBase
                {
                    internal static void __AkburaHotReloadApply()
                    {
                        CallLog.Entries.Add("base");
                    }
                }

                internal sealed class ADerived : ZBase
                {
                    internal new static void __AkburaHotReloadApply()
                    {
                        CallLog.Entries.Add("derived");
                    }
                }
            }
            """;
        var assemblyName =
            "AkburaBaseOrder_" +
            Guid.NewGuid().ToString("N");
        var generated = HotReloadServiceWriter.Generate(
            assemblyName,
            ["Demo.ADerived", "Demo.ZBase"]);
        var assembly = CompileAndLoad(
            assemblyName,
            hostSource,
            generated);
        var handler = GetRequiredType(
            assembly,
            "Akbura.Generated." +
            HotReloadServiceWriter.GetHandlerTypeName(
                assemblyName));
        var callLog = GetRequiredType(
            assembly,
            "Demo.CallLog");
        var reloadAll = GetRequiredStaticMethod(
            handler,
            "ReloadAll");

        reloadAll.Invoke(null, parameters: null);

        var entries = Assert.IsType<List<string>>(
            GetRequiredStaticField(
                callLog,
                "Entries").GetValue(null));
        Assert.Equal(
            ["base", "derived"],
            entries);
    }

    [Fact]
    public void Generate_DebugOutputCompilesAndRegistersInternalMetadataHandler()
    {
        const string assemblyName = "HotReloadServiceWriterTests";
        var generated = HotReloadServiceWriter.Generate(
            assemblyName,
            ImmutableArray.Create(
                "Demo.Zeta",
                "Demo.Alpha",
                "Demo.Alpha"));
        var parseOptions = CSharpParseOptions.Default
            .WithLanguageVersion(LanguageVersion.Preview)
            .WithPreprocessorSymbols("DEBUG");
        var stubs = CSharpSyntaxTree.ParseText(
            """
            namespace Demo
            {
                internal static class Alpha
                {
                    internal static void __AkburaHotReloadApply()
                    {
                    }
                }

                internal static class Zeta
                {
                    internal static void __AkburaHotReloadApply()
                    {
                    }
                }
            }
            """,
            parseOptions);
        var generatedTree = CSharpSyntaxTree.ParseText(
            generated.SourceText,
            parseOptions,
            path: generated.HintName);
        var compilation = CSharpCompilation.Create(
            assemblyName,
            syntaxTrees: [stubs, generatedTree],
            references: CreateHotReloadReferences(),
            options: new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable));
        var diagnostics = compilation.GetDiagnostics()
            .Where(static diagnostic =>
                diagnostic.Severity is DiagnosticSeverity.Warning or
                    DiagnosticSeverity.Error)
            .ToArray();

        Assert.True(
            diagnostics.Length == 0,
            string.Join(
                Environment.NewLine,
                diagnostics.Select(static diagnostic => diagnostic.ToString())) +
            Environment.NewLine +
            generated.SourceText);

        var handlerType = Assert.IsAssignableFrom<INamedTypeSymbol>(
            compilation.GetTypeByMetadataName(
                "Akbura.Generated." +
                HotReloadServiceWriter.GetHandlerTypeName(assemblyName)));
        Assert.Equal(Accessibility.Internal, handlerType.DeclaredAccessibility);

        var clearCache = Assert.Single(
            handlerType.GetMembers("ClearCache").OfType<IMethodSymbol>());
        Assert.True(clearCache.IsStatic);
        Assert.Equal(Accessibility.Internal, clearCache.DeclaredAccessibility);
        Assert.True(clearCache.ReturnsVoid);
        Assert.Single(clearCache.Parameters);

        var updateApplication = Assert.Single(
            handlerType.GetMembers("UpdateApplication").OfType<IMethodSymbol>());
        Assert.True(updateApplication.IsStatic);
        Assert.Equal(
            Accessibility.Internal,
            updateApplication.DeclaredAccessibility);
        Assert.True(updateApplication.ReturnsVoid);
        Assert.Single(updateApplication.Parameters);

        var metadataHandler = Assert.Single(
            compilation.Assembly.GetAttributes(),
            static attribute =>
                attribute.AttributeClass?.ToDisplayString() ==
                "System.Reflection.Metadata.MetadataUpdateHandlerAttribute");
        var registeredType = Assert.IsAssignableFrom<INamedTypeSymbol>(
            Assert.Single(metadataHandler.ConstructorArguments).Value);

        Assert.True(
            SymbolEqualityComparer.Default.Equals(
                handlerType,
                registeredType));
    }

    [Fact]
    public void Generate_WithoutComponentsWritesEmptyReloadBodyAndCompiles()
    {
        const string assemblyName = "EmptyHotReloadServiceWriterTests";
        var generated = HotReloadServiceWriter.Generate(
            assemblyName,
            []);
        var output = generated.SourceText.ToString();

        Assert.Contains(
            "private static void ReloadAll()",
            output,
            StringComparison.Ordinal);
        Assert.Contains(
            "ThrowRefreshFailures(__exceptions);",
            output,
            StringComparison.Ordinal);
        Assert.DoesNotContain(
            ".__AkburaHotReloadApply();",
            output,
            StringComparison.Ordinal);

        var parseOptions = CSharpParseOptions.Default
            .WithLanguageVersion(LanguageVersion.Preview)
            .WithPreprocessorSymbols("DEBUG");
        var compilation = CSharpCompilation.Create(
            assemblyName,
            syntaxTrees:
            [
                CSharpSyntaxTree.ParseText(
                    generated.SourceText,
                    parseOptions,
                    path: generated.HintName),
            ],
            references: CreateHotReloadReferences(),
            options: new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable));
        var diagnostics = compilation.GetDiagnostics()
            .Where(static diagnostic =>
                diagnostic.Severity is DiagnosticSeverity.Warning or
                    DiagnosticSeverity.Error)
            .ToArray();

        Assert.True(
            diagnostics.Length == 0,
            string.Join(
                Environment.NewLine,
                diagnostics.Select(static diagnostic => diagnostic.ToString())) +
            Environment.NewLine +
            generated.SourceText);
    }

    private static MetadataReference[] CreateHotReloadReferences()
    {
        return SymbolTests.CreateAvaloniaReferences()
            .Where(static reference =>
                reference.Display is not { } path ||
                !Path.GetFileName(path).StartsWith(
                    "Akbura",
                    StringComparison.OrdinalIgnoreCase))
            .ToArray();
    }

    private static Assembly CompileAndLoad(
        string assemblyName,
        string hostSource,
        GeneratedSource generated)
    {
        var parseOptions = CSharpParseOptions.Default
            .WithLanguageVersion(LanguageVersion.Preview)
            .WithPreprocessorSymbols("DEBUG");
        var compilation = CSharpCompilation.Create(
            assemblyName,
            syntaxTrees:
            [
                CSharpSyntaxTree.ParseText(
                    hostSource,
                    parseOptions),
                CSharpSyntaxTree.ParseText(
                    generated.SourceText,
                    parseOptions),
            ],
            references: CreateHotReloadReferences(),
            options: new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions:
                    NullableContextOptions.Enable));
        using var peStream = new MemoryStream();
        var emit = compilation.Emit(peStream);

        Assert.True(
            emit.Success,
            string.Join(
                Environment.NewLine,
                emit.Diagnostics.Select(
                    static diagnostic =>
                        diagnostic.ToString())) +
            Environment.NewLine +
            generated.SourceText);

        return Assembly.Load(peStream.ToArray());
    }

    private static Type GetRequiredType(
        Assembly assembly,
        string metadataName)
    {
        return Assert.IsAssignableFrom<Type>(
            assembly.GetType(metadataName));
    }

    private static MethodInfo GetRequiredStaticMethod(
        Type type,
        string name)
    {
        const BindingFlags flags =
            BindingFlags.Static |
            BindingFlags.Public |
            BindingFlags.NonPublic;

        return Assert.IsAssignableFrom<MethodInfo>(
            type.GetMethod(name, flags));
    }

    private static FieldInfo GetRequiredStaticField(
        Type type,
        string name)
    {
        const BindingFlags flags =
            BindingFlags.Static |
            BindingFlags.Public |
            BindingFlags.NonPublic;

        return Assert.IsAssignableFrom<FieldInfo>(
            type.GetField(name, flags));
    }

    private static int GetStaticCallCount(Type type)
    {
        return Assert.IsType<int>(
            GetRequiredStaticField(
                type,
                "CallCount").GetValue(null));
    }

    private static int CountOccurrences(string text, string value)
    {
        var count = 0;
        var start = 0;

        while ((start = text.IndexOf(value, start, StringComparison.Ordinal)) >= 0)
        {
            count++;
            start += value.Length;
        }

        return count;
    }
}
