using Akbura.Language;
using Akbura.Language.Operations;
using Akbura.Language.Symbols;
using Akbura.Language.Syntax;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using AkburaPropertySymbol = Akbura.Language.Symbols.IPropertySymbol;
using AkburaSyntaxList = Akbura.Language.Syntax.SyntaxList<Akbura.Language.Syntax.AkcssTopLevelMemberSyntax>;
using CSharpSyntaxFacts = Microsoft.CodeAnalysis.CSharp.SyntaxFacts;
using CSharpSyntaxKind = Microsoft.CodeAnalysis.CSharp.SyntaxKind;
using CSharpExpressionSyntax = Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax;
using CSharpGenericNameSyntax = Microsoft.CodeAnalysis.CSharp.Syntax.GenericNameSyntax;
using CSharpIdentifierNameSyntax = Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax;
using CSharpInvocationExpressionSyntax = Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax;
using CSharpMemberAccessExpressionSyntax = Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax;
using CSharpSyntaxFactory = Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
using CSharpSyntaxRewriter = Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter;
using RoslynFieldSymbol = Microsoft.CodeAnalysis.IFieldSymbol;
using RoslynMethodSymbol = Microsoft.CodeAnalysis.IMethodSymbol;
using RoslynPropertySymbol = Microsoft.CodeAnalysis.IPropertySymbol;

namespace Akbura.Furioso;

internal static class AkcssGenerator
{
    private const string RuntimeStyleType = "global::Akbura.Akcss.AkcssStyle";
    private const string RuntimeClassType = "global::Akbura.Akcss.AkcssClass";
    private const string RuntimeUtilityType = "global::Akbura.Akcss.AkcssUtility";
    private const string RuntimeZeroUtilityType = "global::Akbura.Akcss.ZeroAkcssUtility";
    private const string StyleNameAttribute = "global::Akbura.CompilerAnotations.StyleNameAttribute";
    private const string InlinedStyleAttribute = "global::Akbura.CompilerAnotations.InlinedStyleAttribute";
    private const string AkcssModuleAttribute = "global::Akbura.CompilerAnotations.AkcssModuleAttribute";
    private const string EditorBrowsableAttribute = "global::System.ComponentModel.EditorBrowsableAttribute";
    private const string BrowsableAttribute = "global::System.ComponentModel.BrowsableAttribute";

    public static string GetHintName(IAkcssModuleSymbol symbol, string sourcePath)
    {
        if (symbol == null)
        {
            throw new ArgumentNullException(nameof(symbol));
        }

        var identity = GetModuleIdentity(symbol, sourcePath);
        return $"Akbura.Akcss.{SanitizeHintPart(identity)}.{AkcssGeneratedModuleNames.GetStableHash(identity):x8}.g.cs";
    }

    public static string Generate(
        IAkcssModuleSymbol symbol,
        AkcssGenerationSourceMap sourceMap,
        string sourcePath)
    {
        if (symbol == null)
        {
            throw new ArgumentNullException(nameof(symbol));
        }

        if (sourceMap == null)
        {
            throw new ArgumentNullException(nameof(sourceMap));
        }

        var identity = GetModuleIdentity(symbol, sourcePath);
        var moduleTypeName = AkcssGeneratedModuleNames.GetTypeName(identity);
        var source = new StringBuilder();

        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        AppendUsingDirectives(source, symbol.DeclaringSyntax);
        source.AppendLine();
        source.Append("namespace ").Append(AkcssGeneratedModuleNames.NamespaceName).AppendLine();
        source.AppendLine("{");
        AppendHiddenApiAttributes(source, 1);
        AppendIndentedLine(source, 1, $"[{AkcssModuleAttribute}(SourcePath)]");
        source.Append("    public static class ").Append(moduleTypeName).AppendLine();
        source.AppendLine("    {");
        AppendHiddenApiAttributes(source, 2);
        source.Append("        public const string MetadataName = ")
            .Append(ToStringLiteral(symbol.MetadataName))
            .AppendLine(";");
        AppendHiddenApiAttributes(source, 2);
        source.Append("        public const string SourcePath = ")
            .Append(ToStringLiteral(identity))
            .AppendLine(";");

        AppendStyleCollection(source, symbol);

        for (var index = 0; index < symbol.AkcssSymbols.Length; index++)
        {
            var akcssSymbol = symbol.AkcssSymbols[index];
            if (!akcssSymbol.IsIntercepted)
            {
                source.AppendLine();
                AppendStyleType(source, symbol, akcssSymbol, index, sourceMap);
            }
        }

        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static void AppendUsingDirectives(StringBuilder source, AkburaSyntax syntax)
    {
        var names = new HashSet<string>(StringComparer.Ordinal);

        if (syntax is AkcssDocumentSyntax document)
        {
            AppendUsingDirectives(source, document.Members, names);
        }
        else if (syntax is InlineAkcssBlockSyntax inlineBlock)
        {
            AppendUsingDirectives(source, inlineBlock.Members, names);
        }
    }

    private static void AppendUsingDirectives(
        StringBuilder source,
        AkburaSyntaxList members,
        HashSet<string> names)
    {
        foreach (var member in members)
        {
            if (member is not AkcssUsingDirectiveSyntax usingDirective)
            {
                continue;
            }

            var name = usingDirective.Name.ToFullString().Trim();
            if (name.Length == 0 ||
                name.EndsWith(".akcss", StringComparison.OrdinalIgnoreCase) ||
                !names.Add(name))
            {
                continue;
            }

            source.Append("using ").Append(name).AppendLine(";");
        }
    }

    private static void AppendStyleCollection(
        StringBuilder source,
        IAkcssModuleSymbol module)
    {
        var expressions = new List<string>(module.AkcssSymbols.Length);
        for (var index = 0; index < module.AkcssSymbols.Length; index++)
        {
            var symbol = module.AkcssSymbols[index];
            if (!symbol.IsIntercepted)
            {
                expressions.Add($"new Style_{index}()");
                continue;
            }

            if (TryGetInterceptorCreation(symbol, out var interceptorCreation))
            {
                expressions.Add(interceptorCreation);
            }
        }

        source.AppendLine();
        AppendHiddenApiAttributes(source, 2);
        source.Append("        public static readonly global::System.Collections.Immutable.ImmutableArray<")
            .Append(RuntimeStyleType)
            .AppendLine("> Styles =");

        if (expressions.Count == 0)
        {
            source.Append("            global::System.Collections.Immutable.ImmutableArray<")
                .Append(RuntimeStyleType)
                .AppendLine(">.Empty;");
            return;
        }

        source.Append("            global::System.Collections.Immutable.ImmutableArray.Create<")
            .Append(RuntimeStyleType)
            .AppendLine(">");
        source.AppendLine("            (");
        for (var index = 0; index < expressions.Count; index++)
        {
            source.Append("                ").Append(expressions[index]);
            source.AppendLine(index == expressions.Count - 1 ? string.Empty : ",");
        }

        source.AppendLine("            );");
    }

    private static bool TryGetInterceptorCreation(
        IAkcssSymbol symbol,
        out string creation)
    {
        creation = string.Empty;
        if (symbol.InterceptType.Symbol is not INamedTypeSymbol type || type.IsAbstract)
        {
            return false;
        }

        foreach (var constructor in type.InstanceConstructors)
        {
            if (constructor.Parameters.Length == 0 &&
                constructor.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal)
            {
                creation = $"new {GetTypeName(type)}()";
                return true;
            }
        }

        return false;
    }

    private static void AppendStyleType(
        StringBuilder source,
        IAkcssModuleSymbol module,
        IAkcssSymbol symbol,
        int index,
        AkcssGenerationSourceMap sourceMap)
    {
        source.Append("        [").Append(StyleNameAttribute).Append('(')
            .Append(ToStringLiteral(symbol.Name)).AppendLine(")] ");
        if (module.IsInlined)
        {
            source.Append("        [").Append(InlinedStyleAttribute).AppendLine("]");
        }

        if (symbol is ITailwindUtilitySymbol utility)
        {
            AppendUtilityType(source, utility, index, sourceMap);
        }
        else
        {
            AppendClassType(source, symbol, index, sourceMap);
        }
    }

    private static void AppendClassType(
        StringBuilder source,
        IAkcssSymbol symbol,
        int index,
        AkcssGenerationSourceMap sourceMap)
    {
        source.Append("        private sealed class Style_").Append(index)
            .Append(" : ").AppendLine(RuntimeClassType);
        source.AppendLine("        {");
        source.AppendLine("            public override void Update(object __target)");
        source.AppendLine("            {");
        source.AppendLine("                global::System.ArgumentNullException.ThrowIfNull(__target);");
        AppendOperations(
            source,
            symbol.Operations,
            "__target",
            4,
            new HashSet<IAkcssSymbol>(),
            sourceMap);
        source.AppendLine("            }");
        AppendResetMethod(source, symbol);
        source.AppendLine("        }");
    }

    private static void AppendUtilityType(
        StringBuilder source,
        ITailwindUtilitySymbol symbol,
        int index,
        AkcssGenerationSourceMap sourceMap)
    {
        var targetName = GetTargetParameterName(symbol.Parameters);
        var baseType = GetUtilityBaseType(symbol.Parameters);
        source.Append("        private sealed class Style_").Append(index)
            .Append(" : ").AppendLine(baseType);
        source.AppendLine("        {");

        if (symbol.Parameters.Length <= 16)
        {
            source.Append("            public override void Update(object ").Append(targetName);
            for (var parameterIndex = 0; parameterIndex < symbol.Parameters.Length; parameterIndex++)
            {
                var parameter = symbol.Parameters[parameterIndex];
                source.Append(", ").Append(GetTypeName(parameter.Type.Symbol))
                    .Append(' ').Append(GetParameterName(parameter));
            }

            source.AppendLine(")");
            source.AppendLine("            {");
        }
        else
        {
            AppendUntypedUtilityMembers(source, symbol, targetName);
        }

        source.Append("                global::System.ArgumentNullException.ThrowIfNull(")
            .Append(targetName).AppendLine(");");
        AppendOperations(
            source,
            symbol.Operations,
            targetName,
            4,
            new HashSet<IAkcssSymbol>(),
            sourceMap);
        source.AppendLine("            }");
        AppendResetMethod(source, symbol);
        source.AppendLine("        }");
    }

    private static string GetUtilityBaseType(
        ImmutableArray<ITailwindUtilityParameterSymbol> parameters)
    {
        if (parameters.Length == 0)
        {
            return RuntimeZeroUtilityType;
        }

        if (parameters.Length > 16)
        {
            return RuntimeUtilityType;
        }

        var result = new StringBuilder(RuntimeUtilityType).Append('<');
        for (var index = 0; index < parameters.Length; index++)
        {
            if (index > 0)
            {
                result.Append(", ");
            }

            result.Append(GetTypeName(parameters[index].Type.Symbol));
        }

        return result.Append('>').ToString();
    }

    private static void AppendUntypedUtilityMembers(
        StringBuilder source,
        ITailwindUtilitySymbol symbol,
        string targetName)
    {
        source.AppendLine("            public override global::System.Collections.Immutable.ImmutableArray<global::System.Type> Parameters =>");
        source.AppendLine("                global::System.Collections.Immutable.ImmutableArray.Create<global::System.Type>");
        source.AppendLine("                (");
        for (var index = 0; index < symbol.Parameters.Length; index++)
        {
            source.Append("                    typeof(")
                .Append(GetTypeName(symbol.Parameters[index].Type.Symbol)).Append(')');
            source.AppendLine(index == symbol.Parameters.Length - 1 ? string.Empty : ",");
        }

        source.AppendLine("                );");
        source.AppendLine();
        source.Append("            public override void Update(object ").Append(targetName)
            .AppendLine(", params object[] __parameters)");
        source.AppendLine("            {");
        for (var index = 0; index < symbol.Parameters.Length; index++)
        {
            source.Append("                var ").Append(GetParameterName(symbol.Parameters[index]))
                .Append(" = (").Append(GetTypeName(symbol.Parameters[index].Type.Symbol))
                .Append(")__parameters[").Append(index).AppendLine("]; ");
        }

    }

    private static void AppendOperations(
        StringBuilder source,
        ImmutableArray<IAkcssOperation> operations,
        string targetName,
        int indentation,
        HashSet<IAkcssSymbol> expansionPath,
        AkcssGenerationSourceMap sourceMap)
    {
        foreach (var operation in operations)
        {
            if (operation.HasErrors)
            {
                AppendIndentedLine(source, indentation, "// The invalid AKCSS operation was not emitted.");
                continue;
            }

            switch (operation)
            {
                case IAkcssPropertySetterOperation setter:
                    AppendPropertySetter(source, setter, targetName, indentation, sourceMap);
                    break;
                case IAkcssIfOperation ifOperation:
                    var condition = ifOperation.Syntax.Condition.GetRawCSharpExpression()?.ToString() ?? "false";
                    AppendIndentedLine(source, indentation, $"if ({condition})");
                    AppendIndentedLine(source, indentation, "{");
                    AppendOperations(
                        source,
                        ifOperation.Operations,
                        targetName,
                        indentation + 1,
                        expansionPath,
                        sourceMap);
                    AppendIndentedLine(source, indentation, "}");
                    break;
                case IAkcssApplyOperation applyOperation:
                    AppendAppliedOperations(
                        source,
                        applyOperation,
                        targetName,
                        indentation,
                        expansionPath,
                        sourceMap);
                    break;
            }
        }
    }

    private static void AppendAppliedOperations(
        StringBuilder source,
        IAkcssApplyOperation operation,
        string targetName,
        int indentation,
        HashSet<IAkcssSymbol> expansionPath,
        AkcssGenerationSourceMap sourceMap)
    {
        foreach (var appliedSymbol in operation.AppliedSymbols)
        {
            if (appliedSymbol is ITailwindUtilitySymbol { Parameters.Length: > 0 })
            {
                AppendIndentedLine(
                    source,
                    indentation,
                    "// Parameterized @apply is preserved for a later code-generation pass.");
                continue;
            }

            if (!expansionPath.Add(appliedSymbol))
            {
                AppendIndentedLine(source, indentation, "// Cyclic @apply was ignored.");
                continue;
            }

            AppendOperations(
                source,
                appliedSymbol.Operations,
                targetName,
                indentation,
                expansionPath,
                sourceMap);
            expansionPath.Remove(appliedSymbol);
        }
    }

    private static void AppendPropertySetter(
        StringBuilder source,
        IAkcssPropertySetterOperation operation,
        string targetName,
        int indentation,
        AkcssGenerationSourceMap sourceMap)
    {
        if (operation.Property is not { } property || !property.CanWrite)
        {
            AppendIndentedLine(source, indentation, "// The unresolved AKCSS property was not emitted.");
            return;
        }

        var value = GetValueExpression(operation, targetName, observeDynamicResource: true);
        GeneratedStatement? statement = null;
        if (value.DynamicResource is { } dynamicResource)
        {
            statement = CreateDynamicResourceAssignment(
                property,
                targetName,
                value.Expression,
                dynamicResource);
        }

        if (statement == null)
        {
            value = GetValueExpression(operation, targetName, observeDynamicResource: false);
        }

        statement ??= property.WriteKind switch
        {
            PropertyAccessKind.ClrProperty => CreateClrPropertyAssignment(property, targetName, value.Expression),
            PropertyAccessKind.AvaloniaProperty => CreateAvaloniaPropertyAssignment(property, targetName, value.Expression),
            PropertyAccessKind.AttachedAccessor => CreateAttachedPropertyAssignment(property, targetName, value.Expression),
            _ => null,
        };

        if (statement == null)
        {
            AppendIndentedLine(
                source,
                indentation,
                "// This AKCSS property write kind is not emitted yet.");
            return;
        }

        AppendTargetCompatibleStatement(
            source,
            indentation,
            targetName,
            statement.Value,
            GetPropertyReceiverType(property),
            value.RequiresResourceHost,
            operation.Syntax.Expression,
            sourceMap);
    }

    private static void AppendTargetCompatibleStatement(
        StringBuilder source,
        int indentation,
        string targetName,
        GeneratedStatement statement,
        ITypeSymbol? receiverType,
        bool requiresResourceHost,
        AkburaSyntax syntax,
        AkcssGenerationSourceMap sourceMap)
    {
        var conditions = new List<string>(2);
        if (receiverType is { SpecialType: not SpecialType.System_Object })
        {
            conditions.Add($"{targetName} is {GetTypeName(receiverType)}");
        }

        if (requiresResourceHost)
        {
            conditions.Add($"{targetName} is global::Avalonia.Controls.IResourceHost");
        }

        var statementIndentation = indentation;
        if (conditions.Count > 0)
        {
            AppendIndentedLine(source, indentation, $"if ({string.Join(" && ", conditions)})");
            AppendIndentedLine(source, indentation, "{");
            statementIndentation++;
        }

        var hasLineDirective = sourceMap.TryGetLineDirective(
            syntax,
            out var lineSpan,
            out var path);
        if (hasLineDirective)
        {
            var start = lineSpan.Start;
            var end = lineSpan.End;
            var characterOffset = statementIndentation * 4 + statement.ValueOffset;
            AppendIndentedLine(
                source,
                statementIndentation,
                $"#line ({start.Line + 1},{start.Character + 1})-" +
                $"({end.Line + 1},{end.Character + 1}) {characterOffset} " +
                ToLineDirectivePath(path));
        }

        AppendIndentedLine(source, statementIndentation, statement.Text);
        if (hasLineDirective)
        {
            AppendIndentedLine(source, statementIndentation, "#line default");
        }

        if (conditions.Count > 0)
        {
            AppendIndentedLine(source, indentation, "}");
        }
    }

    private static GeneratedStatement? CreateDynamicResourceAssignment(
        AkburaPropertySymbol property,
        string targetName,
        string value,
        DynamicResourceBinding dynamicResource)
    {
        var propertyReference = GetStaticMemberReference(property.AvaloniaPropertyDefinition.Symbol) ??
                                GetStaticMemberReference(property.AttachedPropertyDefinition.Symbol);
        if (propertyReference == null && property.WriteKind == PropertyAccessKind.AvaloniaProperty)
        {
            propertyReference = GetStaticMemberReference(property.WriteDefinition.Symbol);
        }

        if (propertyReference == null)
        {
            return null;
        }

        var resourceValue = dynamicResource.ValueParameterName;
        var prefix =
            $"TrackSubscription({targetName}, " +
            $"((global::Avalonia.AvaloniaObject){targetName}).Bind(" +
            $"{propertyReference}, " +
            $"global::Avalonia.Controls.ResourceNodeExtensions.GetResourceObservable(" +
            $"(global::Avalonia.Controls.IResourceHost){targetName}, " +
            $"{dynamicResource.KeyExpression}, converter: " +
            $"{resourceValue} => global::System.Object.ReferenceEquals({resourceValue}, global::Avalonia.AvaloniaProperty.UnsetValue) " +
            $"? global::Avalonia.AvaloniaProperty.UnsetValue : (object?)(";
        return new GeneratedStatement(prefix + value + "))));", prefix.Length);
    }

    private static GeneratedStatement? CreateClrPropertyAssignment(
        AkburaPropertySymbol property,
        string targetName,
        string value)
    {
        if (property.WriteDefinition.Symbol is not RoslynPropertySymbol clrProperty)
        {
            return null;
        }

        var prefix =
            $"(({GetTypeName(clrProperty.ContainingType)}){targetName})." +
            $"{EscapeIdentifier(clrProperty.Name)} = ";
        return new GeneratedStatement(prefix + value + ";", prefix.Length);
    }

    private static GeneratedStatement? CreateAvaloniaPropertyAssignment(
        AkburaPropertySymbol property,
        string targetName,
        string value)
    {
        var propertyReference = GetStaticMemberReference(property.WriteDefinition.Symbol) ??
                                GetStaticMemberReference(property.AvaloniaPropertyDefinition.Symbol);
        if (propertyReference == null)
        {
            return null;
        }

        var prefix =
            $"((global::Avalonia.AvaloniaObject){targetName}).SetValue(" +
            $"{propertyReference}, ";
        return new GeneratedStatement(prefix + value + ");", prefix.Length);
    }

    private static GeneratedStatement? CreateAttachedPropertyAssignment(
        AkburaPropertySymbol property,
        string targetName,
        string value)
    {
        var setter = property.WriteDefinition.Symbol as RoslynMethodSymbol ??
                     property.AttachedSetterDefinition.Symbol as RoslynMethodSymbol;
        if (setter == null || setter.Parameters.Length == 0)
        {
            return null;
        }

        var prefix =
            $"{GetMethodReference(setter)}(({GetTypeName(setter.Parameters[0].Type)}){targetName}, ";
        return new GeneratedStatement(prefix + value + ");", prefix.Length);
    }

    private static GeneratedValue GetValueExpression(
        IAkcssPropertySetterOperation operation,
        string targetName,
        bool observeDynamicResource)
    {
        var rewriter = new AmxExpressionRewriter(targetName, observeDynamicResource);
        string value = operation.ConvertedValue switch
        {
            AkcssColorValue color =>
                $"global::Avalonia.Media.Color.FromArgb({color.A}, {color.R}, {color.G}, {color.B})",
            AkcssThicknessValue thickness => CreateThicknessExpression(thickness),
            AkcssThicknessExpressionValue thickness => CreateThicknessExpression(thickness, rewriter),
            CSharpSymbolDefinition definition when GetStaticMemberReference(definition.Symbol) is { } member => member,
            _ => RewriteExpression(operation.Syntax.Expression.GetRawCSharpExpression(), rewriter),
        };

        if (operation.RequiresBrushConversion)
        {
            value = $"new global::Avalonia.Media.SolidColorBrush({value})";
        }

        return new GeneratedValue(
            value,
            rewriter.DynamicResource,
            rewriter.RequiresResourceHost);
    }

    private static string RewriteExpression(
        CSharpExpressionSyntax? expression,
        AmxExpressionRewriter rewriter)
    {
        return expression == null
            ? "default"
            : rewriter.Visit(expression)?.ToString() ?? "default";
    }

    private static string CreateThicknessExpression(AkcssThicknessValue value)
    {
        return $"new global::Avalonia.Thickness({FormatDouble(value.Left)}, {FormatDouble(value.Top)}, {FormatDouble(value.Right)}, {FormatDouble(value.Bottom)})";
    }

    private static string CreateThicknessExpression(
        AkcssThicknessExpressionValue value,
        AmxExpressionRewriter rewriter)
    {
        return
            $"new global::Avalonia.Thickness(" +
            $"{RewriteExpression(value.Left, rewriter)}, " +
            $"{RewriteExpression(value.Top, rewriter)}, " +
            $"{RewriteExpression(value.Right, rewriter)}, " +
            $"{RewriteExpression(value.Bottom, rewriter)})";
    }

    private static void AppendResetMethod(
        StringBuilder source,
        IAkcssSymbol symbol)
    {
        var propertyReferences = new Dictionary<string, ITypeSymbol?>(StringComparer.Ordinal);
        CollectResetProperties(
            symbol.Operations,
            propertyReferences,
            new HashSet<IAkcssSymbol>());
        if (propertyReferences.Count == 0)
        {
            return;
        }

        source.AppendLine();
        source.AppendLine("            public override void Reset(object __target)");
        source.AppendLine("            {");
        source.AppendLine("                global::System.ArgumentNullException.ThrowIfNull(__target);");
        source.AppendLine("                base.Reset(__target);");
        foreach (var property in propertyReferences)
        {
            var propertyReference = property.Key;
            var receiverType = property.Value;
            source.Append("                if (__target is global::Avalonia.AvaloniaObject");
            if (receiverType is { SpecialType: not SpecialType.System_Object })
            {
                source.Append(" && __target is ").Append(GetTypeName(receiverType));
            }

            source.AppendLine(")");
            source.AppendLine("                {");
            source.Append("                    ((global::Avalonia.AvaloniaObject)__target).ClearValue(")
                .Append(propertyReference).AppendLine(");");
            source.AppendLine("                }");
        }

        source.AppendLine("            }");
    }

    private static void CollectResetProperties(
        ImmutableArray<IAkcssOperation> operations,
        Dictionary<string, ITypeSymbol?> properties,
        HashSet<IAkcssSymbol> expansionPath)
    {
        foreach (var operation in operations)
        {
            switch (operation)
            {
                case IAkcssPropertySetterOperation { Property: { } property }:
                    var propertyReference = GetStaticMemberReference(property.AvaloniaPropertyDefinition.Symbol) ??
                                            GetStaticMemberReference(property.AttachedPropertyDefinition.Symbol);
                    if (propertyReference != null && !properties.ContainsKey(propertyReference))
                    {
                        properties.Add(propertyReference, GetPropertyReceiverType(property));
                    }

                    break;
                case IAkcssIfOperation ifOperation:
                    CollectResetProperties(ifOperation.Operations, properties, expansionPath);
                    break;
                case IAkcssApplyOperation applyOperation:
                    foreach (var appliedSymbol in applyOperation.AppliedSymbols)
                    {
                        if (appliedSymbol is ITailwindUtilitySymbol { Parameters.Length: > 0 } ||
                            !expansionPath.Add(appliedSymbol))
                        {
                            continue;
                        }

                        CollectResetProperties(appliedSymbol.Operations, properties, expansionPath);
                        expansionPath.Remove(appliedSymbol);
                    }

                    break;
            }
        }
    }

    private static ITypeSymbol? GetPropertyReceiverType(AkburaPropertySymbol property)
    {
        return property.WriteKind switch
        {
            PropertyAccessKind.ClrProperty =>
                (property.WriteDefinition.Symbol as RoslynPropertySymbol)?.ContainingType,
            PropertyAccessKind.AvaloniaProperty =>
                property.WriteDefinition.Symbol?.ContainingType ??
                property.AvaloniaPropertyDefinition.Symbol?.ContainingType ??
                property.AttachedPropertyDefinition.Symbol?.ContainingType,
            PropertyAccessKind.AttachedAccessor => GetAttachedTargetType(property),
            _ => null,
        };
    }

    private static ITypeSymbol? GetAttachedTargetType(AkburaPropertySymbol property)
    {
        if (property.AttachedTargetType.Symbol is ITypeSymbol targetType)
        {
            return targetType;
        }

        var setter = property.WriteDefinition.Symbol as RoslynMethodSymbol ??
                     property.AttachedSetterDefinition.Symbol as RoslynMethodSymbol;
        return setter is { Parameters.Length: > 0 } ? setter.Parameters[0].Type : null;
    }

    private static string? GetStaticMemberReference(Microsoft.CodeAnalysis.ISymbol? symbol)
    {
        return symbol switch
        {
            RoslynFieldSymbol { IsStatic: true } field =>
                $"{GetTypeName(field.ContainingType)}.{EscapeIdentifier(field.Name)}",
            RoslynPropertySymbol { IsStatic: true } property =>
                $"{GetTypeName(property.ContainingType)}.{EscapeIdentifier(property.Name)}",
            _ => null,
        };
    }

    private static string GetMethodReference(RoslynMethodSymbol method)
    {
        return $"{GetTypeName(method.ContainingType)}.{EscapeIdentifier(method.Name)}";
    }

    private static string GetTypeName(Microsoft.CodeAnalysis.ISymbol? symbol)
    {
        return symbol is ITypeSymbol type
            ? type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            : "global::System.Object";
    }

    private static string GetTargetParameterName(
        ImmutableArray<ITailwindUtilityParameterSymbol> parameters)
    {
        var name = "__target";
        var hasConflict = true;
        while (hasConflict)
        {
            hasConflict = false;
            foreach (var parameter in parameters)
            {
                if (string.Equals(parameter.Name, name, StringComparison.Ordinal))
                {
                    name += "_";
                    hasConflict = true;
                    break;
                }
            }
        }

        return name;
    }

    private static string GetParameterName(ITailwindUtilityParameterSymbol parameter)
    {
        var name = parameter.CSharpParameter?.Name ?? parameter.Name;
        return CSharpSyntaxFacts.IsValidIdentifier(name)
            ? EscapeIdentifier(name)
            : $"parameter{parameter.Ordinal}";
    }

    private static string EscapeIdentifier(string name)
    {
        return CSharpSyntaxFacts.GetKeywordKind(name) != CSharpSyntaxKind.None ||
               CSharpSyntaxFacts.GetContextualKeywordKind(name) != CSharpSyntaxKind.None
            ? "@" + name
            : name;
    }

    private static string FormatDouble(double value)
    {
        if (double.IsNaN(value))
        {
            return "global::System.Double.NaN";
        }

        if (double.IsPositiveInfinity(value))
        {
            return "global::System.Double.PositiveInfinity";
        }

        if (double.IsNegativeInfinity(value))
        {
            return "global::System.Double.NegativeInfinity";
        }

        return value.ToString("R", CultureInfo.InvariantCulture);
    }

    private static string GetModuleIdentity(
        IAkcssModuleSymbol symbol,
        string sourcePath)
    {
        if (!string.IsNullOrWhiteSpace(sourcePath))
        {
            return AkcssGeneratedModuleNames.NormalizeSourcePath(sourcePath);
        }

        return string.IsNullOrWhiteSpace(symbol.Path)
            ? symbol.MetadataName
            : AkcssGeneratedModuleNames.NormalizeSourcePath(symbol.Path!);
    }

    private static void AppendHiddenApiAttributes(StringBuilder source, int indentation)
    {
        AppendIndentedLine(
            source,
            indentation,
            $"[{EditorBrowsableAttribute}(global::System.ComponentModel.EditorBrowsableState.Never)]");
        AppendIndentedLine(source, indentation, $"[{BrowsableAttribute}(false)]");
    }

    private static string SanitizeHintPart(string value)
    {
        var result = new StringBuilder(Math.Min(value.Length, 64));
        foreach (var character in value)
        {
            if (result.Length == 64)
            {
                break;
            }

            result.Append(char.IsLetterOrDigit(character) || character is '.' or '_'
                ? character
                : '_');
        }

        return result.Length == 0 ? "module" : result.ToString();
    }

    private static string ToStringLiteral(string value)
    {
        return SymbolDisplay.FormatLiteral(value, quote: true);
    }

    private static string ToLineDirectivePath(string path)
    {
        return "\"" + path + "\"";
    }

    private readonly struct GeneratedValue
    {
        public GeneratedValue(
            string expression,
            DynamicResourceBinding? dynamicResource,
            bool requiresResourceHost)
        {
            Expression = expression;
            DynamicResource = dynamicResource;
            RequiresResourceHost = requiresResourceHost;
        }

        public string Expression { get; }

        public DynamicResourceBinding? DynamicResource { get; }

        public bool RequiresResourceHost { get; }
    }

    private readonly struct GeneratedStatement
    {
        public GeneratedStatement(
            string text,
            int valueOffset)
        {
            Text = text;
            ValueOffset = valueOffset;
        }

        public string Text { get; }

        public int ValueOffset { get; }
    }

    private readonly struct DynamicResourceBinding
    {
        public DynamicResourceBinding(
            string keyExpression,
            string valueParameterName)
        {
            KeyExpression = keyExpression;
            ValueParameterName = valueParameterName;
        }

        public string KeyExpression { get; }

        public string ValueParameterName { get; }
    }

    private sealed class AmxExpressionRewriter : CSharpSyntaxRewriter
    {
        private const string ResourceValueParameter = "__resourceValue";
        private readonly string _targetName;
        private readonly bool _observeDynamicResource;

        public AmxExpressionRewriter(
            string targetName,
            bool observeDynamicResource)
        {
            _targetName = targetName;
            _observeDynamicResource = observeDynamicResource;
        }

        public DynamicResourceBinding? DynamicResource { get; private set; }

        public bool RequiresResourceHost { get; private set; }

        public override Microsoft.CodeAnalysis.SyntaxNode? VisitInvocationExpression(
            CSharpInvocationExpressionSyntax node)
        {
            if (!TryGetAmxInvocation(node, out var methodName, out var genericName) ||
                node.ArgumentList.Arguments.Count != 1)
            {
                return base.VisitInvocationExpression(node);
            }

            if (methodName is "DynamicResource" or "StaticResource")
            {
                RequiresResourceHost = true;
            }

            var keyExpression = node.ArgumentList.Arguments[0].Expression;
            if (methodName == "DynamicResource" &&
                _observeDynamicResource &&
                DynamicResource == null)
            {
                DynamicResource = new DynamicResourceBinding(
                    keyExpression.ToString(),
                    ResourceValueParameter);
                var resourceValue = CSharpSyntaxFactory.PostfixUnaryExpression(
                    CSharpSyntaxKind.SuppressNullableWarningExpression,
                    CSharpSyntaxFactory.IdentifierName(ResourceValueParameter));
                return CSharpSyntaxFactory.CastExpression(
                        genericName.TypeArgumentList.Arguments[0].WithoutTrivia(),
                        resourceValue)
                    .WithTriviaFrom(node);
            }

            if (methodName is "DynamicResource" or "StaticResource")
            {
                return CreateStaticResourceAccess(node, genericName, keyExpression);
            }

            return base.VisitInvocationExpression(node);
        }

        private CSharpExpressionSyntax CreateStaticResourceAccess(
            CSharpInvocationExpressionSyntax original,
            CSharpGenericNameSyntax genericName,
            CSharpExpressionSyntax keyExpression)
        {
            var findResource = CSharpSyntaxFactory.ParseExpression(
                "global::Avalonia.Controls.ResourceNodeExtensions.FindResource");
            var target = CSharpSyntaxFactory.CastExpression(
                CSharpSyntaxFactory.ParseTypeName("global::Avalonia.Controls.IResourceHost"),
                CSharpSyntaxFactory.IdentifierName(_targetName));
            var invocation = CSharpSyntaxFactory.InvocationExpression(
                findResource,
                CSharpSyntaxFactory.ArgumentList(
                    CSharpSyntaxFactory.SeparatedList(
                    [
                        CSharpSyntaxFactory.Argument(target),
                        CSharpSyntaxFactory.Argument(keyExpression.WithoutTrivia()),
                    ])));
            var resource = CSharpSyntaxFactory.PostfixUnaryExpression(
                CSharpSyntaxKind.SuppressNullableWarningExpression,
                invocation);
            return CSharpSyntaxFactory.CastExpression(
                    genericName.TypeArgumentList.Arguments[0].WithoutTrivia(),
                    resource)
                .WithTriviaFrom(original);
        }

        private static bool TryGetAmxInvocation(
            CSharpInvocationExpressionSyntax invocation,
            out string methodName,
            out CSharpGenericNameSyntax genericName)
        {
            methodName = string.Empty;
            genericName = null!;
            if (invocation.Expression is not CSharpMemberAccessExpressionSyntax
                {
                    Expression: CSharpIdentifierNameSyntax { Identifier.ValueText: "Amx" },
                    Name: CSharpGenericNameSyntax name,
                } ||
                name.TypeArgumentList.Arguments.Count != 1)
            {
                return false;
            }

            methodName = name.Identifier.ValueText;
            genericName = name;
            return true;
        }
    }

    private static void AppendIndentedLine(
        StringBuilder source,
        int indentation,
        string text)
    {
        source.Append(' ', indentation * 4).AppendLine(text);
    }
}
