using Akbura.Language;
using Akbura.Language.Binder;
using Akbura.Language.BoundTree;
using Akbura.Language.Operations;
using Akbura.Language.Symbols;
using Akbura.Language.Syntax;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using CSharpSyntaxFacts = Microsoft.CodeAnalysis.CSharp.SyntaxFacts;
using CSharpSyntaxKind = Microsoft.CodeAnalysis.CSharp.SyntaxKind;
using RoslynEventSymbol = Microsoft.CodeAnalysis.IEventSymbol;
using RoslynFieldSymbol = Microsoft.CodeAnalysis.IFieldSymbol;
using RoslynMethodSymbol = Microsoft.CodeAnalysis.IMethodSymbol;
using RoslynPropertySymbol = Microsoft.CodeAnalysis.IPropertySymbol;
using AkburaPropertySymbol = Akbura.Language.Symbols.IPropertySymbol;

namespace Akbura.Furioso;

internal static class ComponentGenerator
{
    private const string RuntimeParameter = "global::Akbura.ComponentTree.Parameter";
    private const string RuntimeInjectService = "global::Akbura.ComponentTree.InjectService";
    private const string RuntimeState = "global::Akbura.ComponentTree.State";
    private const string RuntimeCommandProperty = "global::Avalonia.AvaloniaProperty<global::Akbura.IAkburaCommand>";

    public static string GetHintName(IAkburaComponentSymbol symbol, string sourcePath)
    {
        if (symbol == null)
        {
            throw new ArgumentNullException(nameof(symbol));
        }

        var identity = string.IsNullOrWhiteSpace(sourcePath)
            ? symbol.MetadataName
            : sourcePath;
        return $"Akbura.Component.{SanitizeHintPart(identity)}.{AkcssGeneratedModuleNames.GetStableHash(identity):x8}.g.cs";
    }

    public static string Generate(
        IAkburaComponentSymbol symbol,
        AkburaSemanticModel semanticModel,
        string sourcePath,
        IReadOnlyDictionary<AkburaSyntax, string>? akcssModuleTypeNames = null)
    {
        if (symbol == null)
        {
            throw new ArgumentNullException(nameof(symbol));
        }

        if (semanticModel == null)
        {
            throw new ArgumentNullException(nameof(semanticModel));
        }

        var generator = new Generator(
            symbol,
            semanticModel,
            sourcePath,
            akcssModuleTypeNames ?? new Dictionary<AkburaSyntax, string>());
        return generator.Generate();
    }

    private sealed class Generator
    {
        private readonly IAkburaComponentSymbol _symbol;
        private readonly AkburaSemanticModel _semanticModel;
        private readonly ComponentGenerationSourceMap _sourceMap;
        private readonly string _sourcePath;
        private readonly IReadOnlyDictionary<AkburaSyntax, string> _akcssModuleTypeNames;
        private readonly List<ElementPlan> _elements = [];
        private readonly List<PropertyElementPlan> _propertyElements = [];
        private readonly Dictionary<MarkupElementSyntax, ElementPlan> _elementsBySyntax = new();
        private int _nextElementId;

        public Generator(
            IAkburaComponentSymbol symbol,
            AkburaSemanticModel semanticModel,
            string sourcePath,
            IReadOnlyDictionary<AkburaSyntax, string> akcssModuleTypeNames)
        {
            _symbol = symbol;
            _semanticModel = semanticModel;
            _sourceMap = new ComponentGenerationSourceMap((ComponentSyntaxTree)symbol.SyntaxTree);
            _sourcePath = sourcePath;
            _akcssModuleTypeNames = akcssModuleTypeNames;
        }

        public string Generate()
        {
            var document = _symbol.DeclarationSyntax;
            var roots = BuildElementPlans(document);
            var source = new StringBuilder();

            source.AppendLine("// <auto-generated />");
            source.AppendLine("#nullable enable");
            AppendUsingDirectives(source, document);
            source.AppendLine();

            if (!string.IsNullOrWhiteSpace(_symbol.NamespaceName))
            {
                source.Append("namespace ").Append(_symbol.NamespaceName).AppendLine();
                source.AppendLine("{");
            }

            var classIndentation = string.IsNullOrWhiteSpace(_symbol.NamespaceName) ? 0 : 1;
            var accessibility = GetAccessibility(_symbol.PartialTypes);
            AppendIndented(source, classIndentation)
                .Append(accessibility).Append(" partial class ")
                .Append(EscapeIdentifier(_symbol.Name))
                .Append(" : ").Append(GetBaseTypeName()).AppendLine();
            AppendIndentedLine(source, classIndentation, "{");

            AppendParameterMembers(source, classIndentation + 1);
            AppendServiceMembers(source, classIndentation + 1);
            AppendCommandMembers(source, classIndentation + 1);
            AppendStateMembers(source, classIndentation + 1);
            AppendElementFields(source, classIndentation + 1);
            AppendUserMembers(source, document, classIndentation + 1);
            AppendLifecycleMembers(source, roots, classIndentation + 1);
            AppendDescriptorArrays(source, classIndentation + 1);

            AppendIndentedLine(source, classIndentation, "}");
            if (!string.IsNullOrWhiteSpace(_symbol.NamespaceName))
            {
                source.AppendLine("}");
            }

            return source.ToString();
        }

        private ImmutableArray<ElementPlan> BuildElementPlans(AkburaDocumentSyntax document)
        {
            var roots = ImmutableArray.CreateBuilder<ElementPlan>();
            foreach (var root in document.Members.OfType<MarkupRootSyntax>())
            {
                if (TryBuildElement(root.Element, out var plan))
                {
                    roots.Add(plan);
                }
            }

            return roots.ToImmutable();
        }

        private bool TryBuildElement(MarkupElementSyntax syntax, out ElementPlan plan)
        {
            if (_elementsBySyntax.TryGetValue(syntax, out plan!))
            {
                return true;
            }

            if (_semanticModel.GetSymbolInfo(syntax).Symbol is not IMarkupComponentSymbol component)
            {
                plan = null!;
                return false;
            }

            var nameOperation = component.AttributeOperations
                .OfType<IMarkupNameAssignmentOperation>()
                .FirstOrDefault(static operation => !operation.HasErrors && operation.NameSymbol != null);
            var fieldName = nameOperation?.NameSymbol is { } name
                ? EscapeIdentifier(name.IdentifierText)
                : "__element" + _nextElementId.ToString(CultureInfo.InvariantCulture);
            plan = new ElementPlan(
                _nextElementId++,
                syntax,
                component,
                fieldName,
                GetComponentTypeName(component),
                nameOperation,
                FindTemplateOwner(syntax));
            _elements.Add(plan);
            _elementsBySyntax.Add(syntax, plan);

            foreach (var content in syntax.Body.OfType<MarkupElementContentSyntax>())
            {
                var childSyntax = content.Element;
                var childSymbol = _semanticModel.GetSymbolInfo(childSyntax).Symbol;
                if (childSymbol is IMarkupComponentSymbol)
                {
                    if (TryBuildElement(childSyntax, out var child))
                    {
                        plan.Children.Add(child);
                    }

                    continue;
                }

                if (childSymbol is not AkburaPropertySymbol property ||
                    _semanticModel.GetOperation(childSyntax) is not IMarkupContentOperation operation)
                {
                    continue;
                }

                var propertyElement = new PropertyElementPlan(
                    _propertyElements.Count,
                    plan,
                    childSyntax,
                    property,
                    operation);
                _propertyElements.Add(propertyElement);
                foreach (var propertyContent in childSyntax.Body.OfType<MarkupElementContentSyntax>())
                {
                    if (TryBuildElement(propertyContent.Element, out var child))
                    {
                        propertyElement.Children.Add(child);
                    }
                }

                plan.PropertyElements.Add(propertyElement);
            }

            return true;
        }

        private MarkupElementSyntax? FindTemplateOwner(MarkupElementSyntax syntax)
        {
            for (var ancestor = syntax.Parent; ancestor != null; ancestor = ancestor.Parent)
            {
                if (ancestor is MarkupElementSyntax propertyElement &&
                    _semanticModel.GetSymbolInfo(propertyElement).Symbol is AkburaPropertySymbol property &&
                    IsTemplateContentProperty(property))
                {
                    return propertyElement;
                }
            }

            return null;
        }

        private void AppendParameterMembers(StringBuilder source, int indentation)
        {
            foreach (var parameter in _symbol.Parameters)
            {
                if (TryGetContentCollection(parameter, out var collection))
                {
                    AppendCollectionContentParameter(
                        source,
                        indentation,
                        parameter,
                        collection);
                }
                else
                {
                    AppendRegularParameter(source, indentation, parameter);
                }
            }
        }

        private void AppendRegularParameter(
            StringBuilder source,
            int indentation,
            IParamSymbol parameter)
        {
            var type = GetTypeName(parameter.Type.Symbol);
            var name = EscapeIdentifier(parameter.Name);
            var binding = parameter.BindingKind switch
            {
                ParamBindingKind.Bind => "global::Akbura.ComponentTree.ParameterBinding.Bind",
                ParamBindingKind.Out => "global::Akbura.ComponentTree.ParameterBinding.Out",
                _ => "global::Akbura.ComponentTree.ParameterBinding.In",
            };
            var optional = parameter.HasDefaultValue
                ? $"new global::Avalonia.Data.Optional<{type}>({GetExpression(parameter.DefaultValueSyntax)})"
                : "default";
            var isContent = IsContentParameter(parameter);

            AppendIndented(source, indentation)
                .Append("public static readonly global::Akbura.ComponentTree.Parameter<")
                .Append(EscapeIdentifier(_symbol.Name)).Append(", ").Append(type).Append("> ")
                .Append(name).AppendLine("Property =");
            AppendIndented(source, indentation + 1)
                .Append("global::Akbura.ComponentTree.Parameter.Create<")
                .Append(EscapeIdentifier(_symbol.Name)).Append(", ").Append(type).Append(">(")
                .Append(ToStringLiteral(parameter.Name)).Append(", ")
                .Append(optional).Append(", ").Append(binding);
            if (isContent)
            {
                source.Append(", changed: static (__owner, __change) => __owner.__OnContentChanged(__change)");
            }

            source.AppendLine(");");
            if (isContent)
            {
                AppendIndentedLine(source, indentation, "[global::Avalonia.Metadata.Content]");
            }

            AppendIndented(source, indentation)
                .Append("public ").Append(type).Append(' ').Append(name).AppendLine();
            AppendIndentedLine(source, indentation, "{");
            AppendIndented(source, indentation + 1).Append("get => GetValue(").Append(name).AppendLine("Property.AvaloniaProperty);");
            AppendIndented(source, indentation + 1).Append("set => SetValue(").Append(name).AppendLine("Property.AvaloniaProperty, value);");
            AppendIndentedLine(source, indentation, "}");
            source.AppendLine();

            if (isContent)
            {
                AppendSingleContentChanged(source, indentation);
            }
        }

        private void AppendSingleContentChanged(StringBuilder source, int indentation)
        {
            AppendIndentedLine(
                source,
                indentation,
                "private void __OnContentChanged(global::Avalonia.AvaloniaPropertyChangedEventArgs change)");
            AppendIndentedLine(source, indentation, "{");
            AppendIndentedLine(source, indentation + 1, "if (change.OldValue is global::Avalonia.Controls.Control __oldContent)");
            AppendIndentedLine(source, indentation + 1, "{");
            AppendIndentedLine(source, indentation + 2, "LogicalChildren.Remove(__oldContent);");
            AppendIndentedLine(source, indentation + 1, "}");
            AppendIndentedLine(source, indentation + 1, "if (change.NewValue is global::Avalonia.Controls.Control __newContent)");
            AppendIndentedLine(source, indentation + 1, "{");
            AppendIndentedLine(source, indentation + 2, "LogicalChildren.Add(__newContent);");
            AppendIndentedLine(source, indentation + 1, "}");
            AppendIndentedLine(source, indentation, "}");
            source.AppendLine();
        }

        private void AppendCollectionContentParameter(
            StringBuilder source,
            int indentation,
            IParamSymbol parameter,
            ContentCollectionInfo collection)
        {
            var ownerType = EscapeIdentifier(_symbol.Name);
            var name = EscapeIdentifier(parameter.Name);
            var suffix = SanitizeIdentifier(parameter.Name);
            var backingField = "__content_" + suffix;
            var subscribedField = "__contentSubscribed_" + suffix;
            var logicalChildrenField = "__contentLogicalChildren_" + suffix;
            var synchronizeMethod = "__SynchronizeContentLogicalChildren_" + suffix;
            var collectionChangedMethod = "__OnContentCollectionChanged_" + suffix;
            var addMethod = "__AkburaAddContent_" + suffix;

            AppendIndented(source, indentation)
                .Append("private readonly ").Append(collection.BackingType).Append(' ')
                .Append(backingField).AppendLine(" = [];");
            if (collection.ObservesChanges)
            {
                AppendIndented(source, indentation).Append("private bool ")
                    .Append(subscribedField).AppendLine(";");
            }

            AppendIndented(source, indentation)
                .Append("private readonly global::System.Collections.Generic.List<global::Avalonia.Controls.Control> ")
                .Append(logicalChildrenField).AppendLine(" = [];");
            source.AppendLine();

            AppendIndented(source, indentation)
                .Append("public static readonly global::Akbura.ComponentTree.ReadOnlyParameter<")
                .Append(ownerType).Append(", ").Append(collection.PropertyType).Append("> ")
                .Append(name).AppendLine("Property =");
            AppendIndented(source, indentation + 1)
                .Append("global::Akbura.ComponentTree.Parameter.CreateReadOnly<")
                .Append(ownerType).Append(", ").Append(collection.PropertyType).Append(">(")
                .Append(ToStringLiteral(parameter.Name)).Append(", static __owner => __owner.")
                .Append(name).AppendLine(");");
            AppendIndentedLine(source, indentation, "[global::Avalonia.Metadata.Content]");
            AppendIndented(source, indentation).Append("public ").Append(collection.PropertyType)
                .Append(' ').Append(name).AppendLine();
            AppendIndentedLine(source, indentation, "{");
            AppendIndentedLine(source, indentation + 1, "get");
            AppendIndentedLine(source, indentation + 1, "{");
            if (collection.ObservesChanges)
            {
                AppendIndented(source, indentation + 2).Append("if (!").Append(subscribedField).AppendLine(")");
                AppendIndentedLine(source, indentation + 2, "{");
                AppendIndented(source, indentation + 3).Append(backingField)
                    .Append(".CollectionChanged += ").Append(collectionChangedMethod).AppendLine(";");
                AppendIndented(source, indentation + 3).Append(subscribedField).AppendLine(" = true;");
                AppendIndentedLine(source, indentation + 2, "}");
            }

            AppendIndented(source, indentation + 2).Append("return ").Append(backingField).AppendLine(";");
            AppendIndentedLine(source, indentation + 1, "}");
            AppendIndentedLine(source, indentation, "}");
            source.AppendLine();

            AppendIndentedLine(source, indentation, "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            AppendIndentedLine(source, indentation, "[global::System.ComponentModel.Browsable(false)]");
            AppendIndented(source, indentation).Append("public void ").Append(addMethod)
                .Append('(').Append(collection.ElementType).AppendLine(" value)");
            AppendIndentedLine(source, indentation, "{");
            AppendIndented(source, indentation + 1).Append(name).AppendLine(".Add(value);");
            if (!collection.ObservesChanges)
            {
                AppendIndented(source, indentation + 1).Append(synchronizeMethod).AppendLine("();");
            }

            AppendIndentedLine(source, indentation, "}");
            source.AppendLine();

            if (collection.ObservesChanges)
            {
                AppendIndented(source, indentation).Append("private void ").Append(collectionChangedMethod)
                    .AppendLine("(object? sender, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs change)");
                AppendIndentedLine(source, indentation, "{");
                AppendIndentedLine(source, indentation + 1, "switch (change.Action)");
                AppendIndentedLine(source, indentation + 1, "{");
                AppendIndentedLine(source, indentation + 2, "case global::System.Collections.Specialized.NotifyCollectionChangedAction.Add:");
                AppendIndentedLine(source, indentation + 2, "case global::System.Collections.Specialized.NotifyCollectionChangedAction.Move:");
                AppendIndentedLine(source, indentation + 2, "case global::System.Collections.Specialized.NotifyCollectionChangedAction.Remove:");
                AppendIndentedLine(source, indentation + 2, "case global::System.Collections.Specialized.NotifyCollectionChangedAction.Replace:");
                AppendIndented(source, indentation + 3).Append(synchronizeMethod).AppendLine("();");
                AppendIndentedLine(source, indentation + 3, "break;");
                AppendIndentedLine(source, indentation + 2, "case global::System.Collections.Specialized.NotifyCollectionChangedAction.Reset:");
                AppendIndentedLine(source, indentation + 3, "throw new global::System.NotSupportedException(\"Resetting component content is not supported.\");");
                AppendIndentedLine(source, indentation + 2, "default:");
                AppendIndentedLine(source, indentation + 3, "throw new global::System.ArgumentOutOfRangeException(nameof(change));");
                AppendIndentedLine(source, indentation + 1, "}");
                AppendIndentedLine(source, indentation, "}");
                source.AppendLine();
            }

            AppendIndented(source, indentation).Append("private void ").Append(synchronizeMethod).AppendLine("()");
            AppendIndentedLine(source, indentation, "{");
            AppendIndented(source, indentation + 1).Append("foreach (var __oldContent in ")
                .Append(logicalChildrenField).AppendLine(")");
            AppendIndentedLine(source, indentation + 1, "{");
            AppendIndentedLine(source, indentation + 2, "LogicalChildren.Remove(__oldContent);");
            AppendIndentedLine(source, indentation + 1, "}");
            AppendIndented(source, indentation + 1).Append(logicalChildrenField).AppendLine(".Clear();");
            AppendIndented(source, indentation + 1).Append("foreach (var __item in ")
                .Append(backingField).AppendLine(")");
            AppendIndentedLine(source, indentation + 1, "{");
            AppendIndentedLine(source, indentation + 2, "if (__item is global::Avalonia.Controls.Control __contentControl &&");
            AppendIndented(source, indentation + 3).Append('!')
                .Append(logicalChildrenField).AppendLine(".Contains(__contentControl))");
            AppendIndentedLine(source, indentation + 2, "{");
            AppendIndentedLine(source, indentation + 3, "LogicalChildren.Add(__contentControl);");
            AppendIndented(source, indentation + 3).Append(logicalChildrenField)
                .AppendLine(".Add(__contentControl);");
            AppendIndentedLine(source, indentation + 2, "}");
            AppendIndentedLine(source, indentation + 1, "}");
            AppendIndentedLine(source, indentation, "}");
            source.AppendLine();
        }

        private void AppendServiceMembers(StringBuilder source, int indentation)
        {
            foreach (var service in _symbol.InjectedServices)
            {
                var type = GetTypeName(service.Type.Symbol);
                var name = EscapeIdentifier(service.Name);
                var field = "__service_" + SanitizeIdentifier(service.Name);

                AppendIndented(source, indentation).Append("private ").Append(type).Append("? ").Append(field).AppendLine(";");
                AppendIndented(source, indentation)
                    .Append("public static readonly global::Akbura.ComponentTree.InjectService<")
                    .Append(EscapeIdentifier(_symbol.Name)).Append(", ").Append(type.TrimEnd('?')).Append("> ")
                    .Append(name).AppendLine("Property =");
                AppendIndented(source, indentation + 1)
                    .Append("global::Akbura.ComponentTree.InjectService.Create<")
                    .Append(EscapeIdentifier(_symbol.Name)).Append(", ").Append(type.TrimEnd('?')).Append(">(")
                    .Append(ToStringLiteral(service.Name)).Append(", static __owner => __owner.")
                    .Append(field).Append(", static (__owner, __value) => __owner.__SetService_")
                    .Append(SanitizeIdentifier(service.Name)).Append("(__value), isOptional: ")
                    .Append(service.IsOptional ? "true" : "false").AppendLine(");");
                AppendIndented(source, indentation).Append("private void __SetService_")
                    .Append(SanitizeIdentifier(service.Name)).Append('(').Append(type.TrimEnd('?')).Append("? value) => ")
                    .Append("SetAndRaise(").Append(name).Append("Property.AvaloniaProperty, ref ")
                    .Append(field).AppendLine(", value);");
                AppendIndented(source, indentation).Append("public ").Append(type).Append(' ').Append(name).AppendLine();
                AppendIndentedLine(source, indentation, "{");
                AppendIndented(source, indentation + 1).Append("get => ").Append(field);
                if (!service.IsOptional)
                {
                    source.Append('!');
                }

                source.AppendLine(";");
                AppendIndented(source, indentation + 1).Append("set => __SetService_")
                    .Append(SanitizeIdentifier(service.Name)).AppendLine("(value);");
                AppendIndentedLine(source, indentation, "}");
                source.AppendLine();
            }
        }

        private void AppendCommandMembers(StringBuilder source, int indentation)
        {
            foreach (var command in _symbol.Commands)
            {
                var name = EscapeIdentifier(command.Name);
                var commandType = GetCommandType(command);
                AppendIndented(source, indentation)
                    .Append("public static readonly global::Avalonia.StyledProperty<global::Akbura.IAkburaCommand> ")
                    .Append(name).Append("Property = global::Avalonia.AvaloniaProperty.Register<")
                    .Append(EscapeIdentifier(_symbol.Name)).Append(", global::Akbura.IAkburaCommand>(")
                    .Append(ToStringLiteral(command.Name)).AppendLine(");");
                AppendIndented(source, indentation).Append("public ").Append(commandType).Append(' ').Append(name).AppendLine();
                AppendIndentedLine(source, indentation, "{");
                AppendIndented(source, indentation + 1).Append("get => (").Append(commandType).Append(")GetValue(")
                    .Append(name).AppendLine("Property);");
                AppendIndented(source, indentation + 1).Append("set => SetValue(").Append(name).AppendLine("Property, value);");
                AppendIndentedLine(source, indentation, "}");
                source.AppendLine();
            }
        }

        private void AppendStateMembers(StringBuilder source, int indentation)
        {
            foreach (var state in _symbol.States)
            {
                var type = GetTypeName(state.Type.Symbol);
                var name = EscapeIdentifier(state.Name);
                var suffix = SanitizeIdentifier(state.Name);
                var stateInfoFactory = GetStateInfoFactory(state, type);

                AppendIndented(source, indentation).Append("private static readonly global::Akbura.ComponentTree.StateInfo<")
                    .Append(type).Append("> s_stateInfo_").Append(suffix).Append(" = ").Append(stateInfoFactory).AppendLine(";");
                AppendIndented(source, indentation).Append("private global::Akbura.ComponentTree.State<")
                    .Append(type).Append(">? __state_").Append(suffix).AppendLine(";");
                AppendIndented(source, indentation).Append("private global::Akbura.ComponentTree.State<")
                    .Append(type).Append("> __State_").Append(suffix).Append(" => __state_").Append(suffix)
                    .Append(" ??= CreateState(s_stateInfo_").Append(suffix).AppendLine(");");
                AppendIndented(source, indentation).Append("private ").Append(type).Append(' ').Append(name).AppendLine();
                AppendIndentedLine(source, indentation, "{");
                AppendIndented(source, indentation + 1).Append("get => __State_").Append(suffix).AppendLine(".Value;");
                AppendIndented(source, indentation + 1).Append("set => __State_").Append(suffix).AppendLine(".Value = value;");
                AppendIndentedLine(source, indentation, "}");
                source.AppendLine();
            }
        }

        private string GetStateInfoFactory(IStateSymbol state, string type)
        {
            var ownerType = EscapeIdentifier(_symbol.Name);
            var stateName = ToStringLiteral(state.Name);
            if (_semanticModel.BindingSession.BindSemanticSyntax(state.InitializerSyntax) is BoundStateInitializer
                {
                    UseHookInvocation: { } invocation,
                })
            {
                return $"global::Akbura.ComponentTree.StateInfo<{type}>.FromState({stateName}, static __owner => (({ownerType})__owner).__CreateState_{SanitizeIdentifier(state.Name)}())";
            }

            return $"new global::Akbura.ComponentTree.StateInfo<{type}>({stateName}, static __owner => (({ownerType})__owner).__CreateStateValue_{SanitizeIdentifier(state.Name)}())";
        }

        private void AppendElementFields(StringBuilder source, int indentation)
        {
            foreach (var element in _elements)
            {
                if (element.TemplateOwner != null)
                {
                    continue;
                }

                AppendIndented(source, indentation).Append("private ").Append(element.TypeName).Append(' ')
                    .Append(element.FieldName).AppendLine(" = null!;");
            }

            if (_elements.Count > 0)
            {
                source.AppendLine();
            }
        }

        private void AppendUserMembers(
            StringBuilder source,
            AkburaDocumentSyntax document,
            int indentation)
        {
            foreach (var state in _symbol.States)
            {
                var type = GetTypeName(state.Type.Symbol);
                var suffix = SanitizeIdentifier(state.Name);
                if (_semanticModel.BindingSession.BindSemanticSyntax(state.InitializerSyntax) is BoundStateInitializer
                    {
                        UseHookInvocation: { } invocation,
                    })
                {
                    AppendIndented(source, indentation).Append("private global::Akbura.ComponentTree.State<")
                        .Append(type).Append("> __CreateState_").Append(suffix).Append("() => ")
                        .Append(invocation.EffectiveInvocation.ToFullString().Trim()).AppendLine(";");
                }
                else
                {
                    AppendIndented(source, indentation).Append("private ").Append(type).Append(" __CreateStateValue_")
                        .Append(suffix).Append("() => ").Append(GetExpression(state.InitializerExpression)).AppendLine(";");
                }
            }

            if (!_symbol.States.IsEmpty)
            {
                source.AppendLine();
            }

            foreach (var member in document.Members.OfType<CSharpStatementSyntax>())
            {
                if (_semanticModel.GetOperation(member) is IUseHookOperation)
                {
                    continue;
                }

                var text = member.ToFullString().Trim();
                if (text.Length == 0)
                {
                    continue;
                }

                AppendLineDirective(source, indentation, member, text, valueOffset: 0);
                source.AppendLine();
            }
        }

        private void AppendLifecycleMembers(
            StringBuilder source,
            ImmutableArray<ElementPlan> roots,
            int indentation)
        {
            AppendIndentedLine(source, indentation, "protected override global::Avalonia.Controls.Control FirstUpdate()");
            AppendIndentedLine(source, indentation, "{");
            if (roots.IsDefaultOrEmpty)
            {
                AppendIndentedLine(source, indentation + 1, "__generatedRoot = new global::Avalonia.Controls.Control();");
                AppendIndentedLine(source, indentation + 1, "__generatedRoot.BeginInit();");
                AppendIndentedLine(source, indentation + 1, "__generatedRoot.EndInit();");
                AppendIndentedLine(source, indentation + 1, "return __generatedRoot;");
                AppendIndentedLine(source, indentation, "}");
                source.AppendLine();
                AppendIndentedLine(source, indentation, "private global::Avalonia.Controls.Control __generatedRoot = null!;");
            }
            else
            {
                foreach (var element in _elements)
                {
                    if (element.TemplateOwner != null)
                    {
                        continue;
                    }

                    AppendIndented(source, indentation + 1).Append(element.FieldName).Append(" = new ")
                        .Append(element.TypeName).AppendLine("();");
                    AppendIndented(source, indentation + 1).Append(element.FieldName).AppendLine(".BeginInit();");
                }

                source.AppendLine();
                foreach (var element in _elements)
                {
                    if (element.TemplateOwner != null)
                    {
                        continue;
                    }

                    AppendFirstUpdateAttributes(source, element, indentation + 1);
                    AppendFirstUpdateContent(source, element, indentation + 1);
                }

                foreach (var propertyElement in _propertyElements)
                {
                    if (propertyElement.Owner.TemplateOwner == null)
                    {
                        AppendPropertyElement(source, propertyElement, indentation + 1);
                    }
                }

                foreach (var element in _elements)
                {
                    if (element.TemplateOwner == null)
                    {
                        AppendAkcssStyles(source, element, indentation + 1);
                    }
                }

                AppendRootDataContextBinding(source, roots[0], indentation + 1);

                for (var index = _elements.Count - 1; index >= 0; index--)
                {
                    if (_elements[index].TemplateOwner == null)
                    {
                        AppendIndented(source, indentation + 1).Append(_elements[index].FieldName).AppendLine(".EndInit();");
                    }
                }

                AppendIndented(source, indentation + 1).Append("return ").Append(roots[0].FieldName).AppendLine(";");
                AppendIndentedLine(source, indentation, "}");
            }

            source.AppendLine();
            AppendIndentedLine(source, indentation, "protected override global::Avalonia.Controls.Control Update()");
            AppendIndentedLine(source, indentation, "{");
            foreach (var member in _symbol.DeclarationSyntax.Members.OfType<CSharpStatementSyntax>())
            {
                if (_semanticModel.GetOperation(member) is not IUseHookOperation operation || operation.HasErrors)
                {
                    continue;
                }

                AppendLineDirective(
                    source,
                    indentation + 1,
                    member,
                    operation.EffectiveInvocation.ToFullString().Trim() + ";",
                    valueOffset: 0);
            }

            foreach (var element in _elements)
            {
                if (element.TemplateOwner == null)
                {
                    AppendUpdateAttributes(source, element, indentation + 1);
                    AppendDynamicContent(source, element, indentation + 1);
                    AppendAkcssRefresh(source, element, indentation + 1);
                }
            }

            AppendIndented(source, indentation + 1).Append("return ")
                .Append(roots.IsDefaultOrEmpty ? "__generatedRoot" : roots[0].FieldName).AppendLine(";");
            AppendIndentedLine(source, indentation, "}");
            source.AppendLine();
        }

        private static void AppendRootDataContextBinding(
            StringBuilder source,
            ElementPlan root,
            int indentation)
        {
            if (root.Symbol.AttributeOperations
                .OfType<IMarkupPropertySetterOperation>()
                .Any(static operation =>
                    !operation.HasErrors &&
                    string.Equals(
                        operation.Property?.Name,
                        "DataContext",
                        StringComparison.Ordinal)))
            {
                return;
            }

            AppendIndented(source, indentation).Append(root.FieldName)
                .Append(".Bind(global::Avalonia.StyledElement.DataContextProperty, ")
                .AppendLine("global::Avalonia.AvaloniaObjectExtensions.GetObservable(this, global::Avalonia.StyledElement.DataContextProperty));");
        }

        private void AppendFirstUpdateAttributes(StringBuilder source, ElementPlan element, int indentation)
        {
            foreach (var operation in element.Symbol.AttributeOperations)
            {
                if (operation.HasErrors)
                {
                    continue;
                }

                switch (operation)
                {
                    case IMarkupNameAssignmentOperation { NameSymbol: { } name }:
                        if (!string.Equals(element.FieldName, EscapeIdentifier(name.IdentifierText), StringComparison.Ordinal))
                        {
                            AppendIndented(source, indentation).Append(EscapeIdentifier(name.IdentifierText))
                                .Append(" = ").Append(element.FieldName).AppendLine(";");
                        }

                        AppendIndented(source, indentation).Append(element.FieldName).Append(".Name = ")
                            .Append(ToStringLiteral(name.IdentifierText)).AppendLine(";");
                        break;
                    case IMarkupRoutedEventBindingOperation routedEvent:
                        AppendRoutedEvent(source, element, routedEvent, indentation);
                        break;
                    case IMarkupCommandBindingOperation command:
                        AppendCommandBinding(source, element, command, indentation);
                        break;
                    case IMarkupPropertySetterOperation setter when IsFirstUpdateValue(setter):
                        AppendPropertySetter(source, element.FieldName, setter, indentation);
                        break;
                }
            }
        }

        private void AppendUpdateAttributes(StringBuilder source, ElementPlan element, int indentation)
        {
            foreach (var operation in element.Symbol.AttributeOperations.OfType<IMarkupPropertySetterOperation>())
            {
                if (!operation.HasErrors && !IsFirstUpdateValue(operation))
                {
                    AppendPropertySetter(source, element.FieldName, operation, indentation);
                }
            }
        }

        private void AppendFirstUpdateContent(StringBuilder source, ElementPlan element, int indentation)
        {
            if (_semanticModel.GetOperation(element.Syntax) is not IMarkupContentOperation operation ||
                operation.HasErrors ||
                operation.Property == null)
            {
                return;
            }

            if (operation.ContentModel.IsCollection)
            {
                foreach (var child in element.Children)
                {
                    AppendCollectionAdd(source, element.FieldName, operation.Property, child.FieldName, indentation, operation.Syntax);
                }

                return;
            }

            if (element.Children.Count == 1)
            {
                AppendPropertyWrite(source, element.FieldName, operation.Property, element.Children[0].FieldName, indentation, operation.Syntax);
                return;
            }

            if (!operation.IsSynthesizedString)
            {
                var value = operation.LiteralValue != null
                    ? ToStringLiteral(operation.LiteralValue)
                    : GetContentExpression(operation);
                if (value != null)
                {
                    AppendPropertyWrite(source, element.FieldName, operation.Property, value, indentation, operation.Syntax);
                }
            }
        }

        private void AppendDynamicContent(StringBuilder source, ElementPlan element, int indentation)
        {
            if (_semanticModel.GetOperation(element.Syntax) is not IMarkupContentOperation
                {
                    HasErrors: false,
                    IsSynthesizedString: true,
                    Property: { } property,
                } operation)
            {
                return;
            }

            var expression = GetContentExpression(operation);
            if (expression != null)
            {
                AppendPropertyWrite(source, element.FieldName, property, expression, indentation, operation.Syntax);
            }
        }

        private void AppendPropertyElement(StringBuilder source, PropertyElementPlan plan, int indentation)
        {
            if (plan.Operation.HasErrors || plan.Children.Count == 0)
            {
                return;
            }

            if (IsTemplateContentProperty(plan.Property))
            {
                AppendTemplatePropertyElement(source, plan, indentation);
                return;
            }

            if (plan.Operation.ContentModel.IsCollection)
            {
                foreach (var child in plan.Children)
                {
                    AppendCollectionAdd(source, plan.Owner.FieldName, plan.Property, child.FieldName, indentation, plan.Syntax);
                }

                return;
            }

            AppendPropertyWrite(
                source,
                plan.Owner.FieldName,
                plan.Property,
                plan.Children[0].FieldName,
                indentation,
                plan.Syntax);
        }

        private void AppendTemplatePropertyElement(
            StringBuilder source,
            PropertyElementPlan plan,
            int indentation)
        {
            var dataType = _semanticModel.BindingSession.MarkupDataTypes.TryGetDataType(
                plan.Syntax,
                out var resolvedDataType)
                ? GetTypeName(resolvedDataType)
                : "global::System.Object";
            var itemName = _semanticModel.BindingSession.MarkupDataTypes.TryCreateItemSymbol(
                plan.Syntax,
                out var itemSymbol) &&
                itemSymbol != null
                    ? EscapeIdentifier(itemSymbol.Name)
                    : "__item";
            var templateName = "__template" + plan.Id.ToString(CultureInfo.InvariantCulture);
            var templateElements = _elements
                .Where(element => ReferenceEquals(element.TemplateOwner, plan.Syntax))
                .ToArray();
            if (templateElements.Length == 0)
            {
                return;
            }

            AppendIndented(source, indentation).Append("var ").Append(templateName)
                .Append(" = new global::Avalonia.Controls.Templates.FuncDataTemplate<")
                .Append(dataType).Append(">((").Append(itemName).AppendLine(", __nameScope) =>");
            AppendIndentedLine(source, indentation, "{");
            foreach (var element in templateElements)
            {
                AppendIndented(source, indentation + 1).Append("var ").Append(element.FieldName)
                    .Append(" = new ").Append(element.TypeName).AppendLine("();");
                AppendIndented(source, indentation + 1).Append(element.FieldName).AppendLine(".BeginInit();");
            }

            source.AppendLine();
            foreach (var element in templateElements)
            {
                AppendFirstUpdateAttributes(source, element, indentation + 1);
                AppendUpdateAttributes(source, element, indentation + 1);
                AppendFirstUpdateContent(source, element, indentation + 1);
                AppendDynamicContent(source, element, indentation + 1);
            }

            foreach (var propertyElement in _propertyElements)
            {
                if (ReferenceEquals(propertyElement.Owner.TemplateOwner, plan.Syntax))
                {
                    AppendPropertyElement(source, propertyElement, indentation + 1);
                }
            }

            foreach (var element in templateElements)
            {
                AppendAkcssStyles(source, element, indentation + 1);
            }

            for (var index = templateElements.Length - 1; index >= 0; index--)
            {
                AppendIndented(source, indentation + 1).Append(templateElements[index].FieldName)
                    .AppendLine(".EndInit();");
            }

            AppendIndented(source, indentation + 1).Append("return ")
                .Append(plan.Children[0].FieldName).AppendLine(";");
            AppendIndentedLine(source, indentation, "});");
            AppendPropertyWrite(
                source,
                plan.Owner.FieldName,
                plan.Property,
                templateName,
                indentation,
                plan.Syntax);
        }

        private bool IsTemplateContentProperty(AkburaPropertySymbol property)
        {
            var clrProperty = property.ClrPropertyDefinition.Symbol as RoslynPropertySymbol ??
                              property.WriteDefinition.Symbol as RoslynPropertySymbol ??
                              property.ReadDefinition.Symbol as RoslynPropertySymbol;
            return clrProperty != null &&
                _semanticModel.BindingSession.MarkupTemplateContent.IsTemplateContentProperty(clrProperty);
        }

        private void AppendAkcssStyles(
            StringBuilder source,
            ElementPlan element,
            int indentation)
        {
            var activators = GetAkcssActivatorExpressions(element);
            if (activators.Count == 0)
            {
                return;
            }

            AppendIndented(source, indentation)
                .Append("global::Akbura.AkburaControl.SetAkcssStyles(")
                .Append(element.FieldName)
                .AppendLine(",");
            AppendIndentedLine(source, indentation + 1, "global::System.Collections.Immutable.ImmutableArray.Create<global::Akbura.Akcss.AkcssStyleActivator>");
            AppendIndentedLine(source, indentation + 1, "(");
            for (var index = 0; index < activators.Count; index++)
            {
                AppendIndented(source, indentation + 2)
                    .Append(activators[index])
                    .AppendLine(index == activators.Count - 1 ? string.Empty : ",");
            }

            AppendIndentedLine(source, indentation + 1, "));");
        }

        private void AppendAkcssRefresh(
            StringBuilder source,
            ElementPlan element,
            int indentation)
        {
            if (GetAkcssActivatorExpressions(element).Count == 0)
            {
                return;
            }

            AppendIndented(source, indentation)
                .Append("global::Akbura.AkburaControl.ExecuteAkcssStyles(")
                .Append(element.FieldName)
                .AppendLine(");");
        }

        private List<string> GetAkcssActivatorExpressions(ElementPlan element)
        {
            var result = new List<string>();
            foreach (var operation in element.Symbol.AttributeOperations)
            {
                if (operation.HasErrors)
                {
                    continue;
                }

                if (operation is IMarkupPropertySetterOperation propertySetter)
                {
                    foreach (var style in propertySetter.AppliedAkcssSymbols)
                    {
                        if (TryGetAkcssStyleReference(style, out var styleReference))
                        {
                            result.Add(
                                "new global::Akbura.Akcss.AkcssClassActivator(" +
                                "(global::Akbura.Akcss.AkcssClass)" + styleReference + ")");
                        }
                    }
                }

                if (operation is not ITailwindUtilityAttributeOperation utilityOperation)
                {
                    continue;
                }

                foreach (var utility in utilityOperation.Utilities)
                {
                    if (TryGetAkcssStyleReference(utility, out var utilityReference))
                    {
                        result.Add(GetAkcssUtilityActivatorExpression(
                            utilityOperation,
                            utility,
                            utilityReference));
                    }
                }
            }

            return result;
        }

        private string GetAkcssUtilityActivatorExpression(
            ITailwindUtilityAttributeOperation operation,
            ITailwindUtilitySymbol utility,
            string utilityReference)
        {
            var runtimeUtilityType = GetRuntimeUtilityType(utility);
            var result = new StringBuilder("new global::Akbura.Akcss.AkcssUtilityActivator(")
                .Append("(global::Akbura.Akcss.AkcssUtility)")
                .Append(utilityReference)
                .Append(", __target => ((")
                .Append(runtimeUtilityType)
                .Append(')')
                .Append(utilityReference)
                .Append(").Update(__target");
            foreach (var argument in operation.Arguments)
            {
                result.Append(", ").Append(GetTailwindUtilityArgumentExpression(argument));
            }

            result.Append(')');
            if (operation.HasCondition)
            {
                result.Append(", () => ").Append(GetTailwindConditionExpression(operation));
            }

            return result.Append(')').ToString();
        }

        private bool TryGetAkcssStyleReference(
            IAkcssSymbol style,
            out string reference)
        {
            reference = string.Empty;
            var moduleSyntax = GetAkcssModuleSyntax(style.DeclarationSyntax);
            if (moduleSyntax == null ||
                _semanticModel.GetDeclaredSymbol(moduleSyntax) is not IAkcssModuleSymbol module)
            {
                return false;
            }

            var styleIndex = -1;
            for (var index = 0; index < module.AkcssSymbols.Length; index++)
            {
                var candidate = module.AkcssSymbols[index];
                if (ReferenceEquals(candidate.DeclarationSyntax, style.DeclarationSyntax) ||
                    ReferenceEquals(candidate.DeclarationSyntax.Root, style.DeclarationSyntax.Root) &&
                    candidate.DeclarationSyntax.Kind == style.DeclarationSyntax.Kind &&
                    candidate.DeclarationSyntax.FullSpan == style.DeclarationSyntax.FullSpan)
                {
                    styleIndex = index;
                    break;
                }
            }

            if (styleIndex < 0 || !TryGetAkcssModuleTypeName(module, out var moduleTypeName))
            {
                return false;
            }

            reference = moduleTypeName + ".Styles[" +
                styleIndex.ToString(CultureInfo.InvariantCulture) + "]";
            return true;
        }

        private bool TryGetAkcssModuleTypeName(
            IAkcssModuleSymbol module,
            out string typeName)
        {
            if (_akcssModuleTypeNames.TryGetValue(module.DeclaringSyntax, out typeName!))
            {
                return true;
            }

            if (string.IsNullOrWhiteSpace(module.Path))
            {
                typeName = string.Empty;
                return false;
            }

            foreach (var syntaxTree in _semanticModel.Compilation.GetAkcssSyntaxTreesByLogicalName(module.Path!))
            {
                if (!ReferenceEquals(syntaxTree.GetRootSyntax(), module.DeclaringSyntax.Root))
                {
                    continue;
                }

                var sourcePath = GetAkcssSourcePath(syntaxTree, _semanticModel.Compilation);
                typeName = AkcssGeneratedModuleNames.GetFullyQualifiedTypeName(sourcePath);
                return true;
            }

            typeName = string.Empty;
            return false;
        }

        private static string GetAkcssSourcePath(
            AkcssSyntaxTree syntaxTree,
            AkburaCompilation compilation)
        {
            if (TryGetProjectRelativePath(syntaxTree, compilation, out var sourcePath))
            {
                return sourcePath;
            }

            foreach (var reference in compilation.CompilationReferences)
            {
                if (TryGetProjectRelativePath(syntaxTree, reference.Compilation, out sourcePath))
                {
                    return sourcePath;
                }
            }

            var path = !string.IsNullOrWhiteSpace(syntaxTree.FilePath)
                ? syntaxTree.FilePath
                : syntaxTree.LogicalName;
            return AkcssGeneratedModuleNames.NormalizeSourcePath(path);
        }

        private static bool TryGetProjectRelativePath(
            AkcssSyntaxTree syntaxTree,
            AkburaCompilation compilation,
            out string sourcePath)
        {
            sourcePath = string.Empty;
            if (!compilation.AkcssSyntaxTrees.Contains(syntaxTree) ||
                string.IsNullOrWhiteSpace(compilation.ProjectDirectory) ||
                string.IsNullOrWhiteSpace(syntaxTree.FilePath))
            {
                return false;
            }

            var projectPath = Path.GetFullPath(compilation.ProjectDirectory)
                .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            var fullSourcePath = Path.GetFullPath(syntaxTree.FilePath);
            var projectPrefix = projectPath + Path.DirectorySeparatorChar;
            if (!fullSourcePath.StartsWith(projectPrefix, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            sourcePath = AkcssGeneratedModuleNames.NormalizeSourcePath(
                fullSourcePath.Substring(projectPrefix.Length));
            return true;
        }

        private static AkburaSyntax? GetAkcssModuleSyntax(AkburaSyntax syntax)
        {
            for (var current = syntax; current != null; current = current.Parent)
            {
                if (current is AkcssDocumentSyntax or InlineAkcssBlockSyntax)
                {
                    return current;
                }
            }

            return null;
        }

        private static string GetRuntimeUtilityType(ITailwindUtilitySymbol utility)
        {
            if (utility.Parameters.IsEmpty)
            {
                return "global::Akbura.Akcss.ZeroAkcssUtility";
            }

            return "global::Akbura.Akcss.AkcssUtility<" +
                string.Join(", ", utility.Parameters.Select(parameter => GetTypeName(parameter.Type.Symbol))) +
                ">";
        }

        private static string GetTailwindUtilityArgumentExpression(TailwindUtilityArgument argument)
        {
            if (!argument.ValueOperation.IsDefault && argument.ValueOperation.Syntax != null)
            {
                return argument.ValueOperation.Syntax.ToString();
            }

            if (argument.ConstantValue != null)
            {
                return FormatConstant(argument.ConstantValue, argument.Type.Symbol);
            }

            return argument.Text;
        }

        private static string GetTailwindConditionExpression(
            ITailwindUtilityAttributeOperation operation)
        {
            return !operation.ConditionOperation.IsDefault && operation.ConditionOperation.Syntax != null
                ? operation.ConditionOperation.Syntax.ToString()
                : operation.ConditionText ?? "false";
        }

        private void AppendPropertySetter(
            StringBuilder source,
            string target,
            IMarkupPropertySetterOperation operation,
            int indentation)
        {
            if (operation.Property == null)
            {
                return;
            }

            if (IsDataTypeDirective(operation.Syntax))
            {
                return;
            }

            if (operation.ConvertedValue is MarkupExtensionValue
                {
                    Binding: not null,
                } bindingExtension &&
                GetAvaloniaPropertyReference(operation.Property) is { } bindingProperty)
            {
                var binding = GetMarkupExtensionExpression(bindingExtension);
                var statement =
                    $"((global::Avalonia.AvaloniaObject){target}).Bind({bindingProperty}, {binding});";
                AppendLineDirective(
                    source,
                    indentation,
                    operation.Syntax,
                    statement,
                    Math.Max(0, statement.IndexOf(binding, StringComparison.Ordinal)));
                return;
            }

            var value = GetPropertyValue(operation);
            AppendPropertyWrite(source, target, operation.Property, value, indentation, operation.Syntax);
        }

        private static string? GetAvaloniaPropertyReference(AkburaPropertySymbol property)
        {
            return GetStaticMemberReference(property.WriteDefinition.Symbol) ??
                   GetStaticMemberReference(property.AvaloniaPropertyDefinition.Symbol);
        }

        private void AppendPropertyWrite(
            StringBuilder source,
            string target,
            AkburaPropertySymbol property,
            string value,
            int indentation,
            AkburaSyntax syntax)
        {
            string? statement = property.WriteKind switch
            {
                PropertyAccessKind.ClrProperty when property.WriteDefinition.Symbol is RoslynPropertySymbol clrProperty =>
                    $"(({GetTypeName(clrProperty.ContainingType)}){target}).{EscapeIdentifier(clrProperty.Name)} = {value};",
                PropertyAccessKind.AvaloniaProperty when (GetStaticMemberReference(property.WriteDefinition.Symbol) ??
                    GetStaticMemberReference(property.AvaloniaPropertyDefinition.Symbol)) is { } avaloniaProperty =>
                    $"((global::Avalonia.AvaloniaObject){target}).SetValue({avaloniaProperty}, {value});",
                PropertyAccessKind.AttachedAccessor when (property.WriteDefinition.Symbol as RoslynMethodSymbol ??
                    property.AttachedSetterDefinition.Symbol as RoslynMethodSymbol) is { } setter =>
                    $"{GetMethodReference(setter)}(({GetTypeName(setter.Parameters[0].Type)}){target}, {value});",
                PropertyAccessKind.Parameter => $"{target}.{EscapeIdentifier(property.Name)} = {value};",
                PropertyAccessKind.Command => $"{target}.{EscapeIdentifier(property.Name)} = {value};",
                _ => null,
            };

            if (statement != null)
            {
                AppendLineDirective(source, indentation, syntax, statement, Math.Max(0, statement.IndexOf(value, StringComparison.Ordinal)));
            }
        }

        private void AppendCollectionAdd(
            StringBuilder source,
            string target,
            AkburaPropertySymbol property,
            string value,
            int indentation,
            AkburaSyntax syntax)
        {
            if (property.Parameter is { } parameter &&
                TryGetContentCollection(parameter, out _))
            {
                var methodName = "__AkburaAddContent_" + SanitizeIdentifier(parameter.Name);
                var statement = $"{target}.{methodName}({value});";
                AppendLineDirective(
                    source,
                    indentation,
                    syntax,
                    statement,
                    statement.IndexOf(value, StringComparison.Ordinal));
                return;
            }

            if (property.ReadDefinition.Symbol is RoslynPropertySymbol clrProperty)
            {
                var statement = $"(({GetTypeName(clrProperty.ContainingType)}){target}).{EscapeIdentifier(clrProperty.Name)}.Add({value});";
                AppendLineDirective(source, indentation, syntax, statement, statement.IndexOf(value, StringComparison.Ordinal));
                return;
            }

            var propertyReference = GetStaticMemberReference(property.ReadDefinition.Symbol) ??
                                    GetStaticMemberReference(property.AvaloniaPropertyDefinition.Symbol);
            if (propertyReference != null)
            {
                var statement = $"((dynamic)((global::Avalonia.AvaloniaObject){target}).GetValue({propertyReference})!).Add({value});";
                AppendLineDirective(source, indentation, syntax, statement, statement.IndexOf(value, StringComparison.Ordinal));
            }
        }

        private void AppendRoutedEvent(
            StringBuilder source,
            ElementPlan element,
            IMarkupRoutedEventBindingOperation operation,
            int indentation)
        {
            var handler = GetHandlerExpression(operation);
            if (operation.Event.ClrEventDefinition.Symbol is RoslynEventSymbol clrEvent)
            {
                AppendLineDirective(
                    source,
                    indentation,
                    operation.Syntax,
                    $"(({GetTypeName(clrEvent.ContainingType)}){element.FieldName}).{EscapeIdentifier(clrEvent.Name)} += {handler};",
                    valueOffset: 0);
                return;
            }

            var routedEvent = GetStaticMemberReference(operation.Event.RoutedEventDefinition.Symbol);
            if (routedEvent != null)
            {
                AppendLineDirective(
                    source,
                    indentation,
                    operation.Syntax,
                    $"((global::Avalonia.Interactivity.Interactive){element.FieldName}).AddHandler({routedEvent}, {handler});",
                    valueOffset: 0);
            }
        }

        private void AppendCommandBinding(
            StringBuilder source,
            ElementPlan element,
            IMarkupCommandBindingOperation operation,
            int indentation)
        {
            if (operation.Property.CanWrite)
            {
                AppendPropertyWrite(
                    source,
                    element.FieldName,
                    operation.Property,
                    EscapeIdentifier(operation.Command.Name),
                    indentation,
                    operation.Syntax);
            }
        }

        private void AppendDescriptorArrays(StringBuilder source, int indentation)
        {
            AppendImmutableArray(source, indentation, RuntimeParameter, "s_parameters", _symbol.Parameters.Select(parameter => EscapeIdentifier(parameter.Name) + "Property"));
            AppendImmutableArray(source, indentation, RuntimeInjectService, "s_services", _symbol.InjectedServices.Select(service => EscapeIdentifier(service.Name) + "Property"));
            AppendImmutableArray(source, indentation, RuntimeCommandProperty, "s_commands", _symbol.Commands.Select(command => EscapeIdentifier(command.Name) + "Property"));

            if (_symbol.States.IsEmpty)
            {
                AppendImmutableArray(source, indentation, RuntimeState, "s_states", []);
            }
            else
            {
                AppendIndented(source, indentation).Append("private global::System.Collections.Immutable.ImmutableArray<")
                    .Append(RuntimeState).AppendLine("> __states;");
                AppendIndented(source, indentation).Append("private global::System.Collections.Immutable.ImmutableArray<")
                    .Append(RuntimeState).AppendLine("> __GetStates()");
                AppendIndentedLine(source, indentation, "{");
                AppendIndentedLine(source, indentation + 1, "if (__states.IsDefault)");
                AppendIndentedLine(source, indentation + 1, "{");
                AppendIndented(source, indentation + 2).Append("__states = global::System.Collections.Immutable.ImmutableArray.Create<")
                    .Append(RuntimeState).AppendLine(">");
                AppendIndentedLine(source, indentation + 2, "(");
                for (var index = 0; index < _symbol.States.Length; index++)
                {
                    AppendIndented(source, indentation + 3).Append("__State_")
                        .Append(SanitizeIdentifier(_symbol.States[index].Name))
                        .AppendLine(index == _symbol.States.Length - 1 ? string.Empty : ",");
                }

                AppendIndentedLine(source, indentation + 2, ");");
                AppendIndentedLine(source, indentation + 1, "}");
                AppendIndentedLine(source, indentation + 1, "return __states;");
                AppendIndentedLine(source, indentation, "}");
            }

            source.AppendLine();
            AppendIndentedLine(source, indentation, $"protected override global::System.Collections.Immutable.ImmutableArray<{RuntimeParameter}> GetParameters() => s_parameters;");
            AppendIndentedLine(source, indentation, $"protected override global::System.Collections.Immutable.ImmutableArray<{RuntimeCommandProperty}> GetCommands() => s_commands;");
            AppendIndentedLine(source, indentation, $"protected override global::System.Collections.Immutable.ImmutableArray<{RuntimeInjectService}> GetServices() => s_services;");
            AppendIndentedLine(source, indentation, $"protected override global::System.Collections.Immutable.ImmutableArray<{RuntimeState}> GetStates() => {(_symbol.States.IsEmpty ? "s_states" : "__GetStates()")};");
        }

        private static void AppendImmutableArray(
            StringBuilder source,
            int indentation,
            string elementType,
            string fieldName,
            IEnumerable<string> values)
        {
            var items = values.ToArray();
            AppendIndented(source, indentation).Append("private static readonly global::System.Collections.Immutable.ImmutableArray<")
                .Append(elementType).Append("> ").Append(fieldName).Append(" = ");
            if (items.Length == 0)
            {
                source.AppendLine("[];");
                return;
            }

            source.AppendLine();
            AppendIndentedLine(source, indentation + 1, "[");
            foreach (var item in items)
            {
                AppendIndented(source, indentation + 2).Append(item).AppendLine(",");
            }

            AppendIndentedLine(source, indentation + 1, "];");
        }

        private string GetPropertyValue(IMarkupPropertySetterOperation operation)
        {
            if (operation.ValueKind == MarkupAttributeValueKind.DynamicExpression &&
                operation.ValueSyntax is MarkupDynamicAttributeValueSyntax dynamicValue)
            {
                return dynamicValue.Expression.Expression.GetRawCSharpExpression()?.ToFullString().Trim() ?? "default";
            }

            if (operation.ConvertedValue is MarkupExtensionValue extension)
            {
                return GetMarkupExtensionExpression(extension);
            }

            if (operation.ConvertedValue is GridDefinitionListValue definitions)
            {
                return GetGridDefinitionsExpression(definitions, operation.Property?.Type.Symbol);
            }

            if (operation.ConvertedValue is MarkupLiteralValue convertedLiteral)
            {
                return GetConvertedLiteralExpression(convertedLiteral);
            }

            if (operation.ConvertedValue is CSharpSymbolDefinition definition &&
                GetStaticMemberReference(definition.Symbol) is { } member)
            {
                return member;
            }

            if (operation.ConvertedValue != null)
            {
                return FormatConstant(operation.ConvertedValue, operation.Property?.Type.Symbol);
            }

            if (operation.LiteralValue != null)
            {
                return ToStringLiteral(operation.LiteralValue);
            }

            return operation.ValueOperation.Syntax?.ToString() ?? "default";
        }

        private static string GetConvertedLiteralExpression(MarkupLiteralValue literal)
        {
            var type = GetTypeName(literal.TargetType.Symbol);
            var text = ToStringLiteral(literal.Text);
            return literal.ConverterKind switch
            {
                MarkupLiteralConverterKind.ParseMethod when literal.Converter.Symbol is RoslynMethodSymbol method =>
                    $"{GetMethodReference(method)}({text})",
                MarkupLiteralConverterKind.StringConstructor => $"new {type}({text})",
                MarkupLiteralConverterKind.TypeConverter when literal.Converter.Symbol is INamedTypeSymbol converterType =>
                    $"({type})new {GetTypeName(converterType)}().ConvertFromInvariantString({text})!",
                _ => $"({type}){text}",
            };
        }

        private string GetMarkupExtensionExpression(MarkupExtensionValue extension)
        {
            if (extension.Binding is { } binding)
            {
                return GetBindingExpression(extension, binding);
            }

            var type = GetTypeName(extension.ExtensionType.Symbol);
            var arguments = string.Join(", ", extension.Arguments.Select(GetMarkupExtensionArgument));
            var creation = new StringBuilder("new ").Append(type).Append('(').Append(arguments).Append(')');
            if (!extension.Properties.IsEmpty)
            {
                creation.Append(" { ");
                for (var index = 0; index < extension.Properties.Length; index++)
                {
                    if (index > 0)
                    {
                        creation.Append(", ");
                    }

                    var property = extension.Properties[index];
                    creation.Append(EscapeIdentifier(property.Name)).Append(" = ")
                        .Append(GetMarkupExtensionProperty(property));
                }

                creation.Append(" }");
            }

            if (extension.ProvideValueMethod.Symbol is RoslynMethodSymbol provideValue)
            {
                creation.Insert(0, '(').Append(')');
                creation.Append('.').Append(EscapeIdentifier(provideValue.Name)).Append('(');
                if (provideValue.Parameters.Length == 1)
                {
                    creation.Append("null!");
                }

                creation.Append(')');
            }

            return creation.ToString();
        }

        private string GetBindingExpression(MarkupExtensionValue extension, MarkupBindingValue binding)
        {
            if (binding.Kind == MarkupBindingKind.Compiled &&
                TryGetCompiledBindingPathExpression(binding, out var pathExpression))
            {
                var sourceType = GetTypeName(binding.SourceType.Symbol);
                var resultType = GetTypeName(binding.ResultType.Symbol);
                var compiledResult = new StringBuilder("global::Avalonia.Data.CompiledBinding.Create<")
                    .Append(sourceType).Append(", ").Append(resultType)
                    .Append(">(static __source => ").Append(pathExpression);
                AppendCompiledBindingArguments(compiledResult, extension.Properties);
                return compiledResult.Append(')').ToString();
            }

            var type = GetTypeName(binding.BindingType.Symbol);
            var result = new StringBuilder("new ").Append(type).Append('(')
                .Append(ToStringLiteral(binding.Path)).Append(')');
            if (!extension.Properties.IsEmpty)
            {
                result.Append(" { ");
                for (var index = 0; index < extension.Properties.Length; index++)
                {
                    if (index > 0)
                    {
                        result.Append(", ");
                    }

                    var property = extension.Properties[index];
                    result.Append(EscapeIdentifier(property.Name)).Append(" = ")
                        .Append(GetMarkupExtensionProperty(property));
                }

                result.Append(" }");
            }

            return result.ToString();
        }

        private static bool TryGetCompiledBindingPathExpression(
            MarkupBindingValue binding,
            out string expression)
        {
            var result = new StringBuilder("__source");
            var pendingLogicalNot = 0;
            foreach (var element in binding.PathElements)
            {
                switch (element.Kind)
                {
                    case MarkupBindingPathElementKind.Property:
                    case MarkupBindingPathElementKind.Field:
                        result.Append('.').Append(EscapeIdentifier(element.Symbol.Name ?? element.Text));
                        break;
                    case MarkupBindingPathElementKind.Indexer:
                        result.Append('[');
                        var argumentCount = element.BoundArguments.IsEmpty
                            ? element.Arguments.Length
                            : element.BoundArguments.Length;
                        for (var index = 0; index < argumentCount; index++)
                        {
                            if (index > 0)
                            {
                                result.Append(", ");
                            }

                            if (element.BoundArguments.IsEmpty)
                            {
                                result.Append(element.Arguments[index]);
                            }
                            else
                            {
                                var argument = element.BoundArguments[index];
                                result.Append(!argument.Operation.IsDefault
                                    ? argument.Operation.Syntax?.ToString() ?? argument.Text
                                    : argument.ConvertedValue != null
                                        ? FormatConstant(argument.ConvertedValue, argument.Type.Symbol)
                                        : argument.Text);
                            }
                        }

                        result.Append(']');
                        break;
                    case MarkupBindingPathElementKind.TypeCast when element.Type.Symbol != null:
                        result.Insert(0, "((" + GetTypeName(element.Type.Symbol) + ")").Append(')');
                        break;
                    case MarkupBindingPathElementKind.Not:
                        pendingLogicalNot++;
                        break;
                    default:
                        expression = string.Empty;
                        return false;
                }
            }

            if (pendingLogicalNot > 0)
            {
                result.Insert(0, new string('!', pendingLogicalNot));
            }

            expression = result.ToString();
            return true;
        }

        private void AppendCompiledBindingArguments(
            StringBuilder result,
            ImmutableArray<MarkupExtensionPropertyValue> properties)
        {
            foreach (var property in properties)
            {
                var parameterName = property.Name switch
                {
                    "Converter" => "converter",
                    "ConverterCulture" => "converterCulture",
                    "ConverterParameter" => "converterParameter",
                    "Delay" => "delay",
                    "FallbackValue" => "fallbackValue",
                    "Mode" => "mode",
                    "Priority" => "priority",
                    "Source" => "source",
                    "StringFormat" => "stringFormat",
                    "TargetNullValue" => "targetNullValue",
                    "UpdateSourceTrigger" => "updateSourceTrigger",
                    _ => null,
                };
                if (parameterName != null)
                {
                    result.Append(", ").Append(parameterName).Append(": ")
                        .Append(GetMarkupExtensionProperty(property));
                }
            }
        }

        private string GetMarkupExtensionArgument(MarkupExtensionArgumentValue argument)
        {
            if (argument.NestedValue != null)
            {
                return GetMarkupExtensionExpression(argument.NestedValue);
            }

            if (!argument.Operation.IsDefault)
            {
                return argument.Operation.Syntax?.ToString() ?? argument.Text;
            }

            return argument.ConvertedValue != null
                ? FormatConstant(argument.ConvertedValue, argument.Type.Symbol)
                : ToStringLiteral(argument.Text.Trim('\'', '"'));
        }

        private string GetMarkupExtensionProperty(MarkupExtensionPropertyValue property)
        {
            if (property.NestedValue != null)
            {
                return GetMarkupExtensionExpression(property.NestedValue);
            }

            if (property.ConvertedValue != null)
            {
                return FormatConstant(property.ConvertedValue, property.Type.Symbol);
            }

            if (!property.Operation.IsDefault)
            {
                return property.Operation.Syntax?.ToString() ?? property.Value;
            }

            return ToStringLiteral(property.Value.Trim('\'', '"'));
        }

        private static string GetGridDefinitionsExpression(
            GridDefinitionListValue value,
            Microsoft.CodeAnalysis.ISymbol? targetType)
        {
            var isRows = targetType?.Name == "RowDefinitions";
            var collectionType = isRows
                ? "global::Avalonia.Controls.RowDefinitions"
                : "global::Avalonia.Controls.ColumnDefinitions";
            var itemType = isRows
                ? "global::Avalonia.Controls.RowDefinition"
                : "global::Avalonia.Controls.ColumnDefinition";
            var lengthProperty = isRows ? "Height" : "Width";
            var minProperty = isRows ? "MinHeight" : "MinWidth";
            var maxProperty = isRows ? "MaxHeight" : "MaxWidth";
            var result = new StringBuilder("new ").Append(collectionType).Append(" { ");
            for (var index = 0; index < value.Definitions.Length; index++)
            {
                if (index > 0)
                {
                    result.Append(", ");
                }

                var definition = value.Definitions[index];
                result.Append("new ").Append(itemType).Append(" { ")
                    .Append(lengthProperty).Append(" = ").Append(GetGridLengthExpression(definition.Length));
                if (definition.Min is { } min)
                {
                    result.Append(", ").Append(minProperty).Append(" = ").Append(FormatDouble(min));
                }

                if (definition.Max is { } max)
                {
                    result.Append(", ").Append(maxProperty).Append(" = ").Append(FormatDouble(max));
                }

                result.Append(" }");
            }

            return result.Append(" }").ToString();
        }

        private static string GetGridLengthExpression(GridDefinitionLengthValue length)
        {
            var unit = length.UnitType switch
            {
                GridDefinitionUnitType.Auto => "global::Avalonia.Controls.GridUnitType.Auto",
                GridDefinitionUnitType.Star => "global::Avalonia.Controls.GridUnitType.Star",
                _ => "global::Avalonia.Controls.GridUnitType.Pixel",
            };
            return $"new global::Avalonia.Controls.GridLength({FormatDouble(length.Value)}, {unit})";
        }

        private string? GetContentExpression(IMarkupContentOperation operation)
        {
            if (!operation.IsSynthesizedString)
            {
                return operation.LiteralValue == null ? null : ToStringLiteral(operation.LiteralValue);
            }

            var result = new StringBuilder("$\"");
            foreach (var content in operation.Syntax.Body)
            {
                switch (content)
                {
                    case MarkupTextLiteralSyntax text:
                        result.Append(EscapeInterpolatedText(text.ToFullString()));
                        break;
                    case MarkupInlineExpressionSyntax expression:
                        result.Append('{').Append(GetExpression(expression.Expression.Expression)).Append('}');
                        break;
                }
            }

            return result.Append('"').ToString();
        }

        private static string GetHandlerExpression(IMarkupRoutedEventBindingOperation operation)
        {
            var expression = operation.ValueSyntax is MarkupDynamicAttributeValueSyntax dynamicValue
                ? dynamicValue.Expression.Expression.GetRawCSharpExpression()?.ToFullString().Trim()
                : null;
            if (string.IsNullOrWhiteSpace(expression))
            {
                return "static (_, _) => { }";
            }

            if (operation.HandlerKind is MarkupCommandHandlerKind.Lambda or MarkupCommandHandlerKind.DirectReference)
            {
                return expression!;
            }

            var parameters = operation.HandlerParameterCount switch
            {
                0 => "()",
                1 => "__argument",
                _ => "(__sender, __args)",
            };
            var asyncPrefix = operation.IsAsync ? "async " : string.Empty;
            return $"{asyncPrefix}{parameters} => {{ {expression}; }}";
        }

        private static bool IsFirstUpdateValue(IMarkupPropertySetterOperation operation)
        {
            return operation.ValueKind is MarkupAttributeValueKind.Literal or MarkupAttributeValueKind.MarkupExtension;
        }

        private static bool IsDataTypeDirective(MarkupAttributeSyntax syntax)
        {
            return syntax is MarkupAttachedPropertyAttributeSyntax attached &&
                   attached.ToFullString().TrimStart().StartsWith("x.DataType", StringComparison.Ordinal);
        }

        private void AppendLineDirective(
            StringBuilder source,
            int indentation,
            AkburaSyntax syntax,
            string statement,
            int valueOffset)
        {
            if (_sourceMap.TryGetLineDirective(syntax, out var span, out var path))
            {
                var generatedOffset = indentation * 4 + Math.Max(0, valueOffset);
                AppendIndented(source, indentation)
                    .Append("#line (").Append(span.Start.Line + 1).Append(',').Append(span.Start.Character + 1)
                    .Append(")-(").Append(span.End.Line + 1).Append(',').Append(span.End.Character + 1)
                    .Append(") ").Append(generatedOffset).Append(' ').Append(ToLineDirectivePath(path)).AppendLine();
                AppendIndentedLine(source, indentation, statement);
                AppendIndentedLine(source, indentation, "#line default");
                return;
            }

            AppendIndentedLine(source, indentation, statement);
        }

        private string GetBaseTypeName()
        {
            return _symbol.BaseType.Symbol is ITypeSymbol type
                ? GetTypeName(type)
                : "global::Akbura.AkburaControl";
        }

        private static string GetCommandType(ICommandSymbol command)
        {
            if (command.Parameters.IsEmpty)
            {
                return "global::Akbura.IAkburaCommand";
            }

            var result = new StringBuilder("global::Akbura.IAkburaCommand<");
            foreach (var parameter in command.Parameters)
            {
                result.Append(GetTypeName(parameter.Type.Symbol)).Append(", ");
            }

            result.Append(GetTypeName(command.ResultType.Symbol)).Append('>');
            return result.ToString();
        }

        private static string GetExpression(CSharpExpressionSyntax? syntax)
        {
            return syntax?.GetRawCSharpExpression()?.ToFullString().Trim() ?? "default";
        }

        private static string GetComponentTypeName(IMarkupComponentSymbol symbol)
        {
            if (symbol.ComponentType != null)
            {
                return GetTypeName(symbol.ComponentType);
            }

            if (symbol.AkburaComponent != null)
            {
                var metadataName = symbol.AkburaComponent.MetadataName;
                return metadataName.StartsWith("global::", StringComparison.Ordinal)
                    ? metadataName
                    : "global::" + metadataName;
            }

            return "global::Avalonia.Controls.Control";
        }

        private static string GetAccessibility(ImmutableArray<INamedTypeSymbol> partialTypes)
        {
            if (!partialTypes.IsDefaultOrEmpty)
            {
                return partialTypes[0].DeclaredAccessibility switch
                {
                    Accessibility.Public => "public",
                    Accessibility.Private => "private",
                    Accessibility.Protected => "protected",
                    Accessibility.ProtectedAndInternal => "private protected",
                    Accessibility.ProtectedOrInternal => "protected internal",
                    _ => "internal",
                };
            }

            return "public";
        }
    }

    private static bool IsContentParameter(IParamSymbol parameter)
    {
        return string.Equals(parameter.Name, "Content", StringComparison.Ordinal);
    }

    private static bool TryGetContentCollection(
        IParamSymbol parameter,
        out ContentCollectionInfo collection)
    {
        collection = default;
        if (!IsContentParameter(parameter) ||
            parameter.BindingKind != ParamBindingKind.Default ||
            parameter.Type.Symbol is not INamedTypeSymbol namedType)
        {
            return false;
        }

        var original = namedType.OriginalDefinition;
        var namespaceName = original.ContainingNamespace.ToDisplayString();
        var propertyType = GetTypeName(namedType);
        if (original.Name == "IList" &&
            original.Arity == 0 &&
            namespaceName == "System.Collections")
        {
            collection = new ContentCollectionInfo(
                propertyType,
                "global::System.Object",
                "global::System.Collections.ObjectModel.ObservableCollection<global::System.Object>",
                ObservesChanges: true);
            return true;
        }

        if (original.Arity != 1)
        {
            return false;
        }

        var elementType = GetTypeName(namedType.TypeArguments[0]);
        if (original.Name == "IList" &&
            namespaceName == "System.Collections.Generic")
        {
            collection = new ContentCollectionInfo(
                propertyType,
                elementType,
                $"global::System.Collections.ObjectModel.ObservableCollection<{elementType}>",
                ObservesChanges: true);
            return true;
        }

        if (original.Name == "ObservableCollection" &&
            namespaceName == "System.Collections.ObjectModel")
        {
            collection = new ContentCollectionInfo(
                propertyType,
                elementType,
                propertyType,
                ObservesChanges: true);
            return true;
        }

        if (original.Name == "List" &&
            namespaceName == "System.Collections.Generic")
        {
            collection = new ContentCollectionInfo(
                propertyType,
                elementType,
                propertyType,
                ObservesChanges: false);
            return true;
        }

        return false;
    }

    private readonly record struct ContentCollectionInfo(
        string PropertyType,
        string ElementType,
        string BackingType,
        bool ObservesChanges);

    private sealed class ElementPlan
    {
        public ElementPlan(
            int id,
            MarkupElementSyntax syntax,
            IMarkupComponentSymbol symbol,
            string fieldName,
            string typeName,
            IMarkupNameAssignmentOperation? nameOperation,
            MarkupElementSyntax? templateOwner)
        {
            Id = id;
            Syntax = syntax;
            Symbol = symbol;
            FieldName = fieldName;
            TypeName = typeName;
            NameOperation = nameOperation;
            TemplateOwner = templateOwner;
        }

        public int Id { get; }

        public MarkupElementSyntax Syntax { get; }

        public IMarkupComponentSymbol Symbol { get; }

        public string FieldName { get; }

        public string TypeName { get; }

        public IMarkupNameAssignmentOperation? NameOperation { get; }

        public MarkupElementSyntax? TemplateOwner { get; }

        public List<ElementPlan> Children { get; } = [];

        public List<PropertyElementPlan> PropertyElements { get; } = [];
    }

    private sealed class PropertyElementPlan
    {
        public PropertyElementPlan(
            int id,
            ElementPlan owner,
            MarkupElementSyntax syntax,
            AkburaPropertySymbol property,
            IMarkupContentOperation operation)
        {
            Id = id;
            Owner = owner;
            Syntax = syntax;
            Property = property;
            Operation = operation;
        }

        public int Id { get; }

        public ElementPlan Owner { get; }

        public MarkupElementSyntax Syntax { get; }

        public AkburaPropertySymbol Property { get; }

        public IMarkupContentOperation Operation { get; }

        public List<ElementPlan> Children { get; } = [];
    }

    private static void AppendUsingDirectives(StringBuilder source, AkburaDocumentSyntax document)
    {
        foreach (var usingDirective in document.Members.OfType<UsingDirectiveSyntax>())
        {
            var text = usingDirective.ToFullString().Trim();
            if (text.Length > 0)
            {
                source.AppendLine(text);
            }
        }
    }

    private static string? GetStaticMemberReference(Microsoft.CodeAnalysis.ISymbol? symbol)
    {
        return symbol switch
        {
            RoslynFieldSymbol { IsStatic: true } field =>
                $"{GetTypeName(field.ContainingType)}.{EscapeIdentifier(field.Name)}",
            RoslynPropertySymbol { IsStatic: true } property =>
                $"{GetTypeName(property.ContainingType)}.{EscapeIdentifier(property.Name)}",
            _ => null,
        };
    }

    private static string GetMethodReference(RoslynMethodSymbol method)
    {
        return $"{GetTypeName(method.ContainingType)}.{EscapeIdentifier(method.Name)}";
    }

    private static string GetTypeName(Microsoft.CodeAnalysis.ISymbol? symbol)
    {
        return symbol is ITypeSymbol type
            ? type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            : "global::System.Object";
    }

    private static string FormatConstant(object? value, Microsoft.CodeAnalysis.ISymbol? targetType)
    {
        if (value == null)
        {
            return "null";
        }

        if (targetType is INamedTypeSymbol { TypeKind: TypeKind.Enum } enumType)
        {
            return $"({GetTypeName(enumType)}){Convert.ToInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture)}";
        }

        return value switch
        {
            string text => ToStringLiteral(text),
            char character => SymbolDisplay.FormatLiteral(character, quote: true),
            bool boolean => boolean ? "true" : "false",
            byte number => number.ToString(CultureInfo.InvariantCulture),
            sbyte number => number.ToString(CultureInfo.InvariantCulture),
            short number => number.ToString(CultureInfo.InvariantCulture),
            ushort number => number.ToString(CultureInfo.InvariantCulture),
            int number => number.ToString(CultureInfo.InvariantCulture),
            uint number => number.ToString(CultureInfo.InvariantCulture) + "U",
            long number => number.ToString(CultureInfo.InvariantCulture) + "L",
            ulong number => number.ToString(CultureInfo.InvariantCulture) + "UL",
            float number => number.ToString("R", CultureInfo.InvariantCulture) + "F",
            double number => FormatDouble(number),
            decimal number => number.ToString(CultureInfo.InvariantCulture) + "M",
            _ => ToStringLiteral(value.ToString() ?? string.Empty),
        };
    }

    private static string FormatDouble(double value)
    {
        if (double.IsNaN(value))
        {
            return "global::System.Double.NaN";
        }

        if (double.IsPositiveInfinity(value))
        {
            return "global::System.Double.PositiveInfinity";
        }

        if (double.IsNegativeInfinity(value))
        {
            return "global::System.Double.NegativeInfinity";
        }

        return value.ToString("R", CultureInfo.InvariantCulture);
    }

    private static string EscapeInterpolatedText(string text)
    {
        return text
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("{", "{{")
            .Replace("}", "}}");
    }

    private static string EscapeIdentifier(string name)
    {
        return CSharpSyntaxFacts.GetKeywordKind(name) != CSharpSyntaxKind.None ||
               CSharpSyntaxFacts.GetContextualKeywordKind(name) != CSharpSyntaxKind.None
            ? "@" + name
            : name;
    }

    private static string SanitizeIdentifier(string value)
    {
        var result = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            result.Append(char.IsLetterOrDigit(character) || character == '_'
                ? character
                : '_');
        }

        return result.Length == 0 ? "value" : result.ToString();
    }

    private static string SanitizeHintPart(string value)
    {
        var result = new StringBuilder(Math.Min(value.Length, 64));
        foreach (var character in value)
        {
            if (result.Length == 64)
            {
                break;
            }

            result.Append(char.IsLetterOrDigit(character) || character is '.' or '_'
                ? character
                : '_');
        }

        return result.Length == 0 ? "component" : result.ToString();
    }

    private static string ToStringLiteral(string value)
    {
        return SymbolDisplay.FormatLiteral(value, quote: true);
    }

    private static string ToLineDirectivePath(string path)
    {
        return "\"" + path + "\"";
    }

    private static StringBuilder AppendIndented(StringBuilder source, int indentation)
    {
        return source.Append(' ', indentation * 4);
    }

    private static void AppendIndentedLine(StringBuilder source, int indentation, string text)
    {
        source.Append(' ', indentation * 4).AppendLine(text);
    }
}
