using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Editing;
using Microsoft.CodeAnalysis.Text;
using System.Security.Cryptography;
using System.Text;

namespace Akbura.Workspaces;

internal static class MetadataSourceDefinition
{
    private static readonly AdhocWorkspace s_workspace = new();

    public static bool TryCreate(
        TextSpan sourceSpan,
        ISymbol symbol,
        out AkburaDefinition definition)
    {
        symbol = symbol.OriginalDefinition;

        try
        {
            var annotation = new SyntaxAnnotation();
            var generator = SyntaxGenerator.GetGenerator(
                s_workspace,
                LanguageNames.CSharp);
            var declaration = CreateDeclaration(
                generator,
                symbol,
                annotation,
                out var topLevelType);

            if (declaration == null || topLevelType == null)
            {
                definition = null!;
                return false;
            }

            var containingNamespace =
                topLevelType.ContainingNamespace;
            if (containingNamespace is
                { IsGlobalNamespace: false })
            {
                declaration = generator.NamespaceDeclaration(
                    generator.DottedName(
                        containingNamespace.ToDisplayString()),
                    declaration);
            }

            declaration = generator.CompilationUnit(declaration)
                .NormalizeWhitespace();

            var targetNode = declaration
                .GetAnnotatedNodes(annotation)
                .FirstOrDefault();
            if (targetNode == null)
            {
                definition = null!;
                return false;
            }

            var assemblyName =
                symbol.ContainingAssembly?.Identity.ToString() ??
                "metadata";
            var header =
                "// Metadata view generated by Akbura.\r\n" +
                "// Assembly: " + assemblyName + "\r\n\r\n";
            var text = SourceText.From(
                header + declaration.ToFullString(),
                Encoding.UTF8);
            var targetSpan = GetNameSpan(
                targetNode,
                symbol.Name);
            targetSpan = new TextSpan(
                targetSpan.Start + header.Length,
                targetSpan.Length);

            var fileName = SanitizeFileName(
                topLevelType.Name) + ".metadata.cs";
            var cacheKey =
                assemblyName + "|" +
                topLevelType.ToDisplayString(
                    SymbolDisplayFormat.FullyQualifiedFormat);
            var path = CreateCachePath(
                "CSharp",
                cacheKey,
                fileName);

            definition = new AkburaDefinition(
                sourceSpan,
                path,
                text.Lines.GetLinePositionSpan(targetSpan),
                text);
            return true;
        }
        catch (ArgumentException)
        {
            definition = null!;
            return false;
        }
        catch (InvalidOperationException)
        {
            definition = null!;
            return false;
        }
        catch (NotSupportedException)
        {
            definition = null!;
            return false;
        }
    }

    public static string CreateCachePath(
        string category,
        string cacheKey,
        string relativePath)
    {
        var safeCategory = SanitizeFileName(category);
        var safeRelativePath = string.Join(
            Path.DirectorySeparatorChar.ToString(),
            relativePath
                .Replace('\\', '/')
                .Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(SanitizeFileName));

        if (safeRelativePath.Length == 0)
        {
            safeRelativePath = "source.txt";
        }

        return Path.Combine(
            Path.GetTempPath(),
            "Akbura",
            "Metadata",
            safeCategory,
            GetStableHash(cacheKey),
            safeRelativePath);
    }

    private static SyntaxNode? CreateDeclaration(
        SyntaxGenerator generator,
        ISymbol symbol,
        SyntaxAnnotation annotation,
        out INamedTypeSymbol? topLevelType)
    {
        if (symbol is INamedTypeSymbol namedType)
        {
            topLevelType = GetTopLevelType(namedType);
            var typeDeclaration = generator.Declaration(namedType)
                .WithAdditionalAnnotations(annotation);
            return WrapInContainingTypes(
                generator,
                typeDeclaration,
                namedType.ContainingType);
        }

        var containingType = symbol.ContainingType;
        if (containingType == null)
        {
            topLevelType = null;
            return null;
        }

        var member = generator.Declaration(symbol)
            .WithAdditionalAnnotations(annotation);
        var declaration = generator.AddMembers(
            generator.Declaration(containingType),
            member);
        declaration = WrapInContainingTypes(
            generator,
            declaration,
            containingType.ContainingType);
        topLevelType = GetTopLevelType(containingType);
        return declaration;
    }

    private static SyntaxNode WrapInContainingTypes(
        SyntaxGenerator generator,
        SyntaxNode declaration,
        INamedTypeSymbol? containingType)
    {
        for (var current = containingType;
             current != null;
             current = current.ContainingType)
        {
            declaration = generator.AddMembers(
                generator.Declaration(current),
                declaration);
        }

        return declaration;
    }

    private static INamedTypeSymbol GetTopLevelType(
        INamedTypeSymbol type)
    {
        while (type.ContainingType != null)
        {
            type = type.ContainingType;
        }

        return type;
    }

    private static TextSpan GetNameSpan(
        SyntaxNode declaration,
        string name)
    {
        foreach (var token in declaration.DescendantTokens())
        {
            if (string.Equals(
                    token.ValueText,
                    name,
                    StringComparison.Ordinal))
            {
                return token.Span;
            }
        }

        return declaration.Span;
    }

    private static string SanitizeFileName(string value)
    {
        if (string.IsNullOrWhiteSpace(value) ||
            value == "." ||
            value == "..")
        {
            return "_";
        }

        var invalidCharacters =
            Path.GetInvalidFileNameChars();
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            builder.Append(
                invalidCharacters.Contains(character)
                    ? '_'
                    : character);
        }

        return builder.ToString();
    }

    private static string GetStableHash(string value)
    {
        using var algorithm = SHA256.Create();
        var bytes = algorithm.ComputeHash(
            Encoding.UTF8.GetBytes(value));
        var builder = new StringBuilder(16);
        for (var index = 0; index < 8; index++)
        {
            builder.Append(bytes[index].ToString("x2"));
        }

        return builder.ToString();
    }
}
