<Project>
	<PropertyGroup>
		<Configurations>Debug;Release;DebugStats;ReleaseStats</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'DebugStats'">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>portable</DebugType>
		<Optimize>false</Optimize>
		<DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'ReleaseStats'">
		<DebugSymbols>false</DebugSymbols>
		<DebugType>portable</DebugType>
		<Optimize>true</Optimize>
		<DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
	</PropertyGroup>
</Project>
