using Avalonia.Markup.Xaml;
using Avalonia.Markup.Xaml.XamlIl.Runtime;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace Akbura.Markup;

/// <summary>
/// Provides runtime XAML context to markup extensions generated by Akbura.
/// </summary>
internal sealed class AkburaMarkupServiceProvider :
    IServiceProvider,
    IProvideValueTarget,
    IRootObjectProvider,
    IUriContext,
    IXamlTypeResolver,
    IAvaloniaXamlIlEagerParentStackProvider
{
    private readonly IServiceProvider? _fallbackServiceProvider;
    private readonly IReadOnlyDictionary<string, Type>? _knownTypes;

    public AkburaMarkupServiceProvider(
        object targetObject,
        object targetProperty,
        object rootObject,
        object intermediateRootObject,
        Uri baseUri,
        IReadOnlyList<object> directParentsStack,
        IAvaloniaXamlIlEagerParentStackProvider? parentProvider = null,
        IServiceProvider? fallbackServiceProvider = null,
        IReadOnlyDictionary<string, Type>? knownTypes = null)
    {
        ArgumentNullException.ThrowIfNull(targetObject);
        ArgumentNullException.ThrowIfNull(targetProperty);
        ArgumentNullException.ThrowIfNull(rootObject);
        ArgumentNullException.ThrowIfNull(intermediateRootObject);
        ArgumentNullException.ThrowIfNull(baseUri);
        ArgumentNullException.ThrowIfNull(directParentsStack);

        TargetObject = targetObject;
        TargetProperty = targetProperty;

        RootObject = rootObject;
        IntermediateRootObject = intermediateRootObject;

        BaseUri = baseUri;

        DirectParentsStack = directParentsStack;
        ParentProvider = parentProvider;

        _fallbackServiceProvider = fallbackServiceProvider;
        _knownTypes = knownTypes;
    }

    public object TargetObject { get; }

    public object TargetProperty { get; }

    public object RootObject { get; }

    public object IntermediateRootObject { get; }

    public Uri BaseUri { get; set; }

    /// <summary>
    /// Reverse order:
    /// the most distant direct parent is first,
    /// the target object is last.
    /// </summary>
    public IReadOnlyList<object> DirectParentsStack { get; }

    public IAvaloniaXamlIlEagerParentStackProvider? ParentProvider { get; }

    /// <summary>
    /// Normal order:
    /// target object first, distant ancestors last.
    /// </summary>
    public IEnumerable<object> Parents
    {
        get
        {
            for (var index = DirectParentsStack.Count - 1; index >= 0; index--)
            {
                yield return DirectParentsStack[index];
            }

            if (ParentProvider is not null)
            {
                foreach (var parent in ParentProvider.Parents)
                {
                    yield return parent;
                }
            }
        }
    }

    public object? GetService(Type serviceType)
    {
        ArgumentNullException.ThrowIfNull(serviceType);

        if (serviceType == typeof(IServiceProvider))
        {
            return this;
        }

        if (serviceType == typeof(IProvideValueTarget))
        {
            return this;
        }

        if (serviceType == typeof(IRootObjectProvider))
        {
            return this;
        }

        if (serviceType == typeof(IUriContext))
        {
            return this;
        }

        if (serviceType == typeof(IXamlTypeResolver))
        {
            return this;
        }

        if (serviceType == typeof(IAvaloniaXamlIlParentStackProvider) ||
            serviceType == typeof(IAvaloniaXamlIlEagerParentStackProvider))
        {
            return this;
        }

        return _fallbackServiceProvider?.GetService(serviceType);
    }

    [RequiresUnreferencedCode(
        "Runtime XAML type resolution may require types that cannot be determined statically.")]
    public Type Resolve(string qualifiedTypeName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(qualifiedTypeName);

        if (_knownTypes is not null &&
            _knownTypes.TryGetValue(qualifiedTypeName, out var knownType))
        {
            return knownType;
        }

        var clrTypeName = qualifiedTypeName.StartsWith(
            "global::",
            StringComparison.Ordinal)
            ? qualifiedTypeName["global::".Length..]
            : qualifiedTypeName;

        // Prefixed XAML names such as local:MyControl should eventually
        // come from a generated namespace/type map.
        if (clrTypeName.Contains(':'))
        {
            throw new ArgumentException(
                $"XAML type prefix in '{qualifiedTypeName}' is not registered.",
                nameof(qualifiedTypeName));
        }

        var type = Type.GetType(
            clrTypeName,
            throwOnError: false,
            ignoreCase: false);

        if (type is not null)
        {
            return type;
        }

        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            type = assembly.GetType(
                clrTypeName,
                throwOnError: false,
                ignoreCase: false);

            if (type is not null)
            {
                return type;
            }
        }

        throw new ArgumentException(
            $"Unable to resolve XAML type '{qualifiedTypeName}'.",
            nameof(qualifiedTypeName));
    }
}