//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akbura {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AkburaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AkburaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Akbura.AkburaResources", typeof(AkburaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;)&apos; expected..
        /// </summary>
        internal static string ERR_CloseParenExpected {
            get {
                return ResourceManager.GetString("ERR_CloseParenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating-point constant is too large for &apos;{0}&apos;..
        /// </summary>
        internal static string ERR_FloatOverflow {
            get {
                return ResourceManager.GetString("ERR_FloatOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier expected..
        /// </summary>
        internal static string ERR_IdentifierExpected {
            get {
                return ResourceManager.GetString("ERR_IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier expected; &apos;{0}&apos; is a keyword..
        /// </summary>
        internal static string ERR_IdentifierExpectedKW {
            get {
                return ResourceManager.GetString("ERR_IdentifierExpectedKW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal escape sequence at position {0} (length {1})..
        /// </summary>
        internal static string ERR_IllegalEscape {
            get {
                return ResourceManager.GetString("ERR_IllegalEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer literal is too large..
        /// </summary>
        internal static string ERR_IntOverflow {
            get {
                return ResourceManager.GetString("ERR_IntOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number literal at position {0} (length {1})..
        /// </summary>
        internal static string ERR_InvalidNumber {
            get {
                return ResourceManager.GetString("ERR_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number literal..
        /// </summary>
        internal static string ERR_InvalidNumber_WithoutPosition {
            get {
                return ResourceManager.GetString("ERR_InvalidNumber_WithoutPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid real literal..
        /// </summary>
        internal static string ERR_InvalidReal {
            get {
                return ResourceManager.GetString("ERR_InvalidReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{&apos; expected..
        /// </summary>
        internal static string ERR_LbraceExpected {
            get {
                return ResourceManager.GetString("ERR_LbraceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated multi-line comment..
        /// </summary>
        internal static string ERR_OpenEndedComment {
            get {
                return ResourceManager.GetString("ERR_OpenEndedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;}&apos; expected..
        /// </summary>
        internal static string ERR_RbraceExpected {
            get {
                return ResourceManager.GetString("ERR_RbraceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;;&apos; expected..
        /// </summary>
        internal static string ERR_SemicolonExpected {
            get {
                return ResourceManager.GetString("ERR_SemicolonExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error; &apos;{0}&apos; expected..
        /// </summary>
        internal static string ERR_SyntaxError {
            get {
                return ResourceManager.GetString("ERR_SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character: {0}.
        /// </summary>
        internal static string ERR_UnexpectedCharacter {
            get {
                return ResourceManager.GetString("ERR_UnexpectedCharacter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markup child &apos;{0}&apos; is not assignable to expected content type &apos;{1}&apos;..
        /// </summary>
        internal static string AKBURA_SEMANTIC_InvalidMarkupChild {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_InvalidMarkupChild", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AKCSS color value &apos;{0}&apos; is not valid for property &apos;{1}&apos;..
        /// </summary>
        internal static string AKBURA_SEMANTIC_AkcssInvalidColor {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_AkcssInvalidColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AKCSS thickness tuple &apos;{0}&apos; is not valid for property &apos;{1}&apos;..
        /// </summary>
        internal static string AKBURA_SEMANTIC_AkcssInvalidThickness {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_AkcssInvalidThickness", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AKCSS property &apos;{0}&apos; was not found on style target &apos;{1}&apos;..
        /// </summary>
        internal static string AKBURA_SEMANTIC_AkcssPropertyNotFound {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_AkcssPropertyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; was not found on component &apos;{1}&apos;..
        /// </summary>
        internal static string AKBURA_SEMANTIC_MarkupPropertyNotFound {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_MarkupPropertyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markup attribute value for &apos;{0}&apos; cannot be converted from &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string AKBURA_SEMANTIC_MarkupAttributeValueCannotConvert {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_MarkupAttributeValueCannotConvert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markup attribute binding &apos;{0}&apos; is not allowed for parameter &apos;{1}&apos; declared as &apos;{2}&apos;..
        /// </summary>
        internal static string AKBURA_SEMANTIC_MarkupAttributeBindingNotAllowed {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_MarkupAttributeBindingNotAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markup property '{0}' does not provide the {1} required by '{2}' binding..
        /// </summary>
        internal static string AKBURA_SEMANTIC_MarkupPropertyAccessNotSupported {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_MarkupPropertyAccessNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markup property &apos;{0}&apos; already has a setter on this element..
        /// </summary>
        internal static string AKBURA_SEMANTIC_MarkupDuplicatePropertySetter {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_MarkupDuplicatePropertySetter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markup event &apos;{0}&apos; does not support &apos;{1}&apos; binding. Use a normal event handler expression..
        /// </summary>
        internal static string AKBURA_SEMANTIC_MarkupEventBindingNotAllowed {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_MarkupEventBindingNotAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markup event &apos;{0}&apos; expects handler &apos;{1}&apos;, but received &apos;{2}&apos;..
        /// </summary>
        internal static string AKBURA_SEMANTIC_MarkupEventHandlerSignatureMismatch {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_MarkupEventHandlerSignatureMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tailwind utility &apos;{0}&apos; was not found for component &apos;{1}&apos;..
        /// </summary>
        internal static string AKBURA_SEMANTIC_TailwindUtilityNotFound {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_TailwindUtilityNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tailwind utility &apos;{0}&apos; is ambiguous for component &apos;{1}&apos;..
        /// </summary>
        internal static string AKBURA_SEMANTIC_TailwindUtilityAmbiguous {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_TailwindUtilityAmbiguous", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tailwind utility &apos;{0}&apos; expects {1} argument(s), but {2} were provided..
        /// </summary>
        internal static string AKBURA_SEMANTIC_TailwindUtilityArgumentMismatch {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_TailwindUtilityArgumentMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AKCSS import &apos;{0}&apos; was not found..
        /// </summary>
        internal static string AKBURA_SEMANTIC_AkcssImportNotFound {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_AkcssImportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State binding expression &apos;{0}&apos; must be a binding path such as &apos;vm&apos;, &apos;vm.Name&apos;, or &apos;vm.Items[0].Name&apos;..
        /// </summary>
        internal static string AKBURA_SEMANTIC_StateBindingExpressionExpected {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_StateBindingExpressionExpected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State binding source &apos;{0}&apos; cannot be observed as &apos;{1}&apos;. Use IObservable&lt;{1}&gt; or implement INotifyPropertyChanged on &apos;{2}&apos;..
        /// </summary>
        internal static string AKBURA_SEMANTIC_StateBindingSourceNotObservable {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_StateBindingSourceNotObservable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State binding target &apos;{0}&apos; must be a writable property or field..
        /// </summary>
        internal static string AKBURA_SEMANTIC_StateBindingTargetNotWritable {
            get {
                return ResourceManager.GetString("AKBURA_SEMANTIC_StateBindingTargetNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error &apos;{0}&apos; was reported as a warning..
        /// </summary>
        internal static string WRN_ErrorOverride {
            get {
                return ResourceManager.GetString("WRN_ErrorOverride", resourceCulture);
            }
        }
    }
}
