using System.ComponentModel;

namespace Akbura.HotReload;

/// <summary>Retains the owned portion of one generated collection slot across ordinary updates.</summary>
[EditorBrowsable(EditorBrowsableState.Never)]
[Browsable(false)]
public sealed class AkburaRenderCollectionOwner<T>
{
    private IList<T>? _target;
    private T[] _items = [];
    private int _anchor = -1;

    /// <summary>Replaces generated entries, preserving foreign entries and their relative order.</summary>
    public void Reconcile(IList<T> target, T[] desiredItems)
    {
        ArgumentNullException.ThrowIfNull(target);
        ArgumentNullException.ThrowIfNull(desiredItems);
        if (_target != null && !ReferenceEquals(_target, target))
        {
            Clear();
        }

        _anchor = AkburaRenderCollectionReconciler.Reconcile(target, _items, desiredItems, _anchor);
        _target = target;
        _items = desiredItems;
    }

    /// <summary>Removes only entries generated by this owner.</summary>
    public void Clear()
    {
        if (_target != null)
        {
            AkburaRenderCollectionReconciler.Reconcile(_target, _items, Array.Empty<T>(), _anchor);
        }

        _target = null;
        _items = [];
        _anchor = -1;
    }
}
