using Akbura.Pools;
using Microsoft.CodeAnalysis.Text;
using System.Diagnostics;
using System.Text;
using System.Threading;

namespace Akbura.Language.CodeGeneration;

/// <summary>
/// Writes one complete generated C# document for an AKCSS module.
/// </summary>
internal static class AkcssDocumentWriter
{
    private const string HintNamePrefix = "Akbura.Akcss.";
    private const string HexDigits = "0123456789abcdef";

    public static string GetHintName(in AkcssGenerationInput input) =>
        GetHintName(input.ModuleIdentity);

    public static string GetHintName(string moduleIdentity)
    {
        var identity = AkcssGeneratedModuleNames.NormalizeSourcePath(moduleIdentity);
        var pooled = PooledStringBuilder.GetInstance();
        var builder = pooled.Builder;

        builder.Append(HintNamePrefix);
        AppendSanitizedIdentity(builder, identity);
        builder.Append('.');
        AppendStableHash(builder, AkcssGeneratedModuleNames.GetStableHash(identity));
        builder.Append(".g.cs");

        return pooled.ToStringAndFree();
    }

    public static SourceText Generate(
        in AkcssGenerationInput input,
        AkcssGenerationSourceMap sourceMap,
        string rootNamespace,
        CancellationToken cancellationToken = default)
    {
        Debug.Assert(input.Module != null);
        Debug.Assert(input.SemanticModel != null);
        Debug.Assert(!string.IsNullOrWhiteSpace(input.SourcePath));
        Debug.Assert(!string.IsNullOrWhiteSpace(input.ModuleIdentity));
        AkburaDebug.Assert(sourceMap != null);

        cancellationToken.ThrowIfCancellationRequested();

        var plan = AkcssModulePlanner.Create(input, rootNamespace, cancellationToken);

        try
        {
            using var writer = new CodeWriter();

            var moduleWriter = new AkcssModuleWriter(writer, sourceMap);

            WriteHeader(writer, input);

            cancellationToken.ThrowIfCancellationRequested();

            moduleWriter.WriteAssemblyReference(plan);
            writer.WriteLine();

            writer.Write("namespace ");
            writer.Write(plan.GeneratedNamespace);
            writer.WriteLine();
            writer.WriteLine("{");
            writer.CurrentIndent += writer.TabSize;

            moduleWriter.WriteDeclarationAttributes(plan);

            writer.Write("public static class ");
            writer.Write(plan.GeneratedTypeName);
            writer.WriteLine();
            writer.WriteLine("{");
            writer.CurrentIndent += writer.TabSize;

            WriteModuleBody(writer, moduleWriter, plan, cancellationToken);

            writer.CurrentIndent -= writer.TabSize;
            writer.WriteLine("}");

            writer.CurrentIndent -= writer.TabSize;
            writer.WriteLine("}");

            cancellationToken.ThrowIfCancellationRequested();

            return writer.GetText();
        }
        finally
        {
            plan.ReturnToPool();
        }
    }

    private static void WriteHeader(CodeWriter writer, in AkcssGenerationInput input)
    {
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#nullable enable");

        var syntaxWriter = new CSharpSyntaxWriter(writer);
        var externAliases = input.SemanticModel.GetCSharpExternAliases();

        for (var i = 0; i < externAliases.Length; i++)
        {
            syntaxWriter.WriteNormalizedNode(externAliases[i]);
        }

        var usingDirectives = input.UsingDirectives;

        for (var i = 0; i < usingDirectives.Length; i++)
        {
            var directive = usingDirectives[i];
            var isDuplicate = false;

            for (var j = 0; j < i; j++)
            {
                if (directive.IsEquivalentTo(usingDirectives[j], topLevel: false))
                {
                    isDuplicate = true;
                    break;
                }
            }

            if (!isDuplicate)
            {
                syntaxWriter.WriteNormalizedNode(directive);
            }
        }

        writer.WriteLine();
    }

    private static void WriteModuleBody(
        CodeWriter writer,
        AkcssModuleWriter moduleWriter,
        in AkcssModulePlan plan,
        CancellationToken cancellationToken)
    {
        moduleWriter.WriteConstants(plan);

        writer.WriteLine();

        moduleWriter.WriteStyleCollection(plan);

        if (!plan.Symbols.IsEmpty)
        {
            writer.WriteLine();
            moduleWriter.WriteMetadataCarriers(plan);
        }

        cancellationToken.ThrowIfCancellationRequested();

        if (HasGeneratedRuntimeStyles(plan))
        {
            writer.WriteLine();

            var wroteRuntimeStyles = moduleWriter.WriteRuntimeStyles(plan);

            Debug.Assert(wroteRuntimeStyles);
        }

        cancellationToken.ThrowIfCancellationRequested();
    }

    private static bool HasGeneratedRuntimeStyles(in AkcssModulePlan plan)
    {
        for (var i = 0; i < plan.Symbols.Length; i++)
        {
            ref readonly var symbol = ref plan.Symbols.ItemRef(i);

            if (symbol.EmitsRuntimeStyle &&
                symbol.Kind is AkcssSymbolGenerationKind.Style or AkcssSymbolGenerationKind.Utility)
            {
                return true;
            }
        }

        return false;
    }

    private static void AppendSanitizedIdentity(StringBuilder builder, string identity)
    {
        for (var i = 0; i < identity.Length; i++)
        {
            var character = identity[i];

            builder.Append(
                char.IsLetterOrDigit(character) ||
                character is '_' or '-' or '.'
                    ? character
                    : '_');
        }
    }

    private static void AppendStableHash(StringBuilder builder, uint hash)
    {
        for (var shift = 28; shift >= 0; shift -= 4)
        {
            builder.Append(HexDigits[(int)(hash >> shift) & 0xF]);
        }
    }
}
