using Akbura.Language.Symbols;
using Akbura.Language.Syntax;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading;

namespace Akbura.Language.CodeGeneration;

/// <summary>
/// Writes one complete generated C# document for an Akbura component.
/// </summary>
internal static class ComponentDocumentWriter
{
    public static string GetHintName(
        IAkburaComponentSymbol component,
        string sourcePath)
    {
        if (component == null)
        {
            throw new ArgumentNullException(nameof(component));
        }

        var identity = string.IsNullOrWhiteSpace(sourcePath)
            ? component.MetadataName
            : sourcePath;

        var sanitizedIdentity = SanitizeHintPart(identity);
        var hash = AkcssGeneratedModuleNames.GetStableHash(identity);

        return "Akbura.Component." +
            sanitizedIdentity +
            "." +
            hash.ToString("x8") +
            ".g.cs";
    }

    public static SourceText Generate(
        IAkburaComponentSymbol component,
        AkburaSemanticModel semanticModel,
        string sourcePath,
        IReadOnlyDictionary<AkburaSyntax, string> akcssModuleTypeNames,
        CancellationToken cancellationToken = default)
    {
        if (component == null)
        {
            throw new ArgumentNullException(nameof(component));
        }

        if (semanticModel == null)
        {
            throw new ArgumentNullException(nameof(semanticModel));
        }

        if (string.IsNullOrWhiteSpace(sourcePath))
        {
            throw new ArgumentException(
                "The component source path cannot be empty.",
                nameof(sourcePath));
        }

        if (akcssModuleTypeNames == null)
        {
            throw new ArgumentNullException(nameof(akcssModuleTypeNames));
        }

        cancellationToken.ThrowIfCancellationRequested();

        using var codeWriter = new CodeWriter();
        using var componentWriter = new ComponentWriter(
            codeWriter,
            component,
            semanticModel,
            sourcePath,
            akcssModuleTypeNames);

        WriteHeader(
            codeWriter,
            semanticModel);

        var hasNamespace = !string.IsNullOrWhiteSpace(component.NamespaceName);

        if (hasNamespace)
        {
            codeWriter.Write("namespace ");
            codeWriter.Write(component.NamespaceName);
            codeWriter.WriteLine();
            codeWriter.WriteLine("{");
            codeWriter.CurrentIndent += codeWriter.TabSize;
        }

        WriteClassDeclaration(
            codeWriter,
            component);

        codeWriter.WriteLine("{");
        codeWriter.CurrentIndent += codeWriter.TabSize;

        WriteClassBody(
            codeWriter,
            componentWriter,
            cancellationToken);

        codeWriter.CurrentIndent -= codeWriter.TabSize;
        codeWriter.WriteLine("}");

        if (hasNamespace)
        {
            codeWriter.CurrentIndent -= codeWriter.TabSize;
            codeWriter.WriteLine("}");
        }

        cancellationToken.ThrowIfCancellationRequested();

        return codeWriter.GetText();
    }

    private static void WriteHeader(
        CodeWriter writer,
        AkburaSemanticModel semanticModel)
    {
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#nullable enable");

        var syntaxWriter = new CSharpSyntaxWriter(writer);
        var externAliases = semanticModel.GetCSharpExternAliases();

        for (var i = 0; i < externAliases.Length; i++)
        {
            syntaxWriter.WriteNormalizedNode(externAliases[i]);
        }

        var usingDirectives = semanticModel.GetCSharpUsingDirectives();

        for (var i = 0; i < usingDirectives.Length; i++)
        {
            syntaxWriter.WriteNormalizedNode(usingDirectives[i]);
        }

        writer.WriteLine();
    }

    private static void WriteClassDeclaration(
        CodeWriter writer,
        IAkburaComponentSymbol component)
    {
        var valueWriter = new CSharpValueWriter(writer);

        writer.Write(GetAccessibility(component.PartialTypes));
        writer.Write(" partial class ");
        valueWriter.WriteIdentifier(component.Name);
        writer.Write(" : ");

        if (component.BaseType.Symbol is ITypeSymbol { TypeKind: not TypeKind.Error } baseType)
        {
            valueWriter.WriteTypeName(baseType);
        }
        else
        {
            writer.Write("global::Akbura.AkburaControl");
        }

        writer.WriteLine();
    }

    private static void WriteClassBody(
        CodeWriter writer,
        ComponentWriter componentWriter,
        CancellationToken cancellationToken)
    {
        if (componentWriter.WriteComponentMembers())
        {
            writer.WriteLine();
        }

        cancellationToken.ThrowIfCancellationRequested();

        if (componentWriter.WriteElementFields())
        {
            writer.WriteLine();
        }

        if (componentWriter.WriteLifecycleFields())
        {
            writer.WriteLine();
        }

        if (componentWriter.WriteStaticMembers())
        {
            writer.WriteLine();
        }

        if (componentWriter.WriteFactoryMethods())
        {
            writer.WriteLine();
        }

        cancellationToken.ThrowIfCancellationRequested();

        if (componentWriter.WritePropertySubscriptionHandlers())
        {
            writer.WriteLine();
        }

        if (componentWriter.WriteDeferredContentBuilders())
        {
            writer.WriteLine();
        }

        componentWriter.WriteLifecycleMembers();
        writer.WriteLine();

        componentWriter.WriteDescriptorMembers();
    }

    private static string GetAccessibility(ImmutableArray<INamedTypeSymbol> partialTypes)
    {
        if (partialTypes.IsDefaultOrEmpty)
        {
            return "internal";
        }

        return partialTypes[0].DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.Internal => "internal",
            _ => "internal",
        };
    }

    private static string SanitizeHintPart(string value)
    {
        var characters = value.ToCharArray();

        for (var i = 0; i < characters.Length; i++)
        {
            var character = characters[i];

            if (char.IsLetterOrDigit(character) ||
                character is '_' or '-' or '.')
            {
                continue;
            }

            characters[i] = '_';
        }

        return new string(characters);
    }
}
