using Akbura.Language.CodeGeneration;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;

namespace Akbura.BlackSilence;

internal static class HotReloadServiceWriter
{
    public const string HintName = "Akbura.HotReloadService.g.cs";

    public static GeneratedSource Generate(
        string assemblyName,
        ImmutableArray<string> componentTypeNames,
        IReadOnlyDictionary<string, ImmutableArray<string>>? akcssModuleTypeNamesByComponent = null)
    {
        var handlerTypeName = GetHandlerTypeName(assemblyName);
        var orderedTypeNames = GetOrderedTypeNames(componentTypeNames);

        using var writer = new CodeWriter();

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#if DEBUG");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine(
            "[assembly: global::System.Reflection.Metadata.MetadataUpdateHandlerAttribute(");
        writer.CurrentIndent += writer.TabSize;
        writer.Write("typeof(global::Akbura.Generated.");
        writer.Write(handlerTypeName);
        writer.WriteLine("))]");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine();
        writer.WriteLine("namespace Akbura.Generated");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteHiddenApiAttributes();
        writer.WriteLine(
            "[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        writer.Write("internal static class ");
        writer.WriteLine(handlerTypeName);
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;

        WriteClearCache(writer);
        writer.WriteLine();
        WriteUpdateApplication(writer);
        writer.WriteLine();
        WriteUpdateApplicationCore(
            writer,
            handlerTypeName,
            orderedTypeNames,
            akcssModuleTypeNamesByComponent);
        writer.WriteLine();
        WriteReloadAll(writer, orderedTypeNames);
        writer.WriteLine();
        WriteReload(writer, orderedTypeNames);
        writer.WriteLine();
        WriteOrderBaseTypesFirst(writer);
        writer.WriteLine();
        WriteAffects(writer);
        writer.WriteLine();
        WriteContainsType(writer);
        writer.WriteLine();
        WriteThrowRefreshFailures(writer);

        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine("#endif");

        return new GeneratedSource(HintName, writer.GetText());
    }

    private static void WriteClearCache(CodeWriter writer)
    {
        writer.WriteLine(
            "internal static void ClearCache(global::System.Type[]? updatedTypes)");
        writer.WriteLine("{");
        writer.WriteLine("}");
    }

    private static void WriteUpdateApplication(CodeWriter writer)
    {
        writer.WriteLine(
            "internal static void UpdateApplication(global::System.Type[]? updatedTypes)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "if (global::Avalonia.Threading.Dispatcher.UIThread.CheckAccess())");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("UpdateApplicationCore(updatedTypes);");
        writer.WriteLine("return;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine(
            "global::Avalonia.Threading.Dispatcher.UIThread.Post(");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("() => UpdateApplicationCore(updatedTypes));");
        writer.CurrentIndent -= writer.TabSize;
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteUpdateApplicationCore(
        CodeWriter writer,
        string handlerTypeName,
        string[] componentTypeNames,
        IReadOnlyDictionary<string, ImmutableArray<string>>? akcssModuleTypeNamesByComponent)
    {
        writer.WriteLine("private static void UpdateApplicationCore(");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("global::System.Type[]? updatedTypes)");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("if (updatedTypes is null ||");
        writer.CurrentIndent += writer.TabSize;
        writer.Write("ContainsType(updatedTypes, typeof(");
        writer.Write(handlerTypeName);
        writer.WriteLine(")))");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("ReloadAll();");
        writer.WriteLine("return;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.Write("var __componentTypes = new global::System.Type[");
        writer.WriteIntegerLiteral(componentTypeNames.Length);
        writer.WriteLine("];");
        writer.WriteLine("var __componentCount = 0;");

        for (var i = 0; i < componentTypeNames.Length; i++)
        {
            var componentTypeName = componentTypeNames[i];
            var moduleTypeNames = GetOrderedModuleTypeNames(
                componentTypeName,
                akcssModuleTypeNamesByComponent);

            writer.WriteLine();
            writer.WriteLine("if (Affects(");
            writer.CurrentIndent += writer.TabSize;
            writer.WriteLine("updatedTypes,");
            writer.Write("typeof(");
            WriteTypeName(writer, componentTypeName);
            writer.Write("))");

            for (var moduleIndex = 0; moduleIndex < moduleTypeNames.Length; moduleIndex++)
            {
                writer.WriteLine(" ||");
                writer.Write("Affects(updatedTypes, typeof(");
                WriteTypeName(
                    writer,
                    moduleTypeNames[moduleIndex]);
                writer.Write("))");
            }

            writer.WriteLine(")");
            writer.CurrentIndent -= writer.TabSize;
            writer.WriteLine("{");
            writer.CurrentIndent += writer.TabSize;
            writer.Write("__componentTypes[__componentCount++] = typeof(");
            WriteTypeName(writer, componentTypeName);
            writer.WriteLine(");");
            writer.CurrentIndent -= writer.TabSize;
            writer.WriteLine("}");
        }

        writer.WriteLine();
        writer.WriteLine(
            "Reload(__componentTypes, __componentCount);");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteReloadAll(
        CodeWriter writer,
        string[] componentTypeNames)
    {
        writer.WriteLine("private static void ReloadAll()");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.Write("var __componentTypes = new global::System.Type[");
        writer.WriteIntegerLiteral(componentTypeNames.Length);
        writer.WriteLine("];");

        for (var i = 0; i < componentTypeNames.Length; i++)
        {
            writer.Write("__componentTypes[");
            writer.WriteIntegerLiteral(i);
            writer.Write("] = typeof(");
            WriteTypeName(writer, componentTypeNames[i]);
            writer.WriteLine(");");
        }

        writer.WriteLine();
        writer.WriteLine(
            "Reload(__componentTypes, __componentTypes.Length);");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteReload(
        CodeWriter writer,
        string[] componentTypeNames)
    {
        writer.WriteLine("private static void Reload(");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "global::System.Type[] componentTypes,");
        writer.WriteLine("int componentCount)");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "OrderBaseTypesFirst(componentTypes, componentCount);");
        writer.WriteLine(
            "global::System.Collections.Generic.List<global::System.Exception>? " +
            "__exceptions = null;");
        writer.WriteLine();
        writer.WriteLine(
            "for (var i = 0; i < componentCount; i++)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "var __componentType = componentTypes[i];");

        for (var i = 0; i < componentTypeNames.Length; i++)
        {
            writer.WriteLine();
            writer.Write("if (__componentType == typeof(");
            WriteTypeName(writer, componentTypeNames[i]);
            writer.WriteLine("))");
            writer.WriteLine("{");
            writer.CurrentIndent += writer.TabSize;
            WriteGuardedApplyInvocation(
                writer,
                componentTypeNames[i]);
            writer.WriteLine("continue;");
            writer.CurrentIndent -= writer.TabSize;
            writer.WriteLine("}");
        }

        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("ThrowRefreshFailures(__exceptions);");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteOrderBaseTypesFirst(
        CodeWriter writer)
    {
        writer.WriteLine(
            "private static void OrderBaseTypesFirst(");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "global::System.Type[] componentTypes,");
        writer.WriteLine("int componentCount)");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "for (var index = 1; index < componentCount; index++)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "var componentType = componentTypes[index];");
        writer.WriteLine();
        writer.WriteLine(
            "for (var candidateIndex = 0; candidateIndex < index; candidateIndex++)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "if (!componentType.IsAssignableFrom(componentTypes[candidateIndex]))");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("continue;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine(
            "for (var moveIndex = index; moveIndex > candidateIndex; moveIndex--)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "componentTypes[moveIndex] = componentTypes[moveIndex - 1];");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine(
            "componentTypes[candidateIndex] = componentType;");
        writer.WriteLine("break;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteAffects(CodeWriter writer)
    {
        writer.WriteLine("private static bool Affects(");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("global::System.Type[] updatedTypes,");
        writer.WriteLine("global::System.Type componentType)");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("for (var i = 0; i < updatedTypes.Length; i++)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("for (var type = updatedTypes[i];");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("type is not null;");
        writer.WriteLine("type = type.DeclaringType)");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("if (type == componentType ||");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("type.IsAssignableFrom(componentType))");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("return true;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("return false;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteContainsType(CodeWriter writer)
    {
        writer.WriteLine("private static bool ContainsType(");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("global::System.Type[] updatedTypes,");
        writer.WriteLine("global::System.Type expectedType)");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("for (var i = 0; i < updatedTypes.Length; i++)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("if (updatedTypes[i] == expectedType)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("return true;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("return false;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteThrowRefreshFailures(CodeWriter writer)
    {
        writer.WriteLine("private static void ThrowRefreshFailures(");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "global::System.Collections.Generic.List<global::System.Exception>? " +
            "exceptions)");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("if (exceptions == null)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("return;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("if (exceptions.Count == 1)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "global::System.Runtime.ExceptionServices.ExceptionDispatchInfo");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(".Capture(exceptions[0])");
        writer.WriteLine(".Throw();");
        writer.CurrentIndent -= writer.TabSize * 2;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("throw new global::System.AggregateException(");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "\"One or more component types could not be refreshed.\",");
        writer.WriteLine("exceptions);");
        writer.CurrentIndent -= writer.TabSize;
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteGuardedApplyInvocation(
        CodeWriter writer,
        string componentTypeName)
    {
        writer.WriteLine("try");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        WriteApplyInvocation(writer, componentTypeName);
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine("catch (global::System.Exception __exception)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "__exceptions ??= new global::System.Collections.Generic." +
            "List<global::System.Exception>();");
        writer.WriteLine("__exceptions.Add(__exception);");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteApplyInvocation(
        CodeWriter writer,
        string componentTypeName)
    {
        WriteTypeName(writer, componentTypeName);
        writer.WriteLine(".__AkburaHotReloadApply();");
    }

    private static void WriteTypeName(
        CodeWriter writer,
        string metadataName)
    {
        writer.Write("global::");

        if (metadataName.StartsWith(
                "global::",
                StringComparison.Ordinal))
        {
            metadataName = metadataName.Substring(
                "global::".Length);
        }

        var start = 0;
        while (start < metadataName.Length)
        {
            var separator = metadataName.IndexOf('.', start);
            var length = separator < 0
                ? metadataName.Length - start
                : separator - start;
            var part = metadataName.Substring(start, length);

            writer.WriteIdentifierEscapeIfNeeded(part);
            writer.Write(part);

            if (separator < 0)
            {
                break;
            }

            writer.Write(".");
            start = separator + 1;
        }
    }

    private static string[] GetOrderedTypeNames(
        ImmutableArray<string> componentTypeNames)
    {
        if (componentTypeNames.IsDefaultOrEmpty)
        {
            return [];
        }

        var names = componentTypeNames.ToArray();
        Array.Sort(names, StringComparer.Ordinal);

        var uniqueCount = 0;
        for (var i = 0; i < names.Length; i++)
        {
            if (string.IsNullOrWhiteSpace(names[i]) ||
                uniqueCount > 0 &&
                StringComparer.Ordinal.Equals(names[uniqueCount - 1], names[i]))
            {
                continue;
            }

            names[uniqueCount++] = names[i];
        }

        if (uniqueCount == names.Length)
        {
            return names;
        }

        var unique = new string[uniqueCount];
        Array.Copy(names, unique, uniqueCount);
        return unique;
    }

    private static string[] GetOrderedModuleTypeNames(
        string componentTypeName,
        IReadOnlyDictionary<string, ImmutableArray<string>>? akcssModuleTypeNamesByComponent)
    {
        return akcssModuleTypeNamesByComponent != null &&
            akcssModuleTypeNamesByComponent.TryGetValue(
                componentTypeName,
                out var moduleTypeNames)
                ? GetOrderedTypeNames(moduleTypeNames)
                : [];
    }

    internal static string GetHandlerTypeName(string assemblyName)
    {
        if (string.IsNullOrWhiteSpace(assemblyName))
        {
            throw new ArgumentException(
                "The assembly name cannot be null or whitespace.",
                nameof(assemblyName));
        }

        const ulong offsetBasis = 14695981039346656037UL;
        const ulong prime = 1099511628211UL;

        var hash = offsetBasis;
        for (var i = 0; i < assemblyName.Length; i++)
        {
            hash ^= assemblyName[i];
            hash *= prime;
        }

        return "HotReloadService_" +
            hash.ToString("X16", CultureInfo.InvariantCulture);
    }
}
