using Akbura.Language.CodeGeneration;
using System;
using System.Collections.Immutable;
using System.Globalization;

namespace Akbura.BlackSilence;

internal static class HotReloadServiceWriter
{
    public const string HintName = "Akbura.HotReloadService.g.cs";

    public static GeneratedSource Generate(
        string assemblyName,
        ImmutableArray<string> componentTypeNames)
    {
        var handlerTypeName = GetHandlerTypeName(assemblyName);
        var orderedTypeNames = GetOrderedTypeNames(componentTypeNames);

        using var writer = new CodeWriter();

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#if DEBUG");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine(
            "[assembly: global::System.Reflection.Metadata.MetadataUpdateHandlerAttribute(");
        writer.CurrentIndent += writer.TabSize;
        writer.Write("typeof(global::Akbura.Generated.");
        writer.Write(handlerTypeName);
        writer.WriteLine("))]");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine();
        writer.WriteLine("namespace Akbura.Generated");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteHiddenApiAttributes();
        writer.WriteLine(
            "[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        writer.Write("internal static class ");
        writer.WriteLine(handlerTypeName);
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;

        WriteClearCache(writer);
        writer.WriteLine();
        WriteUpdateApplication(writer);
        writer.WriteLine();
        WriteUpdateApplicationCore(
            writer,
            handlerTypeName,
            orderedTypeNames);
        writer.WriteLine();
        WriteReloadAll(writer, orderedTypeNames);
        writer.WriteLine();
        WriteAffects(writer);
        writer.WriteLine();
        WriteContainsType(writer);

        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine("#endif");

        return new GeneratedSource(HintName, writer.GetText());
    }

    private static void WriteClearCache(CodeWriter writer)
    {
        writer.WriteLine(
            "internal static void ClearCache(global::System.Type[]? updatedTypes)");
        writer.WriteLine("{");
        writer.WriteLine("}");
    }

    private static void WriteUpdateApplication(CodeWriter writer)
    {
        writer.WriteLine(
            "internal static void UpdateApplication(global::System.Type[]? updatedTypes)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine(
            "if (global::Avalonia.Threading.Dispatcher.UIThread.CheckAccess())");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("UpdateApplicationCore(updatedTypes);");
        writer.WriteLine("return;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine(
            "global::Avalonia.Threading.Dispatcher.UIThread.Post(");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("() => UpdateApplicationCore(updatedTypes));");
        writer.CurrentIndent -= writer.TabSize;
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteUpdateApplicationCore(
        CodeWriter writer,
        string handlerTypeName,
        string[] componentTypeNames)
    {
        writer.WriteLine("private static void UpdateApplicationCore(");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("global::System.Type[]? updatedTypes)");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("if (updatedTypes is null ||");
        writer.CurrentIndent += writer.TabSize;
        writer.Write("ContainsType(updatedTypes, typeof(");
        writer.Write(handlerTypeName);
        writer.WriteLine(")))");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("ReloadAll();");
        writer.WriteLine("return;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");

        for (var i = 0; i < componentTypeNames.Length; i++)
        {
            writer.WriteLine();
            writer.WriteLine("if (Affects(");
            writer.CurrentIndent += writer.TabSize;
            writer.WriteLine("updatedTypes,");
            writer.Write("typeof(");
            WriteTypeName(writer, componentTypeNames[i]);
            writer.WriteLine(")))");
            writer.CurrentIndent -= writer.TabSize;
            writer.WriteLine("{");
            writer.CurrentIndent += writer.TabSize;
            WriteApplyInvocation(writer, componentTypeNames[i]);
            writer.CurrentIndent -= writer.TabSize;
            writer.WriteLine("}");
        }

        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteReloadAll(
        CodeWriter writer,
        string[] componentTypeNames)
    {
        writer.WriteLine("private static void ReloadAll()");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;

        for (var i = 0; i < componentTypeNames.Length; i++)
        {
            WriteApplyInvocation(writer, componentTypeNames[i]);
        }

        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteAffects(CodeWriter writer)
    {
        writer.WriteLine("private static bool Affects(");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("global::System.Type[] updatedTypes,");
        writer.WriteLine("global::System.Type componentType)");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("for (var i = 0; i < updatedTypes.Length; i++)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("for (var type = updatedTypes[i];");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("type is not null;");
        writer.WriteLine("type = type.DeclaringType)");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("if (type == componentType ||");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("type.IsAssignableFrom(componentType))");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("return true;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("return false;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteContainsType(CodeWriter writer)
    {
        writer.WriteLine("private static bool ContainsType(");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("global::System.Type[] updatedTypes,");
        writer.WriteLine("global::System.Type expectedType)");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("for (var i = 0; i < updatedTypes.Length; i++)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("if (updatedTypes[i] == expectedType)");
        writer.WriteLine("{");
        writer.CurrentIndent += writer.TabSize;
        writer.WriteLine("return true;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("return false;");
        writer.CurrentIndent -= writer.TabSize;
        writer.WriteLine("}");
    }

    private static void WriteApplyInvocation(
        CodeWriter writer,
        string componentTypeName)
    {
        WriteTypeName(writer, componentTypeName);
        writer.WriteLine(".__AkburaHotReloadApply();");
    }

    private static void WriteTypeName(
        CodeWriter writer,
        string metadataName)
    {
        writer.Write("global::");

        var start = 0;
        while (start < metadataName.Length)
        {
            var separator = metadataName.IndexOf('.', start);
            var length = separator < 0
                ? metadataName.Length - start
                : separator - start;
            var part = metadataName.Substring(start, length);

            writer.WriteIdentifierEscapeIfNeeded(part);
            writer.Write(part);

            if (separator < 0)
            {
                break;
            }

            writer.Write(".");
            start = separator + 1;
        }
    }

    private static string[] GetOrderedTypeNames(
        ImmutableArray<string> componentTypeNames)
    {
        if (componentTypeNames.IsDefaultOrEmpty)
        {
            return [];
        }

        var names = componentTypeNames.ToArray();
        Array.Sort(names, StringComparer.Ordinal);

        var uniqueCount = 0;
        for (var i = 0; i < names.Length; i++)
        {
            if (string.IsNullOrWhiteSpace(names[i]) ||
                uniqueCount > 0 &&
                StringComparer.Ordinal.Equals(names[uniqueCount - 1], names[i]))
            {
                continue;
            }

            names[uniqueCount++] = names[i];
        }

        if (uniqueCount == names.Length)
        {
            return names;
        }

        var unique = new string[uniqueCount];
        Array.Copy(names, unique, uniqueCount);
        return unique;
    }

    internal static string GetHandlerTypeName(string assemblyName)
    {
        if (string.IsNullOrWhiteSpace(assemblyName))
        {
            throw new ArgumentException(
                "The assembly name cannot be null or whitespace.",
                nameof(assemblyName));
        }

        const ulong offsetBasis = 14695981039346656037UL;
        const ulong prime = 1099511628211UL;

        var hash = offsetBasis;
        for (var i = 0; i < assemblyName.Length; i++)
        {
            hash ^= assemblyName[i];
            hash *= prime;
        }

        return "HotReloadService_" +
            hash.ToString("X16", CultureInfo.InvariantCulture);
    }
}
